const EN_TRANSLATIONS = {
    "CREATE_PROJECT": "Create Project",
    "CREATE_NEW_PROJECT": "Create New Project",
    "PROJECT": "Project",
    "PROJECTS": "Projects",
    "NEW": "NEW",
    "PROJECT_PAGE.NO_PROJECTS": "You don't have any projects. Create you first project today!",
    "SEARCH_DOTS": "Search...",
    "SEARCH": "Search",
    "RECENT": "RECENT    ",
    "NAME_A-Z": "Name A-Z",
    "NAME_Z-A": "Name Z-A",
    "CREATED": "Created",
    "DEADLINE": "Deadline",
    "CLIENT": "Client",
    "LOCATION" : "Location",
    "TAGS" : "Tags",
    "AUTOROTATE": "Autospin",
    "MODEL_ROTATE": "Model rotates slowly around its center.",
    "CONTACT_US-HEADER": "Contact Us",
    "CONTACT_EMAIL-MESSAGE": "Please contact sales@modelo.io",

    "MISSING_AUXILARY_FILES":"Seems like the model you’re uploading is missing a <mark>mtl</mark> file…Try to zip the obj and mtl files and reupload.",
    "I/O_ERROR":"Seems like the model you’re uploading is missing a <mark>mtl</mark> file…Try to zip the obj and mtl files and reupload.",
    "MODEL_DOES_NOTCONTAIN_A_MESH":"Seems like the model you’re uploading is not built by <mark>triangular mesh</mark> completely or missing <mark>geometric data</mark>…",
    "MODEL_NEEDS_TO_BE_TRIANGULATED":"Seems like the model you’re uploading is not built by <mark>triangular mesh</mark> completely or missing <mark>geometric data</mark>…",

    "TRANSFER_PROJECT": "Transfer project",
    "CHANGE_THUMBNAIL": "Change thumbnail",
    "LEAVE_PROJECT": "Leave project",
    "DELETE_PROJECT": "Delete project",
    "CREATE": "Create",
    "CANCEL": "Cancel",
    "PROJECT_NAME": "Project Name",
    "COMMENT_RENDER_RADIUS": "Range",
    "MODELS": "Models",
    "ALL_MODELS":"Models",
    "ASSETS": "Assets",
    "PROJECT_OVERVIEW-MOBILE": "Overview",
    "PROJECT_OVERVIEW": "Project Overview",
    "TEAM_MEMBERS-MOBILE": "Members",
    "TEAM_MEMBERS": "Team Members",
    "PROJECT_BRIEF": "Project Brief",
    "EDIT": "Edit",
    "RENDER_EDIT": "Edit",
    "SAVE": "Save",

    "PROJECT_SIZE": "Project Size",
    "TOTAL_MODELS": "Total Models",
    "TOTAL_REVIEWS": "Total Reviews",
    "TOTAL_ASSETS": "Total Assets",
    "TOTAL_IMAGE_360": "Total Image 360",

    "NAME-FILE": "Name",
    "CREATED_ON": "Created On",
    "ITEMS": "Items",

    "MINS":"mins",
    "INVALID_DATE":"Invalid date",
    "SMOE_ONE_ACCOUNT":"'s Account",
    "MODELS":"models",
    "REVIEWS":"reviews",
    "MODELS_PLURAL":"models",
    "FOLDER":"folder",
    "MODEL":"model",
    "FAQ":"FAQ",
    "DETAIL":"Detail",
    "VIEW":"View",
    "YOUR_MODEL":"Your model",
    "MODEL_PROCESSED":"has been processed and is now ready to view.",
    "HIDE_BRANDING":"Hide branding",
    "ADD_BIM_AND_PROPERTIES_MODEL":"Add BIM elements and properties to your model",
    "IMPORT_BIM_AND_PROPERTIES_FROM_REVIT_MODELS":"Modelo can now import BIM elements and properties from Revit models to give you even more insight into your designs. Contact your Account Executive to trial and purchase this feature.",
    "RENDER":"render",
    "REVIEW":"review",

    "UPLOAD_CANCELLED": "Upload Cancelled",
    "UPLOAD": "Upload",

    "NEW_FOLDER": "New Folder",
    "UPLOAD_KEY": "upload key",
    "CURIOUS_ABOUT_RENDERING_SERVICE": "Curious about our 3D rendering service?",
    "SHARE": "Share",
    "RENAME": "Rename",
    "DELETE": "Delete",

    "VIEW": "View",
    "VIEW-PREVIEW": "View",
    "MARKUP": "Markup",
    "VIEW_FOLDER": "View folder",
    "REUPLOADING": "Reuploading",

    "CUSTOMIZE_PERMISSIONS": "Customize permissions",
    "ADD_COMPANY_MEMBERS": "Add Company Members",
    "UPGRADE_TO_ADD_NEW_MEMBERS": "Upgrade seats to add new members",
    "ADD_VIEW_ONLY_SEATS": "Add view-only seats",
    "UPGRADE_TO_ADD_NEW_CLIENTS": "Upgrade seats to add clients",
    "STATUS": "Status",
    "PENDING": "Pending",
    "INVITE_RESENT": "Invite Resent",
    "INVITE_RESEND": "Resend Invitation",
    "CANCEL_INVITE": "Cancel Invitation",
    "LICENSES": "Licenses",
    "VIEW_ONLY_LICENSES": "View-only licenses",
    "UPLOAD_MODEL": "Upload Model",

    "ADMIN": "Admin",
    "TEAM_MEMBER": "Team member",
    "VIEW_ONLY": "View only",
    "OWNER": "Owner",

    "VIEW_3D": "View 3D",
    "VIEW_MODEL": "View model",

    "NO_UPDATES_ON_THIS_MODEL": "No updates in this model",
    "ANY_FEEDBACK_WILL_APPEAR_HERE": "Any feedback you made in model page will appear here",

    "DATE_CREATED": "Date Created",
    "DATE_UPDATED": "Date Updated",

    "FILTER": "Filter",
    "SCENE_SETTING_CREATE": "New scene setting",
    "SNAPSHOTS": "Snapshots",
    "3D_COMMENTS": "3D comments",
    "IMPORTED_VIEWS": "Imported views",
    "SKETCHES": "Sketches",
    "RENDERINGS": "Renderings",
    "RENDER_SIZE": "Rendering size",
    "INVITE_USERS_TO_THIS_CCOMPANY": "Invite users to this Company",
    "DO_NOT_HAVE_ENOUGH_SEATS_TO_INVITE_ALL_EMAILS": "Do not have enough seats to invite all emails",
    "INVITE_USERS": "Invite Users",
    "ADD_PEOPLE_TO_PROJECT": "Add people to project",
    "ADD_PEOPLE_TO_COMPANY": "Add people to company",

    "WHO_IS_IN_THIS_PROJECT": "Who is in this project",
    "PROJECT_MEMBER": "Project member",
    "UPGRADE_TO_INVITE_CLIENTS_TO_PROJECT": "Upgrade to invite view-only",
    "YES": "Yes",
    "OK": "Ok",
    "OK_UPPER": "OK",

    "UPLOAD_IMAGE": "Upload image",
    "SELECT_A_PHOTO_FROM_YOUR_COMPUTER": "Select a photo from your computer",

    "NO": "No",
    "INVITE_PEOPLE_TO_PROJECT": "Invite people to project",
    "BILLING_CONTROL": "Billing Control",
    "AN_UNKNOWN_ERROR_HAS_OCCURED_WHEN_SAVING_PERMISSIONS": "An unknown error has occurred when saving permissions",

    "FEATURES": "Features",
    "CAN_SHARE": "Can share",
    "SHARE_DOWNLOAD_MODELS": "Share, download models",
    "SHARE_DOWNLOAD_ASSETS": "Share, download assets",
    "SHARE_DOWNLOAD_MDOEL_REVIEWS": "Share, download model reviews",

    "CAN_EDIT": "Can edit",
    "UPDATE_AND_DELETE_FOLDERS_IN_PROJECTS": "Update and delete folders in projects",
    "DELETE_MODELS_AND_MODEL_REVIEWS": "Delete models and model reviews",
    "DELETE_ASSETS": "Delete assets",
    "TOGGLE_CLIENT_READY": "Toggle client ready",

    "ALL_MODELS_IN_THIS_FOLDER_WILL_BE_DELETED": "All models in this folder will be deleted",

    "ALL_TEAM_MEMBERS": "All team members",
    "WILL_LOSE_ACCESS_TO_THIS_PROJECT": "will lose access to this project.",
    "PLEASE_TYPE_DELETE_TO_CONFIRM": "Please type DELETE to confirm:",
    "DOES_NOT_MATCH_DELETE": "Does not match DELETE",

    "MATERIAL_SETTING_ZOOM_HORIZONTAL": "Scale x",
    "MATERIAL_SETTING_ZOOM_VERTICAL": "Scale y",
    "MATERIAL_SETTING_ANGLE": "Angle",
    "MATERIAL_SETTING_SMOOTHNESS": "Smoothness",
    "MATERIAL_SETTING_REFLECT": "Reflect",
    "MATERIAL_SETTING_HORIZONTAL_OFFSET": "Offset x",
    "MATERIAL_SETTING_VERTICAL_OFFSET": "Offset y",

    "EMAIL_MODEL_REVIEWS": "Email Model Reviews",
    "ADD_MESSAGE": "Add Message",
    "SEND": "send",
    "RNDERING": "Rendering",
    "MATERIAL_SCENE": "Shader",
    "MATERIAL_IMAGE": "Texture map",
    "SIZE": "Size",
    "PIXELS": "pixels",
    "MATERIAL_INDOOR": "indoor",
    "MATERIAL_OUTDOOR": "outdoor",
    "MATERIAL_COLLECT": "collect",
    "MATERIAL_COLLECT_ALL": "collect all",
    "MATERIAL_INDOOR_ALL": "indoor all",
    "MATERIAL_OUTDOOR_ALL": "outdoor all",
    "RENDER_VIEW_INIT-HEADER": "The model is being converted ...",
    "RENDER_RENDERING": "Rendering",
    "RENDER_PANORAMA": "Panorama",
    "RENDER_VIEW_INIT-HEADER": "The model you uploaded is in preparation for rendering...",
    "RENDER_VIEW_INIT-MESSAGE": "It may take a few minutes, please try again later.",
    "RENDER_VIEW_ERROR-HEADER": "The model you uploaded seems a bit advanced...",
    "RENDER_VIEW_ERROR-MESSAGE": "Send the report to support@modeloapp.com, we have professionals to help you solve the problem.",
    "RENDER_VIEW_ERROR_REPORT": "SEND A REPORT",
    "NOTIFICATION-RENDER_VIEW_ERROR_REPORT_SUCCESS": "Rendering report was sent successfully!",
    "RENDER_VIEW_STOP-MESSAGE": "The remaining 360 Panoramas will not be saved.",
    "RENDER_VIEW_STOP-HEADER": "Are you sure you want to quit？",

    "DEFAULT_SCENE": "Default",
    "CHOOSE_A_FILE_FROM_YOUR_ASSETS": "Choose a file from your assets",
    "CHOOSE_FILE": "Selected files",
    "ADD_A_FOLDER": "Add a Folder",
    "PLEASE_ADD_A_FOLDER_BEFORE_UPLOADING_A_FILE": "Please add a folder before uploading a file",
    "CHOOSE": "CHOOSE",

    "SAVE_CHANGES": "Save Changes",
    "DO_YOU_WANT_TO_SAVE_THE_CURRENT_CHANGES": "Do you want to save the current changes?",

    "MODEL_FILE_SIZE_EXCEEDS_THE_LIMIT": "Model file size exceeds the limit",
    "YOUR_FREE_ACCOUNT_CAN_VIEW": "Your free account can view model file up to 50MB. This file is greater than 50MB, please upgrade your plan to view it.",
    "OK_GOT_IT": "OK, got it",

    "ARE_YOU_SURE_TO_LEAVE": "Are you sure you would like to leave this project?",
    "LEAVE": "Leave",

    "SET_STARTING_VIEW": "Set starting view",
    "SAVE_AS_STARTING_VIEW": "Save as starting view",
    "SORRY_ATTACHMENT_UNAVAILABLE": "We're sorry, this attachment is unavailable. It may have been deleted from the assets management page.",
    "NO_PREVIEW_AVAILABLE": "No preview available",

    "MODEL_CONVERSION_ERROR": "Seems like you are building a very unique model... We've already informed our team and will contact you once it's fixed.",
    "OTHER_ERROR": "Seems like you are building a very unique model... We've already informed our team and will contact you once it's fixed.",
    "FAILED_TO_FIND_SUCH_FILE_ON_THE_DISK": "Seems like you are building a very unique model... We've already informed our team and will contact you once it's fixed.",
    "READING_OR_PARSING_THE_FILE_ERROR": "Seems like you are building a very unique model... We've already informed our team and will contact you once it's fixed.",
    "NOT_SUPPORTED_FILE_FORMAT": "Seems like you are building a very unique model... We've already informed our team and will contact you once it's fixed.",
    "INPUT_FORMAT_IS_NEWER_THAN_COVNERTER": "Seems like you are building a very unique model... We've already informed our team and will contact you once it's fixed.",
    "DEFAULT_ERROR": "Seems like you are building a very unique model... We've already informed our team and will contact you once it's fixed.",

    "MODEL_CONVERSION_ERROR_FILE_TOO_LONG": "Looks like some of the files or textures you're trying to upload are too long.  Try shortening the file names or reducing folder nesting.",
    "CONVERSION_TAKES_TOO_LONG": "Seems like the model you’re uploading is too <mark>BIG</mark>… Try to reduce the file size or contact sales@modelo.io for help.",
    
    "CLOSE": "Close",

    "OVER_PLAN_SPACE": "Over plan storage space",
    "UPGRADE_PLAN": "You are currently over the storage space for your plan. Before you can use any more space you need to upgrade your plan",

    "OVER_PLAN_SPACE-HEADER": "Over plan storage space",
    "OVER_PLAN_SPACE-MESSAGE": "You are currently over the storage space for your plan. Before you can use any more space you need to upgrade your plan",

    "HERE": "here",

    "RENDERING_SERVICE": "Rendering Service",
    "RENDERING_SERVICES_MESSAGE": "Thank you for inquiring about our rendering services. Your request has been successfully sent to your account manager who will be in touch within 1 business day.",
    "VIEW_SAMPLE_LINK-EXAMPLE": "VIEW SAMPLE LINK",

    "HIGH_QUALITY_RENDERING": "Want high quality renderings? Let us help.",
    "COLLABORATE_WITH_PROMINENT_RENDERING_COMPANIES": "Modelo is collaborating with prominent rendering companies in order to deliver 3D architectural renderings straight to you.",
    "BECOME_A_PARTNER": "Become a partner",
    "INQUIRE_ABOUT_RENDERINGS": "Inquire about Renderings",
    "DO_NOT_SHOW_ME_THIS_MESSAGE_AGAIN": "Don't show me this message again",
    "FOLLOW_UP_MESSAGE": "Great! We've received your request and will follow-up with more information within 24 hours.",
    "PROBLEMS_GETTING_CONTACT_WITH_SALES": "Looks like there was an issue getting in touch with sales.  Feel free to directly reach out to us at sales@modelolio for more information regarding our rendering service.",

    "SHARE_MODEL": "Share Model",
    "SHARE_3D_MODEL_PAGE": "Share 3D model page",
    "SHARE_MODEL_FILE": "Share Model File",
    "HOLD_DOWN_TO_COPY_LINK": "Hold down to copy link",
    "START_SCREEN": "Start screen",
    "CHOOSE_INITIAL_SCREEN": "Choose the initial screen after model loaded",
    "SHOW_COMMENT_CARD": "Show comment card",
    "PEOPLE_CAN_VIEW_COMMENT_CARDS_FROM_THIS_MODEL": "People can view comment cards from this model",
    "SHOW_WALKTHROUGH": "Show walkthrough",
    "SCENESETTING": "Scene setting",
    "PEOPLE_CAN_VIEW_ANY_WALKTHROUGH_FROM_THIS_MODEL": "People can view any walkthrough from this model",
    "HIDE_COMMENT_DETAILS": "Hide comment details",
    "COMMENTS_AUTHOR_AND_DATE_WILL_NOT_SHOW": "Comments' author and created date will not show",
    "LIMIT_AREA_TO_VIEW": "Using it to limit the area people can view",
    "RESTRICTED_VIEW_REQUIRES_COMMENTS": "Restricted view requires comments.",
    "PREVIEW": "Preview",

    "RESTRICTED_VIEW": "Restricted view",
    "RESTRICTED_VIEW_INSTRUCTION": "When restricted view is on, viewers will only be able to use first person view to go through the model",
    "PAN": "Pan",
    "ZOOM": "Zoom",
    "ROTATE": "Rotate",
    "COMMENT": "Comment",
    "FIRST_PERSON_VIEW_FROM_COMMENT": "First person view from comment",
    "OFF": "Off",

    "WELCOME_NEW_LIGHT_ACCOUNT": "Welcome to your new Light Account!",
    "TRANSFER_ALL_MODELS": "Now that you've transferred all of your projects into your Light account, you can start to enjoy the many perks that come with your new account, things like:",
    "UP_TO_750M_MODEL_UPLOADS": "Up to 750MB Model Uploads",
    "EMBED_MODE_LINKS": "Embed Model Links",
    "CLIENT_SHARE_LINKS": "Client Share Links",
    "COMPANY_USER_PERMISSION_CONTROLS": "Company User permission controls",
    "ENJOY": "Enjoy!",

    "TRANSFER_TO_ANOTHER_COMPANY": "Transfer project to another company",
    "NO_COMPANY_ACCEPTS_THIS_PROJECT": "Currently there are no eligible companies to accept this project",
    "TRANSFER_TERMS": "Transfer Terms",
    "NO_TRANSFER_FROM_PAID_TO_FREE_COMPANY": "Projects may not be transferred from a paid company to a free company. In order for a company to be eligible to receive a project transfer you must be a member with a role of admin or owner. We reserve the right to change these terms and at any time.",
    "TRANSFER": "Transfer",
    "TRANSFER_ERROR_MESSAGE": "Opps something went wrong during project transfer. Please try again.",

    "BUSINESS": "Business",
    "LIGHT-USER": "Light",
    "REQUEST_A_DEMO": "REQUEST A DEMO",
    "VIEW_SAMPLE_LINK-RENDERING": "VIEW SAMPLE LINK",

    "UPLOAD_PANORAMA_IMAGES": "Upload Panoramas Images",
    "UPLOAD_TO": "Upload to",
    "CHOOSE_STEREOSCRIPT_FORMAT": "Choose stereoscopic format, e.g 6 x 1 or 12 x 1",
    "UPLOAD_CUBE_MAP": "Upload cube map",
    "CHOOSE_SPHERICAL_FORMAT": "Choose spherical panorama format, normaily taken by 360 camera",
    "UPLOAD_SPHERICAL_MAP": "Upload spherical map",
    "FILE_TYPE_NOT_SUPPORTED": "The file type is not supported",
    "DROP_YOUR_FILE_HERE": "Drop your file here",

    "360_TOUR": "360 Tour",
    "FLOOR_PLAN": "Floor Plan",
    "SELECT_UPLOAD_FILE_TYPE": "Select file type to upload",
    "PANORAMA_IMAGE": "360 Image",
    "FLOORPLAN_IMAGE": "Floor Plan",

    "GET_TOKEN_FOR_PLUGIN": "Get upload token for plugins",
    "FOLDERS": "Folders",
    "IMPORT_COMMENTS_AND_ANIMATION_FROM": "Import comments and animation from",
    "DONE": "Done",

    "ACCOUNT_EXPIRED": "Thank you for using Modelo. It looks like this account has expired.",
    "CONTACT_US": "Contact us",
    "CONTACT_US-LONG": "If you would like to renew access to it, please contact your Modelo Success Specialist, or email hi@modelo.io.",
    "CONTINUE": "Continue",

    "TERMS_AND_CONDITIONS_OF_USE": "Terms and Conditions of Use",
    "TERM_1": "1. Terms",
    "TERM_1_CONTENT": "By accessing the Modelo Inc web site (\"Service\"), you are agreeing to be bound by the following Terms and Conditions of Use, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, do not use or access this site. The materials contained in this web site are protected by applicable copyright and trademark law.",
    "TERM_2": "2. Acceptable Use",
    "TERM_2_CONTENT_1": "You are solely responsible for your conduct and your data related to the Service. You agree to indemnify, defend, and hold harmless Modelo Inc and its suppliers from any and all loss, cost, liability, and expense arising from or related to your data, your use of the Service, or your violation of these terms. The Software and Service are made available to you, your company, and/or your customers only for personal or commercial use, which use must be in compliance with all applicable laws, rules and regulations and must not infringe or violate third party rights. Any unauthorized use of any Modelo Service is a violation of this Agreement and certain federal and state laws. Such violations may subject the unauthorized user and his or her agents to civil and criminal penalties.",
    "TERM_2_CONTENT_2": "Modelo Inc reserves the right to terminate any account at any time that it finds in violation of its Terms and Conditions of Use without refund. You have the right to cancel your account at any time without penalty. In the event of account cancellation you will lose all data related to your account.",
    "TERM_3": "3. Disclaimer",
    "TERM_3_CONTENT": "The materials on Modelo Inc's web site are provided \"as is\". Modelo Inc makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Modelo Inc does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.",
    "TERM_4": "4. Limitations",
    "TERM_4_CONTENT": "In no event shall Modelo Inc or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on Modelo Inc's Internet site, even if Modelo Inc or a Modelo Inc authorized representative has been notified orally or in writing of the  possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.",
    "TERM_5": "5. Revisions and Errata",
    "TERM_5_CONTENT": "The materials appearing on Modelo Inc's web site could include technical, typographical, or photographic errors. Modelo Inc does not warrant that any of the materials on its web site are accurate, complete, or current. Modelo Inc may make changes to the materials contained on its web site at any time without notice. Modelo Inc does not, however, make any commitment to update the materials.",
    "TERM_6": "6. Links",
    "TERM_6_CONTENT": "Modelo Inc has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Modelo Inc of the site. Use of any such linked web site is at the user's own risk.",
    "TERM_7": "7. Site Terms of Use Modifications",
    "TERM_7_CONTENT": "Modelo Inc may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.",
    "TERM_8": "8. Governing Law",
    "TERM_8_CONTENT_1": "Any claim relating to Modelo Inc's web site shall be governed by the laws of the State of Massachusettes without regard to its conflict of law provisions.",
    "TERM_8_CONTENT_2": "General Terms and Conditions applicable to Use of a Web Site.",
    "TERM_9": "9. Intellectual Property",
    "TERM_9_CONTENT": "Modelo Inc claims no intellectual property rights over the material you provide to the Service. You acknowledge that Modelo Inc owns all right, title and interest in and to the Service, including without limitation all intellectual property rights, and such rights are protected by U.S. and international intellectual property laws. You agree that you will not copy, reproduce, alter, modify, or create derivative works from the Service.",
    "PRIVACY_POLICY": "Privacy Policy",
    "PRIVACY_POLICY_CONTENT": "This privacy policy has been compiled to better serve those who are concerned with how their 'Personally identifiable information' (PII) is being used online. PII, as used in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.",
    "PRIVACY_POLICY_1": "1. What personal information do we collect from the people that visit our blog, website or app?",
    "PRIVACY_POLICY_1_CONTENT": "When ordering or registering on our site, as appropriate, you may be asked to enter your name, email address or other details to help you with your experience.",
    "PRIVACY_POLICY_2": "2. When do we collect information?",
    "PRIVACY_POLICY_2_CONTENT_1": "We collect information from you when you register on our site, place an order, subscribe to a newsletter or enter information on our site.",
    "PRIVACY_POLICY_3": "3. How do we use your information?",
    "PRIVACY_POLICY_3_CONTENT_1": "We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:",
    "PRIVACY_POLICY_3_CONTENT_2": "To personalize user's experience and to allow us to deliver the type of content and product offerings in which you are most interested.",
    "PRIVACY_POLICY_3_CONTENT_3": "To improve our website in order to better serve you.",
    "PRIVACY_POLICY_3_CONTENT_4": "To allow us to better service you in responding to your customer service requests.",
    "PRIVACY_POLICY_3_CONTENT_5": "To quickly process your transactions.",
    "PRIVACY_POLICY_3_CONTENT_6": "To send periodic emails regarding your order or other products and services.",
    "PRIVACY_POLICY_4": "4. Do we use 'cookies'?",
    "PRIVACY_POLICY_4_CONTENT_1": "Yes. Cookies are small files that a site or its service provider transfers to your computer'shard drive through your Web browser (if you allow) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information. For instance, we use cookies to help us remember and process the items in your shopping cart. They are also used to help us understand your preferences based on previous or current site activity, which enables us to provide you with improved services. We also use cookies to help us compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.",
    "PRIVACY_POLICY_4_CONTENT_2": "You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser (like Internet Explorer) settings. Each browser is a little different, so look at your browser's Help menu to learn the correct way to modify your cookies.",
    "PRIVACY_POLICY_4_CONTENT_3": "If you disable cookies off, some features will be disabled It won't affect the users experience that make your site experience more efficient and some of our services will not function properly.",
    "PRIVACY_POLICY_5": "5. Third Party Disclosure",
    "PRIVACY_POLICY_5_CONTENT_1": "We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information unless we provide you with advance notice. This does not include website hosting partners and other parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others' rights, property, or safety.",
    "PRIVACY_POLICY_6": "6. Third party links",
    "PRIVACY_POLICY_6_CONTENT": "Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.",
    "PRIVACY_POLICY_7": "7. Does our site allow third party behavioral tracking?",
    "PRIVACY_POLICY_7_CONTENT": "It's also important to note that we allow third party behavioral tracking",
    "PRIVACY_POLICY_8": "8. COPPA (Children Online Privacy Protection Act)",
    "PRIVACY_POLICY_8_CONTENT_1": "When it comes to the collection of personal information from children under 13, the Children's Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, the nation's consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children's privacy and safety online.",
    "PRIVACY_POLICY_8_CONTENT_2": "We do not specifically market to children under 13.",
    "PRIVACY_POLICY_9": "9. Fair Information Practices",
    "PRIVACY_POLICY_9_CONTENT_1": "The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.",
    "PRIVACY_POLICY_9_CONTENT_2": "In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur:",
    "PRIVACY_POLICY_9_CONTENT_3": "We will notify the users via email",
    "PRIVACY_POLICY_9_CONTENT_4": "Within 7 business days",
    "PRIVACY_POLICY_9_CONTENT_5": "We will notify the users via in site notification",
    "PRIVACY_POLICY_9_CONTENT_6": "Within 7 business days",
    "PRIVACY_POLICY_9_CONTENT_7": "We also agree to the individual redress principle, which requires that individuals have a right to pursue legally enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or a government agency to investigate and/or prosecute non-compliance by data processors.",
    "PRIVACY_POLICY_10": "10. CAN SPAM Act",
    "PRIVACY_POLICY_10_CONTENT_1": "The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations.",
    "PRIVACY_POLICY_10_CONTENT_2": "We collect your email address in order to:",
    "PRIVACY_POLICY_10_CONTENT_3": "Market to our mailing list or continue to send emails to our clients after the original transaction has occurred",
    "PRIVACY_POLICY_11": "11. To be in accordance with CANSPAM we agree to the following:",
    "PRIVACY_POLICY_11_CONTENT_1": "NOT use false, or misleading subjects or email addresses",
    "PRIVACY_POLICY_11_CONTENT_2": "Identify the message as an advertisement in some reasonable way",
    "PRIVACY_POLICY_11_CONTENT_3": "Include the physical address of our business or site headquarters",
    "PRIVACY_POLICY_11_CONTENT_4": "Monitor third party email marketing services for compliance, if one is used.",
    "PRIVACY_POLICY_11_CONTENT_5": "Honor opt-out/unsubscribe requests quickly",
    "PRIVACY_POLICY_11_CONTENT_6": "Allow users to unsubscribe by using the link at the bottom of each email",
    "CONTACTING_US": "Contacting Us",
    "CONTACTING_US_CONTENT": "If there are any questions regarding this privacy policy you may contact us using the information below.",
    "MODELO_WEBSITE": "www.modelo.io",
    "ADDRESS_LINE_1": "Modelo, 1 Davis Square",
    "ADDRESS_LINE_2": "Somerville",
    "ADDRESS_LINE_3": "Massachusetts",
    "ADDRESS_LINE_4": "02144",
    "ADDRESS_LINE_5": "United States",
    "EMAIL_ADDRESS": "hi@modelo.io",
    "AGREE": "Agree",

    "FORGOT_PASSWORD": "Forgot Password?",
    "FORGOT_YOUR_PASSWORD": "Forgot your password?",
    "ENTER_EMAIL_ADDRESS": "Enter your email address and we will send you an email to reset your password.",
    "EMAIL_NOT_CORRECT": "Hmm, that email doesn't look correct.",
    "NO_SUCH_EMAIL": "We do not have a user with that email in our database",
    "SUBMIT": "Submit",
    "RESET_PASSWORD_EMAIL_SEND": "We've sent you an email containing a link that will allow you to reset your password for the next 24 hours. Please check your spam folder if the email doesn't appear within a few minutes.",

    "MODELO": "Modelo",
    "COMMUNICATE_YOUR_VISION": "Communicate your vision.",
    "PASSWORD_NOT_MATCH": "This password didn't match your account.",
    "EMAIL_NOT_VALID": "This email doesn't look valid.",
    "EMAIL_CONFIRM": "Are you sure that's your email address?",

    "CREATE_AN_ACCOUNT": "Create a Modelo account and begin making design reviews more productive and presentations more interactive.",
    "MODELO_IS_A_JETPACK": "\"Modelo is a jetpack to supercharge your design process\"",
    "ARCHITECT": "Architect",
    "FIRST_NAME": "First Name",
    "PROVIDE_FIRST_NAME": "Please provide your first name",
    "LAST_NAME": "Last Name",
    "PROVIDE_LAST_NAME": "Please provide your last name",
    "EMAIL": "Email",
    "VERIFICATION_CODE": "Verification Code",
    "GET_VERIFICATION_CODE": "Get Email Verification Code",
    "INVALID_VERIFICATION_CODE": "Invalid Email Verification Code",
    "PROVIDE_A_VALID_VERIFICATION_CODE": "Please provide a email verification code",
    "PROVIDE_A_VALID_EMAIL" : "Please provide a valid email address, e.g.",
    "PLEASE_PROVIDE_YOUR_EMAIL" : "Please provide your email address",
    "EMAIL_EXIST_ALREADY" : "It looks like this email is already associated with another account. Did you mean to",
    "LOG_IN_QUESTION" : "login?",
    "PHONE_NUMBER" : "Phone Number",
    "PHONE_NUMBER_NOT_VALID" : "This doesn't look like a valid phone number. Remember to include area code.",
    "MUST_PROVIDE_A_PHONE_NUMBER" : "You must provide a phone number.",
    "COMPANY_INSTITUTION" : "Company/Institution",
    "PLEASE_PROVIDE_COMPANY" : "Please provide your company or institution.",
    "PASSWORD" : "Password",
    "MUST_PROVIDE_A_PASSWORD" : "You must provide a password",
    "MUST_HAVE_8_CHARACTERS_AT_LEAST" : "Your password needs to be at least 8 characters",
    "CONFIRM_PASSWORD" : "Confirm Password",
    "PASSWORD_MUST_MATCH" : "Your passwords must match",
    "PLEASE_CONFIRM_PASSWORD" : "Please confirm your password",
    "AGREE_TO" : "I agree to the",
    "TERMS_AND_CONDITIONS" : "Terms and Conditions",
    "CREATE_MY_ACCOUNT" : "Create my account",
    "ALREADY_HAVE_AN_ACCOUNT" : "Already have an account?",
    "LOG_IN" : "Log in",

    "MODELO_PASSWORD_RESET" : "Modelo Password Reset",
    "ENTER_A_NEW_PASSWORD" : "Please enter a new password for your account.",
    "MUST_HAVE_8_CHARACTERS_LONG" : "Your password must be at least 8 characters long",
    "URL_NOT_VALID" : "This URL is not longer valid. Please request a new url again.",

    "LOG_OUT" : "LOGOUT",

    "ASSIGNED_TO" : "Assigned to:",

    "ASSET_FAILED_TO_UPLOAD" : "Asset failed to upload.",
    "FOLDER_FAILED_TO_BE_CREATED" : "Folder failed to be created",
    "UNEXPECTED_ERROR_APOLOGY" : "Our apologies. An unexpected error has been occurred when we tried to convert your model. Please do not delete your model and email the model ID  to hi@modelo.io. Our engineering team will resolve the issue and notify you when your model can be viewed in Modelo.",
    "REVIEW_ADDED" : "Your review has been added.",
    "BEEN_ADDED_TO_THIS_PROJECT" : "You have been added to this project.",

    "BUSINESS_ACCOUNT" : "Business Account",
    "YOUR_ROLE" : "Your Role",
    "LIGHT_ACCOUNT" : "Light Account",
    "PERSONAL_ACCOUNT" : "Personal Account",
    "SWITCH_COMPANY" : "Switch Company",
    "ENTERPRISE_ACCOUNTS" : "Enterprise Accounts",
    "LIGHT_ACCOUNTS" : "Light Accounts",
    "PERSONAL_ACCOUNTS" : "Personal Accounts",

    "ASSIGN_TASK" : "Assign task",

    "UPGRADE_ACCOUNT" : "Upgrade account",
    "PROFILE" : "Profile",
    "SETTINGS" : "Settings",
    "PLAN" : "Plan",
    "RELEASE_NOTE": "What’s New",
    "REVIT_EXPORTER" : "Revit Exporter",
    "NAVISWORKS_EXPORTER": "Navisworks Exporter",
    "3DS_MAX_EXPORTER" : "3ds Max Exporter",
    "VECTORWORKS_EXPORTER" : "Vectorworks Exporter",
    "SIGN_OUT" : "Sign Out",

    "SKETCH_DOES_NOT_SUPPORT_LANDSCAPE_THIS_TIME" : "Sketch does not support landscape at this time",

    "BORDER" : "Border",
    "WIDTH" : "Width",
    "TEXT" : "Text",
    "FILL" : "Fill",

    "ADD_WALKTHROUGH_TO_COMMENT" : "Add walkthrough to comment",
    "ERROR_ADDING_NAVIGATION_COMMENT" : "Something went wrong when adding walkthrough to your comment",
    "NAME-USER" : "Name",
    "SAVED_BY" : "Saved By",

    "SETTING" : "Setting",
    "REQUEST_360_RENDERING" : "Request 360 rendering",

    "REPLY" : "Reply",

    "FAILED" : "failed,",
    "RETRY" : "retry",

    "CREATOR" : "Creator",
    "DATES" : "Dates",
    "TYPE" : "Type",
    "CLIENT_READY" : "Client Ready",
    "ON" : "On",

    "RECORD_COMMENT_CARDS" : "Reorder Comment Cards",

    "PREVIOUS" : "previous",
    "NEXT" : "next",

    "UP_DOWN_ARROW_TO_THE_NEXT_COMMENT" : "Up/Down Arrow to the next comment.",
    "LEFT_RIGHT_ARROW_TO_VIEW_ATTACHMENTS" : "Left/Right Arrow to view attachments.",

    "UPLOAD_BACKGROUND_IMAGE" : "Upload Background Image",
    "CHANGE_BACKGROUND_IMAGE" : "Change Background Image",
    "CUSTOM" : "Custom",
    "PRESET": "Preset",
    "PRESET_IMAGES" : "Preset Images",
    "SELECT_A_PHOTO_FROM_COMPUTER" : "Select a photo from your computer",
    "SUPPORTED_JPEG_PNG" : "Supported formats: JPEG, PNG",
    "REMOVE_IMAGE" : "Remove image",

    "MODEL_UPDATING" : "Model Updating",
    "PLEASE_WAIT_MOMENTATILY_WHILE_RECONVERTING" : "Please wait momentarily while we reconvert your model.",
    "ERROR_OCCURRED_WHILE_CONVERTING" : "Error occurred when converting this model",
    "CAN_NOT_VIEW_MODEL" : "Due to error that occurred when converting this model, you will not be able to view this model.",
    "LEAVE_PAGE" : "Leave Page",

    "VISIT_THE_LINK_TO_VIEW_OFFLINE" : "Visit the link and bookmark it to view your model offline",
    "OFFLINE_LINK" : "Offline Link",
    "PLEASE_REFRESH_BROWSER" : "Please refresh browser and try to save again",
    "CLEAR_STORAGE" : "Clear storage",

    "UPGRADE_TO_SHARE_MODEL" : "Upgrade to Share your Model",
    "UPGRADE_TO_VIEW_MODEL_OFFLINE" : "Upgrade to View your Model Offline",
    "WE_SEND_EMAIL_TO_SHARE_MODEL" : "We make sharing your models easy by simply sending a URL. To start sharing your models with ease, please upgrade to Modelo's Light or Business plans.",
    "VIEW_SAMPLE_LINK-MODEL" : "View sample link",
    "STILL_ABLE_TO_VIEW_MODEL_OFFLINE" : "When internet connectivity is slow or you cannot get online, you can still access and view your models when you are offline. Please speak to your Account Manager about upgrading to Modelo Business to access this feature.",

    "EMBED_MODEL" : "Embed Model",
    "DEFAULT" : "Default",
    "CURRENT_VIEW" : "Current View",
    "AUTOSTART" : "Autostart",
    "MAY_EFFECT_LOADING_TIME_WITH_MULTIPLE_MODELS" : "Loads model once the page is ready. May affect loading time with multiple models.",
    "SHOW_VIEW_SWITCH_BUTTON" : "Show view switch button",
    "DISPLAY_BUTTON_TO_SWITCH_VIEWS" : "Display button to switch different views to help viewers better navigate the model.",
    "SHOW_VIEW_HIDE_TOOLS": 'Hide Tools',
    "DISPLAY_BUTTON_TO_HIDE_TOOLS": 'Tools will not show in the menu.',
    "NO_COMMENTS" : "No Comments",
    "NO_PROMPT": "No prompt",
    "KEYBORD_SHORTCUT": 'Keyboard Shortcuts',
    "NEXT_COMMENT": "Next comment",
    "PREV_COMMENT": "Previous comment",
    "ATTACHMENT_FULL_SCREEN": "Attachment fullscreen",
    "NEXT_ATTACHMENT": "Next attachment",
    "PREV_ATTACHMENT": "Previous attachment",
    "QUIT_PRESENTATION_MODE": "Quit presentation mode",

    "SECTION" : "Section",
    "MEASURE" : "Measure",
    "ZOOM_AND_PAN" : "Zoom and Pan",
    "EMBED" : "Embed",
    "UPGRADE" : "Upgrade",
    "OFFLINE_MODEL_LINK" : "Offline model link",
    "ENABLE_BIN" : "ENABLE BIM",

    "BIM_PROPERTIES" : "BIM Properties",
    "TREE" : "TREE",
    "PROPERTIES" : "PROPERTIES",
    "COMBIMDED_PROPERTIES" : "Combined Properties",
    "COMMON_PROPERTIES" : "Common Properties",

    "CONFIRM_VIEW_DIRECTION" : "Confirm view direction",

    "WALKTHROUGHS" : "Walkthroughs",

    "CREATE_A_WALKTHROUGH" : "Create a walkthrough",
    "AUTO_GENERATE_FLOOR_PLAN" : "Walkthrough animations made easy. We automatically generate a floor plan—just drop waypoints and present!",
    "CLICK_ON_ANY_PLANE_TO_BEGIN_WALKTHROUGH" : "To begin your walkthrough, click on any plane to drop your first waypoint.",

    "RENDER_SETTINGS" : "Render Settings",
    "SETTING_NAME" : "SETTING_NAME",
    "DUPLICATE_NAME" : "DUPLICATE_NAME",

    "BACKGROUND" : "Background",
    "OPTION" : "Option",
    "IMAGE" : "Image",
    "CHANGE" : "Change",
    "CHANGE-BG_IMG" : "Change",
    "CHOOSE_IMAGE" : "Choose Image",
    "SUN_LIGHTING": "Sun Lighting",

    "FILTERS" : "Filters",
    "ENHANCED_RENDERING" : "Enhanced Rendering",
    "BASE_RENDERING_MODE" : "Base Rendering Mode",
    "ACCELERATED_RENDERING_MODE" : "Accelerated Rendering Mode",
    "ACCELERATED_RENDERING_MODE_INFO" : "Some special rendering effects will be shut off and some model parts will be hidden during camera manipulation for better performance. ",
    "ARCHITECT_EFFECT" : "Architect Effect",
    "PEN_DETAIL" : "Pen Detail",
    "INK_CONTRAST" : "Ink Contrast",
    "BLACK_WHITE" : "Black & White",
    "SUNLIGHT_LOCATION" : "Sunlight location",
    "BRIGHTNESS" : "Brightness",
    "AUTOEXPOSURE": "Auto-Exposure",
    "SHADOW" : "Shadow",
    "SPECULAR" : "Specular",
    "PROFILE_LINES" : "Profile Lines",
    "FIELD_OF_VIEW" : "Field of View",
    "RESET" : "Reset",
    "DIRECTION": "Direction",
    "ENVIRONMETAL_REFLECTION": "Reflection",

    "SAVE_AS" : "Save As",
    "UPDATE" : "Update",
    "LAYERS" : "Layer",
    "EFFECTS" : "Effect",
    "MATERIALS" : "Material",

    "TOP" : "Top",
    "BOTTOM" : "Bottom",
    "FRONT" : "Front",
    "BACK" : "Back",
    "RIGHT" : "Right",
    "LEFT" : "Left",
    "ISOMETRIC" : "Isometric",
    "GO_BACK": "Back",

    "CLICK_SECTION_TO_MOVE_LEFT_RIGHT" : "Click on a section plane and move it from left to right",
    "PICK_FACE_TO_ADJUST" : "Pick the face of the bounding box you would like to adjust",
    "CHANGE_PASSWORD" : "Change Password",
    "CURRENT_PASSWORD" : "Current Password",
    "NEW_PASSWORD" : "New Password",
    "PASSWORD_NOT_MATCH_CONFIRMATION" : "Your new password does not match your confirmation password.",
    "CURRENT_PASSWORD_DOES_NOT_MATCH_RECORD" : "Your current password does not match our records",
    "MUST_PROVIDE_YOUR_CURRENT_PASSWORD_TO_CHANGE_IT" : "You must provide your current password to change it.",
    "CHANGE_PASSWORD_SUCCESSFULLY" : "Your password has been successfully changed!",

    "PER_MONTH" : "Per month",
    "CURRENT_PLAN" : "Current plan",
    "500MB_STORAGE" : "500MB of storage",
    "UP_TO_200MB_PER_MODEL" : "Up to 200 MB per model upload",
    "UNLIMITED_PROJECTS" : "Unlimited projects",
    "VR_VIEWING" : "VR viewing",
    "3D_COMMENTING" : "3D commenting",
    "WALKTHROUGH_ANIMATION" : "Walkthrough animation",
    "PANORAMA_IMAGE_VIEWING" : "Panorama image viewing",
    "YOUR_CURRENT_PLAN" : "YOUR CURRENT PLAN",
    "3GB_OF_STORAGE_PER_USER" : "3GB of storage per user",
    "UP_TO_750MB_PER_MODEL" : "Up to 750MB per model upload",
    "EMBED_MODELS_WITHOUT_MODELO_LOGO" : "Embed models without Modelo logo",
    "CLIENT_SHARE_LINK" : "Client share link",
    "USER_PERMISSION_CONTROLS" : "User permission controls",
    "COLLABORATE_WITH_TEAM_MEMBERS" : "Collaborate with team members",
    "MANAGE_LICENSES" : "Manage Licenses",
    "AFTER_THE_TRIAL_ENDS_NEW_PRICE_WILL_BE" : "The new monthly charge will be",
    "PLEASE_REMOVE_USERS_BEFORE_REDUCE_LICENSES" : "Please remove users from company before trying to reduce your licenses.",
    "ERROR_UPDATING_YOUR_ACCOUNT" : "There was an error updating your account, Please refresh and try again. If the problem persists please contact hi@modelo.io",
    "UPDATE_LICENSE" : "UPDATE LICENSE",
    "CANCEL_CURRENT_PLAN" : "Cancel current plan",
    "REQUEST_A_DEMO-L" : "Request a demo",
    "STORAGE_BASED_PRICING" : "Storage based pricing",
    "UNLIMITED_FILE_UPLOAD_SIZE" : "Unlimited file upload size",
    "UNLIMITED_VR_VIEWING" : "Unlimited VR viewing",
    "UNLIMITED_3D_COMMENTING" : "Unlimited 3D commenting",
    "UNLIMITED_WALKTHROUGH_ANIMATION" : "Unlimited walkthrough animation",
    "UNLIMITED_PANORAMA_IMAGE_VIEWING_AND_SHARE" : "Unlimited panorama image viewing and share link",
    "UNLIMITED_EMBED_MODELS_WITHOUT_MODELO_LOGO" : "Unlimited embed models without Modelo logo",
    "VIEW_OFFLINE" : "view offline",
    "DEDICATED_CUSTOMER_SUCCESS_MANAGER" : "Dedicated customer success manager",
    "SUPPORT_RESPONSE_WITHIN" : "Support response within 12 hours",
    "CHINA_LOCAL_SERVER_ACCESS" : "China local server access",
    "COMPANY_NAME" : "Company name",
    "CARD_NUMBER" : "Card Number",
    "EXPIRATION_DATE" : "Expiration Date",
    "SECURITY_CODE" : "Security Code",
    "TRANSFER_ALL_PROJECTS_FROM_PERSONAL_TO_LIGHT_ACCOUNT" : "Transfer all projects from your personal account to your new Light account",
    "BEEN_CHARGED_FIRST_BILL" : "You'll be charged for your first bill today",
    "CARD_NOT_CORRECT" : "The card you supplied is not correct.",
    "BEFORE_CANCELLING" : "Before cancel your current plan, please read the following:",
    "CANCELLING_PLAN_LINE2" : "Your account will be downgraded to free account and if the total storage of projects you own and joined exceed 5GB, you will need to leave/delete some of them to access to your account.",
    "CANCELLING_PLAN_LINE3" : "We will send you an email confirmation of your cancellation.",
    "BACK-RETURN" : "BACK",
    "BACK-RETURN-SIMPLE": "Back",
    "CONFIRM_CANCELLATION" : "CONFIRM CANCELLATION",

    "PAYMENT_METHOD" : "Payment method",
    "CREDIT_CARD_CAN_NOT_BE_PROCESSED" : "Credit Card could not be processed.",
    "INVALID_EXPIRATION_DATE" : "Expiration Date is not valid",
    "WE_USE_STRIPE" : "We use Stripe to handle transactions to ensure all your payments are safe and encrypted.",

    "SUBSCRIBED_TO_AT_LEAST_ONE_PAID_ACCOUNT" : "You are currently subscribed to at least one paid account",
    "PAYMENT" : "Payment",
    "AMOUNT" : "Amount",
    "RESTART_PLAN" : "Restart plan",
    "NO_AMOUNT_DUE_AFTER_CURRENT_PERIOD" : "No amount due after current billing period",

    "COMPANY_LOGO" : "Company Logo",
    "SHOW_LOG_TO_SHARE_LINKS_AND_EMBED_MODELS" : "Show the logo for your company to share links and embed models",
    "ACCOUNT_BILLING" : "Account & Billing",
    "STORAGE" : "Storage",
    "MEMBERS" : "Members",

    "COMPANY_PROJECTS" : "Company Projects",
    "CREATED_BY" : "Created By",
    "JOIN" : "Join",

    "EMAIL_NOTIFICATION" : "Email Notifications",
    "YOUR_CHANGES_HAVE_BEEN_SAVED" : "Your changes have been saved",
    "SELECT_ALL" : "Select all",
    "DESELECT_ALL" : "Un-select all",
    "SOMEONE_LEAVES_A_COMMENT_SCREEN_CAPTURE_SKETCH" : "Someone leaves a comment, screen capture or sketch",
    "SOMEONE_ASSIGNS_ME_A_TASK" : "Someone assigns me a task",
    "SOMEONE_UPLOADS_A_MODEL" : "Someone uploads a model",

    "PERSONAL_INFO" : "Personal Info",
    "EDIT_NAME" : "Edit Name",
    "DONT_HAVE_PROJECTS_CREATE_PROJECT_TO_ALTER_EMAIL_SETTINGS": "You don't have any projects yet.  Please create a project to alter your email settings.",

    "PERSONAL-ACCOUNT": "Personal",
    "LIGHT-ACCOUNT": "Light",
    "BUSINESS-ACCOUNT": "Business",
    "DAYS_UNTIL_DEADLINE": "Days Until Deadline",
    "DAYS_LATE": "Days Late",

    "USERS_ALREADY_IN_COMPANY": "User {{ emails }} is already in your company",
    "FAILED_TO_INVITE_USERS_TO_COMPANY": "There was an issue inviting {{emailString}} to this company.",
    "INVITE_TEAM_MEMBERS_TO_PROJECT": "Invite team member to project",
    "ADD_COMPANY_MEMBERS_TO_THIS_PROJECT": "Add company members to this project",
    "INVITEES_FULL_ACCESS_WARNING_HEADER": "Some invitee wil not have full access of this project",
    "INVITEES_FULL_ACCESS_WARNING_MESSAGE": "is not a member of your company account, the person will be added to the project as View-only, where only limited access in this project will be granted.  If you would like to give the user full access of the project, please contact the admin of your company to add this user to your company.",

    "ERROR_INVITING_FOLLOWING_USERS": "Error inviting following users: {{ users }}",

    "CHANGE_IMAGE_TYPE": "Change { type } image",
    "ARE_YOU_SURE_YOU_WOULD_LIKE_TO_DELETE": "Are you sure you would like to delete {{firstName}} {{ lastName }}",
    "ERROR": "Error",
    "LEARN_MORE": "Learn more",

    "YOU_CAN_SET": "You can set <b>Can edit</b> to enable certain features to people in the project.",
    "YOU_CAN_SHARE": "You can set <b>Can share</b> to enable certain features to people in the project.",


    "IMAGES_OF_MODELS": "Images of {type, select,  project{models} other{model} }",
    "SAVE_AS_TYPE_IMAGE": "Save as {type,select, MODEL{model} other{project}} image",

    "DELETE-OBJECTS": " Delete {{ object }}",
    "ARE_YOU_SURE_YOU_WOULD_LIKE_TO_DELETE-ITEMS": "Are you sure you would like to delete {isPlural, select,  true{these} other{this}} {itemName}?",

    "CATION_THIS_CANNOT_BE_UNDONE_CHECK_BOX_TO_CONFIRM": "Caution: This cannot be undone. Check {isFolder, select,  true{boxes} other{box} } to confirm.",
    "ALL_DESIGN_REVIEWS_MODEL_WILL_BE_DELETED": "All design reviews in this folder will be deleted",
    "ALL_DESIGN_REVIEWS_WILL_BE_DELETED": "All design reviews {isPlural, select, true{in this folder} other{for this model}} will be deleted",

    "ARE_YOU_CERTAIN_YOU_WANT_TO_DELETE_PROJECT_X": "Are you absolutely certain you want to delete the project <span>{{ projectName }}</span>?",
    "THIS_WILL_PERMANENTLY_DELETE_THE_PROJECT_X": "This will permanently delete the project { projectName } along with <span>all</span> of it's models, comments and sketches.",

    "SEND_SELECTED_REVIEW_TO": "Send {numberOfReviews, plural,  =1{}  other{ # }} selected {numberOfReviews, plural,  =1{review}  other{reviews}} to:",
    "ADD_A_NEW_FILE": "Add a new file",

    "X_STORAGE_PER_USER": "{{ storage }} of storage <b>per user</b>",

    "CONGRATULATIONS_ON_UPGRADING_TO_LIGHT": "Congratulations on making the upgrade to Light. Your free account {transferAll, select, true{<span>and all its content</span>} other {} } can still be accessed by clicking on the tab labeled",
    "PERSONAL_AND_THEN_SELECTING_FROM_THE_DROP_DOWN": "<b>Personal</b> and then selecting from the dropdown <b>{{ fullName}} Account.</b>",
    "X_ACCOUNTS_NAME": "<b>{{ fullName }}'s Account</b>.",

    "SELECT_COMPANY_TO_TRANSFER_YOUR_PROJECT_TO": "Select a company to transfer your <span >\"{{ projectName }}\"</span> to. After transfer, the selected company will be the sole owner of this project.",
    "INVITE_TEAM_MEMBERS_TO_PROJECTS": "Invite <b>team members</b> to projects",
    "INVITE_UNLIMITED_VIEW_ONLY_MEMBERS_TO_PROJECTS": "Invite unlimited <b >view-only seats</b> to projects",
    "ADD_ANOTHER_COMPANY": "Add another company",
    "CHOOSE_STEREOSCOPIC_FORMAT": "Choose stereoscopic format, e.g 6 x 1 or 12 x 1",
    "CHOOSE_SPHERICAL_PANO_FORMAT": "Choose spherical panorama format, normaily taken by 360 camera",

    "THE_X_PAGE_REQUIRE_BEING_LOGGED_OUT": "The {{page}} page requires being logged out. Click continue below to log out and proceed to that page.",

    "IF_AT_ANY_TIME_YOU_WOULD_LIKE_TO_UNSUB": " If at any time you would like to unsubscribe from receiving future emails, you can email us at<a href='mailto:hi@modelo.io'>hi@modelo.io</a> or follow the instructions at the bottom of each email and we will promptly remove you from ALL correspondence.",
    "WE_CANT_FIND_YOUR_EMAIL": "We can't find an account with this email address.Do you want to <a  class='login-form__top-error-link' href='/register'>create a new account?</span>",

    "NO_ACCOUNT": "Don't have an account?",
    "SIGN_UP": "Sign up",

    "CREATE_AN_ACCOUNT_TO_JOIN_X": "Create an account to join this {type, select, company{company} other{project}}",
    "CREATE_A_FREE_ACCOUNT": "Get started with a free account",
    "CREATE_AN_ACCOUNT-SHORT": "Create an account",

    "ONLY_10_LICENSES_ARE_ALLOWED_UNDER_THE_LIGHT_PLAN": "Only 10 Licenses are allowed under the Light plan. Please email<span class='change-plan-dialog__company-enterprise--email'>sales@modelo.io</span>to upgrade to Modelo's Business plan.",

    "CANCEL_WILL_BE_EFFECTIVE_AT_THE_END_OF_THIS_BILLING_PERIOD": "Cancellation will be effective at the end of your current billing period<b>{date, date, short}</b>",

    "EDIT_COMPANY_NAME": "Edit Company name",
    "CHANGE_PLAN": "Change plan",
    "NEXT_PAYMENT_DUE": "Next payment due:",
    "LIGHT_PLAN_ENDS_ON": "Your Light Plan ends on {d0, date, short}",
    "PLAN_EXPIRED_ON_X": " Plan expired on",
    "UPDATE_PAYMENT_METHOD": "Update payment method",
    "FREE": "Free",
    "PROJECT_WALL": "Project wall",
    "REVIEW_DISCUSSION": "Review discussion",
    "MESSAGE": "Message",
    "DOWNLOADING_AND_PROCESSING_MODEL": "Downloading and processing model...",
    "DOWNLOADING_TEXTURE_X": " Downloading texture...{{ texture }}",

    "MODEL_LOAD_ERROR-HEADER": "Model loading error",
    "MODEL_LOAD_ERROR-MESSAGE": "Opps something went wrong while loading your model. Don't worry, we sent a notification to our error reporting system. If you continue to experience issues please reach out to our support team and we can look into the issue.",

    "PANORAMA_LOAD_ERROR-HEADER": "Your panorama could not be loaded",
    "PANORAMA_LOAD_ERROR-MESSAGE": "Due to some technical difficulties this panorama could not be loaded.",

    "SAVE_360_TOUR_CHANGES-HEADER": "Save Changes",
    "SAVE_360_TOUR_CHANGES-MESSAGE": "Do you want to keep your changes to the 360 tour?",

    "PANORAMA_LINKED-HEADER": "Panorama Linked",
    "PANORAMA_LINKED-MESSAGE": "This 360 panorama image has already been linked to a floor plan.",

    "PDF_DOWNLOAD_ERROR-HEADER": "Downloading Error",
    "PDF_DOWNLOAD_ERROR-MESSAGE": "Oops something went wrong! Please try again later.",

    "UPDATE_ENTERPRISE_PAYMENT_METHOD-HEADER": "Contact us to update payment",
    "UPDATE_ENTERPRISE_PAYMENT_METHOD-MESSAGE": "Please reach out to our sales representatives at sales@modelo.io to update your payment method.",

    "PROVIDE_PDF_PASSWORD-HEADER": "PDF is encrypted please",
    "PROVIDE_PDF_PASSWORD-MESSAGE": "please provide the password",

    "EXIT_FULL_SCREEN": "Exit full screen",
    "FULL_SCREEN": "Full screen",

    "FIRST_PERSON_VIEW_(SHIFT_+_V)": "First person view (Shift + V)",
    "ORBIT_VIEW_(SHIFT_+_V)": "Orbit view (Shift + V)",
    "WALKTHROUGH": "Walkthrough",
    "SCREEN_CAPTURE": "Screen capture",
    "COMMENTS": "Comments",
    "SKETCH": "Sketch",
    "TOOLS": "Tools",
    "BIM": "BIM",

    "HD": "HD",
    "ADD_NOTE": "Add note",
    "EDIT_NOTE": "Edit note",
    "HIGH_RES": "High Res.",

    "EMAIL_ALL_SCREENSHOTS": "Email all Screenshots",
    "DOWNLOAD_ALL_SCREENSHOTS": "Download all Screenshots",

    "MANAGE_WALKTHROUGHS": "Manage walkthroughs...",

    "CREATE_WALKTHROUGH": "Create walkthrough",
    "START_ANIMATION": "Start animation",

    "ADD_WAYPOINT": "Add waypoint",
    "REMOVE_WAYPOINT": "Remove waypoint",
    "CHANGE_ELEVATION": "Change elevation",
    "GO_TO_LAST_LEVEL": "Go to last level",
    "GO_TO_NEXT_LEVEL": "Go to next level",

    "ELEVATION" : "Elevation",
    "SPEED" : "Speed",
    "SPEED_SLOWEST": "Slowest",
    "SPEED_SLOWER": "Slower",
    "SPEED_NORMAL": "Normal",
    "SPEED_FASTER": "Faster",
    "SPEED_FASTEST": "Fastest",
    "PAUSE": "Pause",

    "UPLOAD_ASSETS": "Upload Assets",
    "CREATE_NEW_FOLDER": "Create New Folder",
    "FOLDER_WITH_SAME_NAME_ALREADY_EXISTS": "Folder with same name already exists, please choose new name.",
    "CANNOT_NAME_FOLDER_ROOT": "We're sorry, you cannot name your folder \"root\".",

    "USING_REVIT": "Using Revit",
    "GET_THE_EXPORTER_PLUGIN": "DOWNLOAD REVIT PLUGIN",
    "GRAPHIC DISPLAY OPTION": "Graphic Display Option",
    "SHADING": "Shading",
    "REALISTIC": "Realistic",
    "REDUCE_TEXTURE_FILES_FOR_FASTER_RENDERING": "Reduce texture file size for faster rendering",
    "IMPORT_COMMENTS_AND_WALKTHROUGHS_FROM": "Import comments and walkthroughs from",
    "EMAIL_DOWNLOAD_LINK_TO_PEOPLE_ONCE_MODEL_HAS_BEEN_CONVERTED": "Email download link to people once model has been converted",
    "GET_UPLOAD_TOKEN": "UPLOAD REVIT MODEL",

    "SELECT_MODEL_FROM_YOUR_COMPUTER": "Select model from your computer",
    "WERE_SORRY_THIS_FILE_IS_NOT_SUPPORTED": "We're sorry, this file type is not supported.",
    "LOOKS_LIKE_THIS_IS_A_REVIT_FILE_PLEASE_USE_OUR_REVIT_EXPORTER_PLUGIN": "Looks like this is a Revit file, please use our Revit Exporter Plugin to upload this model.",
    "DROP_YOUR_FILES_HERE": "Drop your file here",
    "X_MODELS": "{ models } {models, plural,  =1{model}  other{ models }}",

    "SHARE_ASSET_FOLDER": "Share Asset Folder",
    "SHARE_ASSET": "Share Asset",

    "EASILY_SEND_LINKS_TO_COLLEAGUES_AND_CLIENTS": "Easily send links to colleagues and clients.",
    "THIS_FOLDER_WILL_NOT_SHOW_ANY_INDICATORS": "This folder will not show any indicators.",

    "SEND_FILE_DOWNLOAD_LINK_TO": "Send file download link to",
    "SHARE_PDF_LINK_TO": "Share PDF link to",
    "ADD_MESSAGE_OPTIONAL": "Add message (optional)",
    "LINK_TO_FILE": "Link to file",
    "COPY": "Copy",
    "COPIED": "Copied",

    "X_ITEMS": "{ items } {items, plural,  =1{item}  other{ items }}",

    "DATE_UPLOADED": "Date Uploaded",
    "NEW_ASSET_NAME": "New Asset Name",
    "RENAME_ASSET": "Rename Asset",

    "X_FILES_UPLOADING": "{ files } {files, plural,  =1{ File }  other{ Files }} Uploading",

    "SELECT_USERS_FROM_YOUR_COMPANY": "Select users from your company",
    "ENTER_EMAIL_ADDRESSES": "Enter email addresses",

    "UNSELECT_ALL": "Un-select all",
    "VIEW_UPDATES": "View Updates",
    "VIEW_MODEL_PREPARATION_TIPS": "View Model Preparation Tips",
    "UPLOADED_BY": "Uploaded by",
    "ADD_A_DESCRIPTION": "Add a description",

    "DELETE_MODEL": "Delete Model",

    "EDIT_NAME_NOTE": "Edit name/note",
    "RE_UPLOAD_MODEL": "Re-upload model",
    "MODEL_UPLOADED_FROM_PLUGIN": "Model Uploaded Through Plugin, Cannot Download",
    "DOWNLOAD_MODEL": "Download Model",


    "NO_BIM_ELEMENTS_OR_PROPS_IN_MODEL-HEADER": "No BIM elements or properties were found in your model",
    "NO_BIM_ELEMENTS_OR_PROPS_IN_MODEL-MESSAGE": "BIM elements and properties are automatically imported when you upload a Revit model that contains this type of information. Please ensure you have installed Modelo’s most recent plugin for Revit and try uploading your model again. If you continue to experience issues, please reach out to us at hi@modelo.io",

    "CHANGE_NUMBER": "Change Number",
    "ADD_NUMBER": "Add Number",

    "UNHIDE": "Unhide",
    "HIDE": "Hide",
    "RENDER_WAITING": "Waiting...",
    "BRANDING_IS_CURRENT_HIDDEN_ON_SHARE_LINS_AND_EMBED_MODELS": "Branding is currently hidden on share links and embed models",
    "OPPS_SOMETHING_WENT_WRONG_WHEN_UPLOADING_BRANDING": " Opps something went wrong when updating branding. Please try again later.",

    "UPLOAD_COMPANY_LOGO": "Upload company logo",
    "OPPS_SOMETHING_WENT_WRONG_WHEN_UPDATING_BRANDING": "Opps something went wrong when updating branding. Please try again later.",

    "SET_AS_COMPANY_LOGO": "Set as company logo",
    "CHANGE_IMAGE": "Change Image",

    "NO_PAYMENT_METHOD_ON_FILE": "No payment method on file",

    "X_FILE_SPACED_USED": "{{spaceUsed}} {{spaceUsedByPct}}% of {{ totalSpace }} used",
    "X_FILE_SPACED_USED_OF_UNLIMITED": "{{ totalSpaceUsed }} of <b>Unlimited Space</b> used",

    "X_SPACE_MODEL_FILES": "Model files ({{ spaceUsed }})",
    "X_SPACE_ASSET_FILES": "Asset files ({{ spaceUsed }})",

    "ATTACHMENTS": "Attachments",

    "HDRI_1": "HDRI 1",
    "HDRI_2": "HDRI 2",
    "HDRI_3": "HDRI 3",
    "HDRI_4": "HDRI 4",

    "CLEAR_SKY_1": "Clear Sky 1",
    "CLEAR_SKY_2": "Clear Sky 2",
    "CLOUDY_SKY_1": "Cloudy Sky 1",
    "CLOUDY_SKY_2": "Cloudy Sky 2",
    "DUSK_SKY_1": "Dusk Sky 1",
    "DUSK_SKY_2": "Dusk Sky 2",
    "GREY_BACKGROUND": "Grey Background",
    "NIGHT_SAILING": "Night Sailing",
    "RAINY_SHORE": "Rainy Shore",
    "MORNING_FOG": "Morning Fog",
    "GLACIER_SEA": "Glacier Sea",
    "MIDNIGHT_LA": "Midnight L.A.",
    "SUMMER_SAPPHIRE": "Summer Sapphire",

    "BACKGROUND_IMAGE_TYPE_WALL_PAPER": "Wall Paper",
    "BACKGROUND_IMAGE_TYPE_WALL_PAPER_TILE": "Wall Paper Tile",
    "BACKGROUND_IMAGE_TYPE_SKY_DOME": "Skydome",

    "CSS_FILTER_NORMAL": "Normal",
    "CSS_FILTER_BLUE_PRINT": "Blue print",
    "CSS_FILTER_DARK_SKY": "Dark Sky",
    "CSS_FILTER_VINTAGE_PAPER": "Vintage Paper",
    "CSS_FILTER_GRAYSCALE": "Greyscale",

    "TIME": "Time",
    "DATE": "Date",

    "NAVIGATION_PREFIX": "Walkthrough_",
    "CUTTING_SPEED": "Cutting Speed",
    "HIDE_SECTION_BOX": "Hide section box",
    "ROTATE_SECTION_BOX": "Rotate section box",
    "RESET_SECTION": "Reset section",

    "FEET_SHORTHAND": "ft",
    "INCH_SHORTHAND": "in",
    "CM_SHORTHAND": "cm",
    "METER_SHORTHAND": "m",
    "MM_SHORTHAND": "mm",

    "SLOW": "Slow",
    "FAST": "Fast",

    "END_PRESENTATION": "End Presentation",

    "ADD_A_COMMENT": "Add a comment",
    "ADD_VIEW": "Add a view",
    "PRESENT": "Present",

    "FROM-DATE": "From",
    "TO-DATE": "To",

    "ALL": "All",
    "PLAY": "Play",

    "ADD_WALKTHROUGH": "Add Walkthrough",
    "SCREENSHOT_PREFIX": "Screenshot_",

    "UNDO": "Undo",
    "REDO": "Redo",
    "NEW_SKETCH": "New Sketch",

    "REMOVE": "Remove",
    "DOWNLOAD": "Download",
    "ADD_MESSAGE_TO_THE_EMAIL": "Add Message to the email",
    "ADD_TEXT": "Add Text",
    "ADD_FILE": "Add File",
    "REORDER": "Reorder",
    "3D_PREFIX": "3D_",

    "ASSIGNEE": "Assignee",

    "CREATE_NEW_WALKTHROUGH": "Creating new walkthrough...",
    "WALKTHROUGH...": "Walkthrough...",

    "MANAGE_SETTINGS": "Manage settings",
    "BLANK_NAME": "Blank name",
    "RESTORE": "Restore",

    "OEMBED": "OEMBED",
    "HTML": "HTML",
    "USE_MODELO_TO_SHARE_YOUR_3D_MODELS_THROUGH_YOUR_BLOG": "Use Modelo to share your 3D model through your portfolio or blog.",
    "CLIENT_READY_CARDS": "Client ready cards",
    "SAVE_MODEL_AND_VIEW_OFFLINE_IN_CHROME": "Save model and view offline in Chrome",
    "ONCE_THE_MODEL_IS_DOWNLOADED_WE_WILL_CREATE_A_LINK": "Once the model is downloaded, we will create a link for you to access it without internet.",
    "UNKNOWN_ERROR": "Unknown error",
    "OFFLINE_STORAGE_IN_YOUR_COMPUTER": "Offline Storage in Your Computer",
    "X_SPACE_USED": "{{ usedSpace }} of {{ totalSpace }} used",

    "SET_EXPIRATION": "Set expiration",
    "NO_EXPIRATION": "No expiration",
    "1_DAY": "1 day",
    "7_DAYS": "7 days",
    "30_DAYS": "30 days",

    "FIRST_COMMENT": "First comment",
    "NONE": "None",

    "SEND_A_MESSAGE": "Send a message",
    "DELETE_REVIEW": "Delete Review",
    "SKETCH_ON_REVIEW": "Sketch on Review",
    "GENERATE_PDF": "Generate PDF",
    "DOWNLOADING": "Downloading ...",
    "COPY_THIS_TOKEN_TO_YOUR_PLUGIN_AND_UPLOAD_YOUR_MODEL_FROM_THERE": "Copy this token to your plugin and upload your model from there",
    "ADD_A_MESSAGE": "Add a message",
    "OPTIONS": "Options",
    "FOLDER_NAME": "Folder Name",
    "RE_UPLOAD_PANORAMA": "Re-upload Panorama",
    "EMBED_360_TOUR": "Embed 360 Tour",
    "SELECT": "Select",
    "ADD_HOTSPOT": "Add Hotspot",

    "CLICK_TO_ADD_LINK": "Click to add Link",
    "SELECT_THE_NEXT_360_IMAGE_FROM_BOTTOM_BAR": "Select the next 360 image from bottom bar",
    "CLICK_ANYWHERE_TO_UPDATE_THE_POSITION": "Click anywhere to update the position",
    "SHARE_360_TOUR": "Share 360 Tour",
    "LINK_TO_360_TOUR": "Link to 360 Tour",
    "CHOOSE_THE_ENTERING_VIEW": "Choose the entering view",
    "PICK_WHICH_VIEW_THE_DESTINATION_360_IMAGE_WILL_BE_SHOWING": "Pick which view the destination 360 image will be showing",

    "GO_TO_PANORAMA": "Go to Panorama",
    "EDIT_POSITION": "Edit position",

    "LOADING_X_SCENES": "Loading {scenes} {scenes, plural,  =1{ scene }  other{ scenes }}",




    "ONBOARDING-ROTATE_MODEL-TITLE": "ROTATE",
    "ONBOARDING-ROTATE_MODEL-MESSAGE": "Click and hold <span>left</span> button",

    "ONBOARDING-PAN_MODEL-TITLE": "PAN",
    "ONBOARDING-PAN_MODEL-MESSAGE": "Click and hold <span>right</span> button",

    "ONBOARDING-ZOOM_MODEL-TITLE": "ZOOM",
    "ONBOARDING-ZOOM_MODEL-MESSAGE": "<span>Scroll</span> to zoom in and out",

    "ONBOARDING-PIVOT_POINT_MODEL-TITLE": "POINT",
    "ONBOARDING-PIVOT_POINT_MODEL-MESSAGE": "<span>Double-click left</span> button to zoom-in and set the pivot point of rotation",

    "ONBOARDING-PRECISE_COMMUNICATION-TITLE": "Precise communication",
    "ONBOARDING-PRECISE_COMMUNICATION-MESSAGE": "Add comments to the model to help explain your ideas.",

    "ONBOARDING-CUSTOMIZING_VISUAL_EFFECT-TITLE": "Customizing visual effect",
    "ONBOARDING-CUSTOMIZING_VISUAL_EFFECT-MESSAGE": "Combine 3D comments with material settings and section cuts to present key views and subtle details.",

    "ONBOARDING-2D_ATTACHMENTS-TITLE": "2D attachments",
    "ONBOARDING-2D_ATTACHMENTS-MESSAGE": "Attach plans, photos and other images to comments and quickly switch between 3D and 2D views",

    "ONBOARDING-SHARE_WITH_CONFIDENCE-TITLE": "Share with confidence",
    "ONBOARDING-SHARE_WITH_CONFIDENCE-MESSAGE": "Set comments as 'Client Ready' and only these comments will be displayed when sharing your model.",

    "ONBOARDING-SWIPE_FROM_COMMENT_TO_COMMENT-TITLE": "Swipe from comment to comment",
    "ONBOARDING-SWIPE_FROM_COMMENT_TO_COMMENT-MESSAGE": "",

    "ONBOARDING-SWIPE_COMMENT_TO_VIEW_AND_REPLY-TITLE": "Tap comment to view and reply",
    "ONBOARDING-SWIPE_COMMENT_TO_VIEW_AND_REPLY-MESSAGE": "",


    "ONBOARDING-CREATE_YOUR_FIRST_ANIMATION-TITLE": "Create your first animation",
    "ONBOARDING-CREATE_YOUR_FIRST_ANIMATION-MESSAGE": "Click the <b>PLUS ICON</b> on the left to create a walkthrough animation.",

    "ONBOARDING-CLICK_ON_A_PLANE_TO_GENERATE_FLOOR_PLAN-TITLE": "Click on a plane to generate floor plan",
    "ONBOARDING-CLICK_ON_A_PLANE_TO_GENERATE_FLOOR_PLAN-MESSAGE": "Choose a <b>FLOOR PLANE</b> in the model to generate the floor plan of that level.",

    "ONBOARDING-SELECT_THE_VIEW_DIRECTION-TITLE": "Select the view direction",
    "ONBOARDING-SELECT_THE_VIEW_DIRECTION-MESSAGE": "There are 2 way to set your camera view direction:<ol class=\"onboarding-card__list\"><li><b>Click and hold on your model</b> to rotate you camera</li><li><b>Move your cursor on the floor plan</b> to pick a direction.</li></ol>",

    "ONBOARDING-ADD_WAYPOINTS_ON_FLOORPLAN-TITLE": "Add waypoints on floorplan",
    "ONBOARDING-ADD_WAYPOINTS_ON_FLOORPLAN-MESSAGE": "<b>Click on the floor plan</b> to add more waypoint to form a path for your animation.<div class=\"in-app-nav__onboarding-card__message\"><img class=\"in-app-nav__onboarding-card__message__gif\" src=\"/assets/images/navigation_intro_waypoint.gif\"></div><div class=\"in-app-nav__onboarding-card__gif__caption\">Add waypoint on floorplan and click to confirm view direction.</div>",

    "ONBOARDING-WHEN_FINISHED_PLAY_YOUR_ANIMATION-TITLE": "When finish, play your animation",
    "ONBOARDING-WHEN_FINISHED_PLAY_YOUR_ANIMATION-MESSAGE": "Once you have your path for the animation setted up, press <b>PLAY BUTTON</b> to start viewing your animation.",

    "MOVE_MODELS_BETWEEN_FOLDERS_BY_CLICK_AND_DRAG": "Move models between folders by click and drag.",

    "BIM_INFO": "BIM Info",
    "CURRENTLY_YOU_HAVE_NO_SELECTION_SETS": "Currently you have no selection sets.",
    "HOLD_THE_CTRL_KEY_AND_CLICK_MULTIPLE": "Hold the Ctrl key and click multiple elements to create a selection set.",
    "HOLD_THE_CMD_KEY_AND_CLICK_MULTIPLE": "Hold the Command key and click multiple elements to create a selection set.",

    "SORT_INSTANCES_BY": "Sort instances by",
    "LEVEL_VIEW": "Level view",
    "CATEGORY_VIEW": "Category view",
    "NO_ELEMENTS_IN_THIS_LEVEL": " No elements in this level",
    "SAVE_X_SELECTED_ELEMENTS": "Save {{ elements }} Selected Elements",
    "X_SELECTED_ELEMENTS": "{{ elements }} Selected Elements",

    "COMBINED_PROPERTIES": "Combined Properties",
    "SHOW": "Show",
    "X_MATCHES": " {{ matches }} Matches",

    "PROJECT_BROWSER": "Project Browser",
    "SELECTION_SETS": "Selection sets",
    "AUTORENDERING-HEADER": "360 Tour is ready! ",
    "AUTORENDERING-MESSAGE": "Go and check for now?",

    "START_RENDERING": "START RENDERING",
    // "STOP_RENDERING": "Stop Rendering",
    "STOP_RENDERING": "QUIT",
    "RENDERING_QUEUE": "Add in rendering queue success",
    "RENDERING_SUCCESS": "Rendering success",
    "NOTIFICATION-RENDERING_CONTINUE": "Continue",
    "VIEWS-MODEL": "Views",

    "ONLY_HDRI": "Only HDRI",
    "SHARPNESS_HD": "1080P",
    "SHARPNESS_SD": "720P",
    "DOWNLOAD_IMAGE": "Download Image",

    "NOTIFICATION-RENDERING_REQUEST_FAILURE": "Render request failed",
    "NOTIFICATION-FOLDER_CREATE_FAILURE": "Failed to create folder",
    "NOTIFICATION-MODEL_READY": "Your model is now ready",
    "NOTIFICATION-CONVERSION_ERROR": "There was an error when converting your model",
    "NOTIFICATION-COMMENT_SETTING_UPDATED": "Comment setting updated",
    "NOTIFICATION-REVIEW_ADDED": "A Review was added",
    "NOTIFICATION-REVIEW_ADDED-EVENT_TX": "View",

    "NOTIFICATION-ADDED_TO_PROJECT": "There was an error when converting your model",
    "NOTIFICATION-EFFECTS_SAVED": "Setting saved",
    "NOTIFICATION-EFFECTS_DELETED": "Setting deleted",

    "NOTIFICATION-FLIPYZ_ASK": "Model in the wrong direction?",
    "NOTIFICATION-FLIPYZ_ASK-EVENT_TXT": "Flip It",
    "NOTIFICATION-RENDERING_QUEUE": "Successfully added to the queue!",
    "NOTIFICATION-RENDERING_SUCCESS": "Rendering success!",
    "NOTIFICATION-RENDERING_VIEW": "View",
    "RENDERING_VIEW": "Auto 360 Tour(beta)",
    "RENDERING_VIEW_EMPTY": "Oops… you haven’t created any 3D Comment yet.",
    "RENDERING_VIEW_EMPTY_NEW": "CREATE NOW",
    "RENDERING_VIEW_COMPLETED": "Completed…",
    "RENDERING_VIEW_TIME": ", estimated time remaining",
    "NOTIFICATION-SETTINGS_NAME_TAKEN": "Name Taken",
    "NOTIFICATION-EMAIL_SENT": "Email sent.",

    "NOTIFICATION-EMAILS_SENT": "Emails sent.",
    "NOTIFICATION-SETTINGS_FAILED": "Setting failed to save.",
    "NOTIFICATION-ASSET_UPLOAD_FAILED": "Asset failed to upload.",
    "NOTIFICATION-IS_OFFLINE": "You are offline",
    "NOTIFICATION-NO_SKETCH_IN_BIM": "Architect effect is not supported in BIM mode",

    "CREATE_FOLDER_FAILED": "Create folder failed",
    "DELETE_FOLDER_FAILED": "Delete folder failed",
    "RENAME_FOLDER_FAILED": "Rename folder failed",
    "UPDATE_PROJECT_DETAILS_FAILED": "Update project details failed",
    "DELETE_MODEL_FAILED": "Delete model failed",
    "UPDATE_MODEL_DETAILS_FAILED": "Update model details failed",
    "UPDATE_MODEL_THUMBNAIL_FAILED": "Update model thumbnail failed",
    "USER_EXCEEDED_STORAGE_LIMIT": "Unfortunately you have exceeded your storage limit. Until you upgrade or delete items you will no longer be able to save or upload files.",


    "SAVE_SELECTION_SET_FAILED": "Save selection set failed",
    "UPDATE_SELECTION_SET_FAILED": "Update selection set failed",
    "RENAME_SELECTION_SET_FAILED": "Rename selection set failed",
    "REORDER_FAILED": "Reorder Failed",
    "DELETE_SELECTION_SET_FAILED": "Delete selection set failed",

    "INVITE_PEOPLE_TO_YOUR_PROJECT_START_COLLABORATING": "Invite people to your project, start collaborating.",


    "UPGRADE_DIALOG-EXCEEDED_STORAGE_LIMIT-HEADER": "You have exceeded your storage limit",
    "UPGRADE_DIALOG-EXCEEDED_STORAGE_LIMIT-MESSAGE": "Hey, it looks like you have reached the storage limit of your account. To continue using Modelo, please add another company, or contact sales@modelo.io",

    "UPGRADE_DIALOG-UPGRADE_TO_SHARE_ASSETS-HEADER": "Please upgrade to share assets",
    "UPGRADE_DIALOG-UPGRADE_TO_SHARE_ASSETS-MESSAGE": "Sharing assets and panoramas is as easy as sending a URL or notifying a colleague in Modelo's Business plan. Learn how this plan can meet all of your Design Asset Management and sharing needs.",


    "UPGRADE_DIALOG-PLEASE_UPGRADE_TO_ADD_LOGO-HEADER": "Please upgrade to add a logo",
    "UPGRADE_DIALOG-PLEASE_UPGRADE_TO_ADD_LOGO-MESSAGE": "To customize your presentation with your own branding, please upgrade to Modelo's Light or Business plans.",


    "UPGRADE_DIALOG-UPGRADE_FOR_360_TOUR-HEADER": "Upgrade for 360 Tour",
    "UPGRADE_DIALOG-UPGRADE_FOR_360_TOUR-MESSAGE": "Create immersive and exciting 360 tours of panoramic images to showcase your designs. Inquire about Modelo's Business plan to get started.",


    "UPGRADE_DIALOG-UPGRADE_TO_ADD_COLLABORATOR_SEATS-HEADER": "Upgrade to Add Collaborator Seats",
    "UPGRADE_DIALOG-UPGRADE_TO_ADD_COLLABORATOR_SEATS-MESSAGE": "Modelo's Light plan is designed to support your presentation needs. To collaborate, it is recommended you use Modelo’s Business plan which offers a centralized platform for managing all of your communication, design markups, and files. Contact your Account Manager to upgrade to a Business Account and begin using Modelo’s Design Asset Management (DAM) solution.",

    "UPGRADE_DIALOG-UPGRADE_TO_SAVE_YOUR_SKETCH-HEADER": "Upgrade to save your Sketch",
    "UPGRADE_DIALOG-UPGRADE_TO_SAVE_YOUR_SKETCH-MESSAGE": "Great job marking up your PDFs and other files! To save them, please upgrade to Modelo's Business plan.",

    "UPGRADE_DIALOG-SWITCH_TO_ON_OF_YOUR_PAID_COMPANIES-HEADER": "Change or remove watermarks with a Modelo Light or Business",
    "UPGRADE_DIALOG-SWITCH_TO_ON_OF_YOUR_PAID_COMPANIES-MESSAGE": "Switching to one of your paid companies or adding a new company allows you to insert a watermark of your brand, a project's name, or remove the watermark entirely.",

    "UPGRADE_DIALOG-ABLE_TO_INSERT_A_WATERMARK_OF_YOUR_BRAND-HEADER": "Change or remove watermarks with a Modelo Light or Business",
    "UPGRADE_DIALOG-ABLE_TO_INSERT_A_WATERMARK_OF_YOUR_BRAND-MESSAGE": "When you upgrade to Modelo's Light or Business plans, you will be able to insert a watermark of your brand, a project's name, or remove the watermark entirely.",

    "UPGRADE_DIALOG-CONTINUE_CREATING_WALKTHROUGHS-HEADER": "Continue creating walkthroughs",
    "UPGRADE_DIALOG-CONTINUE_CREATING_WALKTHROUGHS-MESSAGE": "It's great to see you're making the most out of Modelo. Free Accounts are limited to creating one walkthrough. To continue adding a new walkthrough of your design, please upgrade to a Modelo Light or Business plan.",

    "UPGRADE_DIALOG-SHARE_ASSET_FOLDER-HEADER": "Upgrade Your Account",
    "UPGRADE_DIALOG-SHARE_ASSET_FOLDER-MESSAGE": "Share folder is included in Light and Business plan. It is the easiest way to share a series of panorama images with your clients or colleagues.",

    "UPGRADE_DIALOG-UPGRADE_TO_GET_MORE_SPACE-HEADER": "Upgrade to get more space",
    "UPGRADE_DIALOG-UPGRADE_TO_GET_MORE_SPACE-MESSAGE": "Looks like the files you're trying to upload would put you over your storage limit.  Upgrade today to share your assets with your team.",

    "UPGRADE_DIALOG-UPGRADE_TO_VIEW_MORE_SCENE_WITH_COMPANIES-HEADER": "Upgrade to View More Scenes/Views",
    "UPGRADE_DIALOG-UPGRADE_TO_VIEW_MORE_SCENE_WITH_COMPANIES-MESSAGE": "Modelo is a powerful tool for exploring your designs. Free users are limited to viewing 3 imported scenes. Switching to one of your paid company accounts or adding a new company allows you to import, view, markup, and comment on an unlimited number of scenes.",

    "UPGRADE_DIALOG-UPGRADE_TO_VIEW_MORE_SCENE-HEADER": "Upgrade to View More Scenes/Views",
    "UPGRADE_DIALOG-UPGRADE_TO_VIEW_MORE_SCENE-MESSAGE": "Modelo is a powerful tool for exploring your designs. Free users are limited to viewing 3 imported scenes. When you upgrade to a Modelo Light or Business plan, you are able to import, view, markup, and comment on an unlimited number of scenes.",

    "UPGRADE_DIALOG-UPGRADE_TO_START_PRESENTING_PDFS-HEADER": "Upgrade to start presenting PDFs",
    "UPGRADE_DIALOG-UPGRADE_TO_START_PRESENTING_PDFS-MESSAGE": "Presentations are our specialty.  Upgrade to a Business plan to get access to our PDF presentation feature.",

    "UPGRADE_DIALOG-UPGRADE_TO_INVITE_OTHER_TO_YOUR_PROJECTS_WITH_COMPANIES-HEADER": "Upgrade to invite others to your projects",
    "UPGRADE_DIALOG-UPGRADE_TO_INVITE_OTHER_TO_YOUR_PROJECTS_WITH_COMPANIES-MESSAGE": "It's great that you see the value in adding others to your projects. To prepare and host presentations please switch to one of your paid companies or add another company. To collaborate with your team, markup designs, and access all of Modelo’s Digital Asset Management (DAM) and presentation features, learn how Modelo’s Business plan can meet your needs.",

    "UPGRADE_DIALOG-UPGRADE_TO_INVITE_OTHER_TO_YOUR_PROJECTS-HEADER": "Upgrade to invite others to your projects",
    "UPGRADE_DIALOG-UPGRADE_TO_INVITE_OTHER_TO_YOUR_PROJECTS-MESSAGE": "It's great that you see the value in adding others to your projects. To prepare and host presentations please upgrade to Modelo’s Light plan. To collaborate with your team, markup designs, and access all of Modelo’s Digital Asset Management (DAM) and presentation features, learn how Modelo’s Business plan can meet your needs.",

    "UPGRADE_DIALOG-UPGRADE_TO_CHANGE_YOUR_BACKGROUND_IMAGE-HEADER": "Upgrade to Change Your Background Image",
    "UPGRADE_DIALOG-UPGRADE_TO_CHANGE_YOUR_BACKGROUND_IMAGE-MESSAGE": "Our free accounts use a default background. To customize the background to include your logo or any other image, please upgrade to Modelo's Light or Business plans.",

    "UPGRADE_DIALOG-UPGRADE_FOR_HD_SCREENSHOTS-HEADER": "Upgrade Your Account",
    "UPGRADE_DIALOG-UPGRADE_FOR_HD_SCREENSHOTS-MESSAGE": "High Resolution Screenshots are included in Light and Business plan. It is a powerful way to collaboration with others. Get the highest quality for your project by upgrading your account today.",

    "UPGRADE_DIALOG-UPGRADE_TO_ADD_EXTRA_COMMENTS-HEADER": "Upgrade to Add Extra Comments",
    "UPGRADE_DIALOG-UPGRADE_TO_ADD_EXTRA_COMMENTS-MESSAGE": "Modelo is a powerful tool for exploring your designs. Free users are limited to viewing 3 imported scenes. When you upgrade to a Modelo Light or Business plan, you are able to import, view, markup, and comment on an unlimited number of scenes.",


    "OVER_RENDERINGS-HEADER": "Upgrade to Render more panoramas",
    "OVER_RENDERINGS-MESSAGE": "Free users can only render 3 panoramas, upgrade your account to get more functions",

    "UPGRADE_DIALOG-UPGRADE_TO_SET_EXPIRATION-HEADER": "Ungrade to set expiration date.",
    "UPGRADE_DIALOG-UPGRADE_TO_SET_EXPIRATION-MESSAGE": "",

    "UPGRADE_DIALOG-UPGRADE_TO_GENERATE_APP-HEADER": "Upgrade to view offline.",
    "UPGRADE_DIALOG-UPGRADE_TO_GENERATE_APP-MESSAGE": "Modelo empowers you to wrap up your entire multi-media presentation into an executable file(.exe). Upgrade to access this feature.",

    "FULL_SCREEN-DOWNGRADING": "Downgrading",

    "FULL_SCREEN-OPPS_THE_URL_IS_INVALID": "Oops! This url is invalid.",
    "FULL_SCREEN-YOU_ARE_NOT_CURRENTLY_A_MEMBER_OF_THIS_PROJECT": "You are not currently a member of this project. Please contact the project owner to grant you access.",
    "FULL_SCREEN-THIS_PROJECT_FOLDER_OR_MODEL_DOES_NOT_EXIST_IN_OUR_DB": "This project, folder or model does not exist in our database.It may have been deleted.",
    "FULL_SCREEN-WE_COULDNT_FIND_YOUR_PAGE": "Our apologies, we couldn't find the page you were looking for. Please try refreshing the page. If you continue having issues, please send us a note at hi@modelo.io and we'll see what we can do to help!",

    "FULL_SCREEN-MODEL_FAILED_TO_LOAD": "Failed to load model! Mostly like resources depleted. Close other unused tabs and refresh this one.",
    "FULL_SCREEN-WE_JUST_CLEANED_UP_A_COUPLE_THINGS_PLEASE_REFRESH": " We just cleaned up a couple things with your model.Please click ok to refresh the page and reload the updated model.",
    "FULL_SCREEN-THE_OWNER_OF_THIS_MODEL_HAS_EXPIRED": "The owner of this model has an expired account, please contact him/her to view.",
    "FULL_SCREEN-RESOURCE_DEPLETED": "Resource depleted! Please close some unused tabs and click chrome webgl reload button to reload this page.",
    "FULL_SCREEN-REFRESH_THIS_PAGE": "Refresh this page? Please click the fresh button yourself!",
    "FULL_SCREEN-ACCOUNT_EXPIRED": "Your account has been expired. Please renew to access this page. If you have any question, please contact us at hi@modelo.io",


    "ALL-SEARCH": "All",
    "MODELS-SEARCH": "Models",
    "ASSETS-SEARCH": "Assets",
    "360_TOUR-SEARCH": "360 Tour",

    "WALKTHROUGH_SPEED_PLACEHOLDER": "e.g 3",
    "SAVING...": "Saving...",
    "PRESENT_COMMENTS": "PRESENT COMMENTS",
    "RESOLVE": "Resolve",
    "RESOLVED": "Resolved",
    "UNRESOLVED": "UnResolved",

    "CREATED_A_3D_COMMENT": "Created a 3D Comment",
    "CREATED_A_SKETCH": "Created a Sketch",
    "CREATED_A_SCREENSHOT": "Created a Screenshot",
    "CREATED_A_REVIEW": "Created a review",


    "TRANSITION_SPEED_HEADER": "Comments transition speed",
    "ILLUSTRATED_BT_FEIFEI_FEND": "Illustration by Feifei Feng",
    "SIGN_UP_FOR_FREE": "Sign up for Free",

    "MODELO_IS_THE_EASIEST_WAY_TO_BRING_YOUR_3D_MODEL_INTO_THE_WEB_AND_SHARE_WITH_OTHERS": "Modelo is the easiest way to bring your 3D model into web and sharing with others.",

    "YOUR_FILE_WILL_BEGIN_DOWNLOADING_SHORTLY": "Your file will begin downloading shortly",
    "OPPS_LOOKS_LIKE_SOMETHING_WENT_WRONG": "Oops! Looks like something went wrong.",
    "OPPS_LOOKS_LIKE_THIS_FILE_HAS_BEEN_DELETED": "Oops! Looks like this file has been deleted.",

    "VIEW_BROWSER_BY": "View browser by",
    "VIEW_BY": "View by",

    "EXIT": "Exit",

    "REUPLOAD_A_NEW_MODEL_TO_REPLACE_THE_OLD_MODEL": " Reupload a new model to replace the old model, your model URL, settings and design reviews will be preserved with the new upload.",
    "OPPS_SOMETHING_WENT_WRONG_WE_LOGGED_THIS_ERROR_AND_OUR_DEVELOPERS_WILL_TAKE_A_LOOK": " Opps something went wrong. We logged this error and our developers will take a look.",

    "UPLOADING...": "Uploading",
    "YOUR_ENTERPRISE_PLAN_EXPIRED_EMAIL_SALES_TO_CONTINUE_USING_YOUR_ACCOUNT": "Your enterprise plan expired has expired. Email <a href='mailto:sales@modelo.io'>sales@modelo.io</a> to continue using your account.",


    "YOUR_CURRENT_PAYMENT_METHOD_FAILED_PLEASE": "Your current payment method failed, please",
    "UPDATE_PAYMENT_DETAILS": "Update payment detail",
    "OR": "or",
    "DOWNGRADE_YOUR_PLAN": "Downgrade Your Plan",
    "TO_ACCESS_YOUR_PROJECT": "to access your projects.",

    "YOUR_PLAN_WILL_EXPIRE_IN_X_DAYS": "Your plan will expire in {willExpireIn, plural, =1{tomorrow}  other{ # days}}.",
    "EMBED_ASSET": "Embed Asset",

    "THIS_ACTION_CANNOT_BE_UNDONE": "This action <span>cannot</span> be undone.",

    "REUPLOAD_MODEL_FROM_PLUGIN": "Reupload model from plugin",


    "UT_LENGTH_FEET": "\"",
    "UT_AREA_FEET_2": "SF",
    "UT_VOLUME_FEET_3": "CF",

    "UT_LENGTH_METER": "m",
    "UT_AREA_METER_2": "SM",
    "UT_VOLUME_METER_3": "CM",

    "UT_MASS_KG": "kg",
    "ADD_ANNOTATION": "Add Annotation",

    "CHANGE_LANGUAGE": "Change Language",
    "CHOOSE_LANGUAGE": "Choose Language",
    "ENGLISH": "English",
    "CHINESE": "Chinese",

    "VIEW_SETTINGS_PREFIX": "View Settings  ",

    "EN": "en",
    "ZH": "中文(zh)",

    "SELECTED_ELEMENTS": "Selected elements",
    "CURVES": "Curves",

    "MODEL_CONVERTING_TEXT_EMAIL": "You can leave this page and we'll email you when your model is ready to view.",
    "MODEL_CONVERTING_TEXT_NO_EMAIL": "You can leave this page and return to view your model here.",

    "CAN_ONLY_VIEW_FILES_IN_PROJECT": "You can only view files in this project.",
    "CLIENT_SIDEBAR_BODY_TEXT": "Your view-only permissions allow you to view designs and reply comments. If you would like to collaborate in a larger capacity, please contact the project owner to be added as a team member.",

    "FLIP_PANORAMA_DIALOG-HEADER": "Flip Panorama",
    "FLIP_PANORAMA_DIALOG-MESSAGE": "Do you like to flip this panorama image?",
    "FLIP": "Flip",
    "FLIP_PANORAMA": "Flip Panorama",

    "AS_TEAMMEMBER": "As Teammember",
    "AS_CLIENT": "As View-only",

    "TEST_WEBGL_SUPPORT": "Test your WebGL support",
    "GO_TO_PROJECTS_PAGE": "Go to projects page",
    "SUPPORTED_BROWSERS_TEXT": "Our current supported browsers are Mobile Safari (non-desktop), Mozilla Firefox, Microsoft Edge and Google Chrome.",
    "UNSUPPORTED_WEBGL_TEXT": "Your browser does not support WebGL and it's extensions required by our 3D rendering engine.",
    "DOWNLOAD_CHROME": "Download Chrome",
    "COPY_SHARE_LINK": "Copy Share Link",


    "BIM_DATA_INSIGHT_TOOL": "Bim Data Insight Tool",
    "CLICK_TO_ADD_ANNOTATION": "Click to add annotation",

    "SHARE_LINK": "Share Link",

    "TITLE": "Title",
    "HEIGHT": "Height",
    "MEDIA": "Media",

    "HOW_TO_EARN_MORE": "How to earn more",
    "WHAT_IS_DESIGN_TOKEN": "What is Design Token",
    "MODELO_DESIGN_TOKEN_IS_THE_FIRST_DIGITAL_REWARDING_FUND": "Modelo Design Token is the first digital rewarding fund from the collaboration between Modelo and Cingularity. Modelo Design Token can be used to purchase Modelo service, or exchange to Cingularity Token.",
    "VISIT_CINGULARITY_NETWORK": "Visit cingularity.network",
    "YOUR_DESIGN_TOKEN_IS_CALCULATED_USING_THE_FOLLOWING_FORMULA": "Your design token is calculated using the following formula:",
    "DESIGN_TOKEN_UPLOAD_MODEL_PLUS_ETC_X_0_DOT_25": " Design Token = (Model Data in megabytes + Review data in megabytes) X 0.1",
    "DESIGN_TOKEN": "Design token",

    "GENERATE_APP": "Generate App",

  "GENERATE_APP" : "Generate App",
  "GENERATE_PANO_APP" : "Generate App",


    "GENERATE_MODEL_VIEWER_APP": "Generating Model Viewer App",
    "DO_YOU_WANT_TO_GENERATE_AN_APP_FOR_OFFLINE_USAGE_CURRENTLY_USERS_ARE_ONLY_ABLE_GEN_EVERY_6_HOURS": "Modelo empowers you to wrap up your entire multi-media presentation into an executable file(.exe). For every six hours, you can generate an application out of a model.",
    "GENERATE": "Generate",
    "USERS_CAN_ONLY_GENERATE_ONE_MODEL_EVERY_X_HOURS": `Users can only generate one model every {{ genTime }} hours, you need to wait until {{ nextDownloadTime }} until you can generate a new app. If you need more, please contact us at sales@modelo.io`,
    "THE_MODEL_VIEWER_APP_WILL_AUTO_START_DOWNLOADING_ONCE_IT_HAS_BEEN_GENERATED": "The Model Viewer App will automatically start downloading once it has been generated.  Please do not refresh this page.",
    "THE_MODEL_VIEWER_APP_WAS_GENERATED_SUCCESSFULLY": "The Model Viewer App was generated successfully, it should have already started downloading to your machine. If it failed to download please click the button below.",
    "THERE_WAS_AN_ERROR_GENERATING_YOUR_MODEL_VIEWER_APP_PLEASE_TRY_AGAIN_LATER": "There was an error generating your Model Viewer App. Please try again later or if the problem persists contact us at hi@modelo.io",

  "GENERATE_MODEL_VIEWER_APP" : "Generating Model Viewer App",
  "GENERATE_PANO_VIEWER_APP" : "Generating Panorama Viewer App",
  "DO_YOU_WANT_TO_GENERATE_AN_APP_FOR_OFFLINE_USAGE_CURRENTLY_USERS_ARE_ONLY_ABLE_GEN_EVERY_6_HOURS": "Modelo empowers you to wrap up your entire multi-media presentation into an executable file(.exe). For every six hours, you can generate an application out of a model.",
  "DO_YOU_WANT_TO_GENERATE_AN_PANO_APP_FOR_OFFLINE_USAGE_CURRENTLY_USERS_ARE_ONLY_ABLE_GEN_EVERY_6_HOURS": "Modelo empowers you to wrap up your entire panorama presentation into an executable file(.exe). For every six hours, you can generate an application out of a model.",
  "GENERATE" : "Generate",
  "USERS_CAN_ONLY_GENERATE_ONE_MODEL_EVERY_X_HOURS" : `Users can only generate one model every {{ genTime }} hours, you need to wait until {{ nextDownloadTime }} until you can generate a new app. If you need more, please contact us at sales@modelo.io`,
  "USERS_CAN_ONLY_GENERATE_ONE_PANO_EVERY_X_HOURS" : `Users can only generate one panorama app every {{ genTime }} hours, you need to wait until {{ nextDownloadTime }} until you can generate a new app. If you need more, please contact us at sales@modelo.io`,
  "THE_MODEL_VIEWER_APP_WILL_AUTO_START_DOWNLOADING_ONCE_IT_HAS_BEEN_GENERATED" : "The Model Viewer App will automatically start downloading once it has been generated.  Please do not refresh this page.",
  "THE_PANO_VIEWER_APP_WILL_AUTO_START_DOWNLOADING_ONCE_IT_HAS_BEEN_GENERATED": "The Panorama Viewer App will automatically start downloading once it has been generated.  Please do not refresh this page.",
  "THE_MODEL_VIEWER_APP_WAS_GENERATED_SUCCESSFULLY" : "The Model Viewer App was generated successfully, it should have already started downloading to your machine. If it failed to download please click the button below.",
  "THE_PANO_VIEWER_APP_WAS_GENERATED_SUCCESSFULLY" : "The Panorama Viewer App was generated successfully, it should have already started downloading to your machine. If it failed to download please click the button below.",
  "THERE_WAS_AN_ERROR_GENERATING_YOUR_MODEL_VIEWER_APP_PLEASE_TRY_AGAIN_LATER" : "There was an error generating your Model Viewer App. Please try again later or if the problem persists contact us at hi@modelo.io",

    "REQUIRED": "Required",
    "ADD_NOTES": "Add notes...",
    "EDIT_ANNOTATION": "Edit Annotation",


    "TABLEAU_EXTENSION": "Tableau Extension",
    "TABLEAU_EXTENSION_DATA": "Tableau Extension Data",
    "GET_TABLEAU_PLUGIN": "Get Tableau plugin",
    "MODEL_TOKEN": "Model Token",
    "YOU_CAN_IMPORT_THIS_DATA_INTO_TABLEAU_AS_A_DATASOURCE": "You can import this data into tableau as a datasource. When connecting interactions please use the field ElementId",
    "DOWNLOAD_BIM_DATA": "Download bim data",


    "COUPON_CODE": "Coupon Code",
    "THE_COUPON_CODE_YOU_ENTERED_IS_INVALID": "The coupon code you entered is invalid. Please try again.",


    "UPGRADE_TO_CUSTOMIZE_YOUR_BRANDING": "upgrade to customize your branding",
    "NOTICE": "Notice",
    "ALL_MODELS_UPLOADED_FROM_FREE_USERS_WILL_BE_PUBLICLY_SHOW_IN_MODELO_EXPLORE": "All models uploaded from free users accounts will be publicly posted to <a target=\"_blank\" href=\"https://modelo.io/explore\">Modelo Explore</a> after 24 hours. If you want to keep your model private, ",
    "PLEASE_UPGRADE_YOUR_ACCOUNT_HERE": "please <a>upgrade</a> your account here.",
    "PLEASE_ACCEPT_OUR_UPDATED_TERMS_AND_CONDITIONS": "Please accept our updated Terms and Conditions to continue using Modelo",


  "UT_POWER_WATT": "w",
  "UT_VOLTAGE_VOLT" : "V",

  "CLOUDY_LAWNS": "Cloudy Lawns",
  "GREEN_SUBURBAN": "Green Suburban",
  "RURAL_LANDSCAPE": "Rural Landscape",
  "ON_THE_ROAD": "On The Road",
  "GREEN_CAMPUS": "Green Campus",
  "OASIS": "Oasis",
  "BLUE_SKY": "Blue Sky",
  "VENICE_SUNSET": "Venice Sunset",
  "MOUNTAIN_TOP": "Mountain Top",
  "CLIFF_TOP": "Cliff Top",

  "LOADING_KOORENDER": 'Loading KooRender(beta)...',
  "HDRI": "Settings",
  "HDRI-INTENSITY": "Brightness",
  "HDRI-DIRECTION": "Direction",
    "SCENE_SETTING_PARAM": "Setting",
    "SCENE_SETTING_DIRECTION": "Dirtction",
    "SCENE_SETTING_DENSITY": "Density",
    "SCENE_SETTING_POSITION": "Position",
    "SCENE_SETTING_ANGLE": "Angle",
    "SCENE_SETTING_SCALE": "Scale",
    "SCENE_SETTING_PROPORTION": "Proportion",

    "PAGE_IS_EMPTY": "Empty page",
    "UNSELECTED": "Select a part",

    "COMMENTAUTORENDER_DEFAULT": "Default",
    "COMMENTAUTORENDER_QUALITY": "Quality",
    "COMMENTAUTORENDER_STYLE": "Style",
    "COMMENTAUTORENDER_SAVETO": "Save to",
    "COMMENTAUTORENDER_START": "Start 360 Rendering",
    "COMMENTAUTORENDER_RENDERING": "Rendering…",
    "COMMENTAUTORENDER_COMPLETED": "360 Rendering Settings",

    "RENDERSTATUS_WAITING": "Waiting...",
    "RENDERSTATUS_RENDERING": "Rendering...",
    "RENDERSTATUS_COMPLETED": "Completed!",

    "PANORAMA_LOADING": "Loading Panorama",
    "PANORAMA_LOADING_THUMB": "Loading Thumbnail...",
    
    "ERROR_MODEL_TOOOLD": "This model was uploaded quite earlier that koorender needs to reprocess the model, so please re-upload the model for better rendering experience. ",

    "INVITE_TEAM_MEMBERS_EXISTED": "Users {{existedEmails}} is already in project",

    "RELEASE_FEATURE": "Feature",
    "RELEASE_DETAIL": "details",
    "RELEASE_UPDATE": "Update",
    "RELEASE_DESC": "We’re constantly working to improve your DAM experience, here’s a summary of what has changed.",
    "RELEASE_MAJOR": "Major update",
    "RELEASE_MINOR": "Minor update",
    "RELEASE_FIX": "Fixes",
    "RELEASE_MISC": "Misc",
    "RELEASE_VERSION": " v{version} has released!",

    "RELEASE_SMALL_UPDATE": "Updated some detailed features",
    "RELEASE_SMALL_BUG": "Fixed some bugs",
    "RELEASE_SMALL_MAJORIZATION": "Optimized some user experience",
    
    "CHANGEBACKGROUND": "Background changing",

    "INVALID_IMAGE": "Invalid image",
    "CURRENT_IMAGE": "Current Image",

    "SAFE_VERIFICATION": "Safety Verification",
    "CONFIRM": "Confirm",

    "VERITIFY_ERROR": "Verification code error",
    "VERTIFITY_EXPIRED": "Code expired, please refresh",

    "PROJECT_NAME_CONNOT_BE_EMPTY":"Project Name cannot be empty",
    "FAQ_URL": "https://modelo.zendesk.com/hc/en-us",

    "CUSTOMIZED_PRICING_BASED_ON_STORAGE" : "Customized pricing based on storage",
    "UNLIMITED_MODEL_UPLOAD_SIZE" : "Unlimited model upload size",
    "UNLIMITED_OBJECT_QUANTITY" : "Unlimited object quantity",
    "UNLIMITED_SCENES_PER_MODEL_IN_VR" : "Unlimited scenes per model in VR",
    "3D_WALKTHROUGH_UNLIMITED" : "3D walkthrough--unlimited",
    "UNLIMITED_360_PANORAMIC_TOUR" : "Unlimited 360 panoramic tour",
    "UNLIMITED_CREATE_SHARE_LINKS" : "Unlimited create share links",
    "CUSTOM_BRANDS_ON_MODEL" : "Custom brands on model",
    "PERSONALIZED_SETTINGS_CUSTOMIZED_USER_PERMISSION" : "Personalized settings--customized user permission",
    "OFFLINE_MODEL_VIEWING" : "Offline Model viewing",
    "BIM_VIEWER_ACCESS_BIM_PROPERTIES_AND_ELEMENTS" : "BIM Viewer--access BIM properties and elements",
    "ASSET_MARKUPS_MARKUP_AND_SHARE_PDFS_PLANS_AND_IMAGES" : "Asset Markups--markup and share PDFs, plans, and images",
    "SUPPORT_DEDICATED_CUSTOMER_SUCCESS_MANAGER" : "Support--dedicated customer success manager",
    "FREE_MODELO_ON_BOARDING_TRAINING" : "Free Modelo on-boarding training",

    "MODEL_RECONVERTED_SUCCESSFULLY" : "Model reconverted successfully!",
    "PLEASE_RELOAD_THE_PAGE_TO_VIEW_MODEL" : "Please reload the page to view model.",
    "RELOAD" : "Reload",
    "MODEL_PROCESSING" : "Model Processing...",

    "LEARN_MORE_URL" : "https://www.youtube.com/watch?v=YJWx5ZSBqLc",
    "UPLOAD_MODEL_IMPORT_COMPAT_TEXT_HELP_URL" : "https://modelo.zendesk.com/hc/en-us/articles/230625407",
    "UPLOAD_MODEL_HELP" : "https://modelo.zendesk.com/hc/en-us/sections/203387677-Uploading-3D-Model-Files",

    "UPGRADE_TO_CUSTOMIZE_URL" : "https://modelo.io",
    "SHARE_360" : "Share 360",
    "GO_TO_360_TOUR_PANEL": "Go to 360 Tour Panel",
    "LEAVEL_THIS_PAGE_AND_GO_TO_360_TOUR_PANEL" : "Sharing 360 needs to leave this page and go to 360 Tour Panel, shall we go?",
    "HAVENT_GENERATED_360" : "Opps… you haven't generated any 360 yet.",
    "GO_TO_GENERATE" : "GO TO GENERATE",

    "CAN_ONLY_AHARE_NON-IMPORTED_FILES" : "Can only share non-imported files",




};

if (typeof window !== 'undefined') {
    window.EN_TRANSLATIONS = EN_TRANSLATIONS;
}
