const ZH_TRANSLATIONS = {
  "CREATE_PROJECT": "创建项目",
  "CREATE_NEW_PROJECT": "新建项目",
  "PROJECT": "项目",
  "PROJECTS": "所有项目",
  "NEW": "最新",
  "PROJECT_PAGE.NO_PROJECTS": "您还没有任何项目，现在就创建一个吧！",
  "SEARCH_DOTS": "搜索...",
  "SEARCH": "搜索",
  "RECENT": "按时间从近到远排序",
  "NAME_A-Z": "按字母从A到Z排序",
  "NAME_Z-A": "按字母从Z到A排序",
  "CREATED": "创建日期",
  "DEADLINE": "截止日期",
  "CLIENT": "客户",
  "LOCATION": "地区",
  "TAGS": "标签",
  "AUTOROTATE": "自动旋转",
  "MODEL_ROTATE": "模型围绕其中心缓慢旋转。",

  "MISSING_AUXILARY_FILES":"您的模型似乎缺少<mark>mtl</mark>文件…请将obj文件和mtl文件打包为zip文件再尝试上传。",
  "I/O_ERROR":"您的模型似乎缺少<mark>mtl</mark>文件…请将obj文件和mtl文件打包为zip文件再尝试上传。",

  "MODEL_DOES_NOTCONTAIN_A_MESH":"你的模型可能非完全<mark>三角面建模</mark>或者无<mark>几何数据</mark>…",
  "MODEL_NEEDS_TO_BE_TRIANGULATED":"你的模型可能非完全<mark>三角面建模</mark>或者无<mark>几何数据</mark>…",

  "TRANSFER_PROJECT": "转移项目",
  "CHANGE_THUMBNAIL": "更换缩略图",
  "LEAVE_PROJECT": "离开项目",
  "DELETE_PROJECT": "删除项目",
  "CREATE": "创建",
  "CANCEL": "取消",
  "PROJECT_NAME": "项目名称",
  "ALL_MODELS": "所有模型",
  "MODELS": "所有模型",
  "ASSETS": "所有文件",
  "PROJECT_OVERVIEW-MOBILE": "概况",
  "PROJECT_OVERVIEW": "项目概况",
  "TEAM_MEMBERS-MOBILE": "成员",
  "TEAM_MEMBERS": "项目成员",
  "PROJECT_BRIEF": "项目简介",
  "EDIT": "修改",
  "RENDER_EDIT": "编辑",
  "SAVE": "保存",
  "PROJECT_SIZE": "项目大小",
  "TOTAL_MODELS": "模型总数",
  "TOTAL_REVIEWS": "反馈总数",
  "TOTAL_ASSETS": "文件总数",
  "TOTAL_IMAGE_360": "全景漫游总数",
  "NAME-FILE": "文件名",
  "CREATED_ON": "创建日期",
  "ITEMS": "项",
  "UPLOAD_CANCELLED": "取消上传",
  "UPLOAD": "上传",
  "RNDERING": "离线渲染",
  "NEW_FOLDER": "新建文件夹",
  "DEFAULT_SCENE": "默认场景",
  "UPLOAD_KEY": "上传密钥",
  "MATERIAL_SCENE": "材质球",
  "MATERIAL_IMAGE": "纹理图",
  "RENDER_SIZE": "输出尺寸",
  "RENDER_VIEW_STOP-HEADER": "确认停止所有渲染？",
  "RENDER_VIEW_STOP-MESSAGE": "未渲染的全景图将不会被保存。",
  "RENDER_VIEW_INIT-HEADER": "您上传的模型正在为渲染做准备中 …",
  "RENDER_VIEW_INIT-MESSAGE": "可能还需要几分钟时间，请稍后再试。",
  "RENDER_VIEW_ERROR-HEADER": "您上传的模型好像有点高级…",
  "RENDER_VIEW_ERROR-MESSAGE": "发送报告至support@modeloapp.com，我们有专业的人士帮您解决问题。",
  "CURIOUS_ABOUT_RENDERING_SERVICE": "对我们的三维渲染服务是否感兴趣?",
  "RENDER_VIEW_ERROR_REPORT": "发送报告",
  "NOTIFICATION-RENDER_VIEW_ERROR_REPORT_SUCCESS": "模型渲染报告发送成功！",
  "SHARE": "分享",
  "RENAME": "重命名",
  "DELETE": "删除",
  "VIEW": "视图",
  "VIEW-PREVIEW": "预览视图",
  "MARKUP": "标注",
  "VIEW_FOLDER": "访问文件夹",
  "REUPLOADING": "重新上传",
  "CUSTOMIZE_PERMISSIONS": "自定义权限",
  "ADD_COMPANY_MEMBERS": "添加公司成员",
  "UPGRADE_TO_ADD_NEW_MEMBERS": "升级账户以便添加公司成员",
  "ADD_VIEW_ONLY_SEATS": "添加客户",
  "UPGRADE_TO_ADD_NEW_CLIENTS": "升级账户以便添加客户",
  "STATUS": "状态",
  "PENDING": "待处理",
  "INVITE_RESENT": "重发邀请",
  "INVITE_RESEND": "重新邀请",
  "CANCEL_INVITE": "取消邀请",
  "LICENSES": "席位",
  "VIEW_ONLY_LICENSES": "客户席位",
  "UPLOAD_MODEL": "上传模型",
  "ADMIN": "管理员",
  "TEAM_MEMBER": "成员",
  "VIEW_ONLY": "客户",
  "OWNER": "所有者",
  "VIEW_3D": "查看3D",
  "VIEW_MODEL": "查看模型",
  "NO_UPDATES_ON_THIS_MODEL": "这个模型没有任何更新",
  "ANY_FEEDBACK_WILL_APPEAR_HERE": "任何模型相关的更新都会显示在这里",
  "DATE_CREATED": "创建日期",
  "DATE_UPDATED": "更新日期",
  "FILTER": "筛选",
  "SNAPSHOTS": "屏幕快照",
  "3D_COMMENTS": "三维批注",
  "IMPORTED_VIEWS": "导入的视角",
  "SKETCHES": "草图",
  "RENDERINGS": "效果图",
  "SCENE_SETTING_CREATE": "新建素材组",
  "INVITE_USERS_TO_THIS_CCOMPANY": "邀请用户到这个公司",
  "DO_NOT_HAVE_ENOUGH_SEATS_TO_INVITE_ALL_EMAILS": "没有足够的席位去邀请所有人",
  "INVITE_USERS": "邀请用户",
  "ADD_PEOPLE_TO_PROJECT": "添加成员到项目",
  "ADD_PEOPLE_TO_COMPANY": "添加成员到公司",
  "WHO_IS_IN_THIS_PROJECT": "谁在这个项目里",
  "PROJECT_MEMBER": "项目成员",
  "NOTE_LIGHT_ACCOUNT_CAN_ONLY_ADD_COMPANY_MEMBERS_TO_PROJECTS": "提醒：个人帐户只能在项目里添加公司成员",
  "UPGRADE_TO_INVITE_CLIENTS_TO_PROJECT": "升级账户以便邀请客户到这个项目",
  "YES": "是",
  "OK": "好",
  "OK_UPPER": "好",
  "UPLOAD_IMAGE": "上传图片",
  "SELECT_A_PHOTO_FROM_YOUR_COMPUTER": "从您的电脑里选一张图片",
  "NO": "否",
  "INVITE_PEOPLE_TO_PROJECT": "邀请别人到项目",
  "BILLING_CONTROL": "计费控制",
  "AN_UNKNOWN_ERROR_HAS_OCCURED_WHEN_SAVING_PERMISSIONS": "保存权限时发生未知错误",
  "FEATURES": "功能",
  "CAN_SHARE": "可以分享",
  "SHARE_DOWNLOAD_MODELS": "分享，下载模型",
  "SHARE_DOWNLOAD_ASSETS": "分享，下载文件",
  "SHARE_DOWNLOAD_MDOEL_REVIEWS": "分享，下载模型反馈",
  "CAN_EDIT": "可以编辑",
  "UPDATE_AND_DELETE_FOLDERS_IN_PROJECTS": "在项目中更新以及删除文件夹",
  "DELETE_MODELS_AND_MODEL_REVIEWS": "删除模型和模型反馈",
  "DELETE_ASSETS": "删除文件",
  "TOGGLE_CLIENT_READY": "切换至客户可见",
  "ALL_MODELS_IN_THIS_FOLDER_WILL_BE_DELETED": "该文件夹里所有模型都将被删除",
  "ALL_TEAM_MEMBERS": "所有成员",
  "WILL_LOSE_ACCESS_TO_THIS_PROJECT": "将无法访问该项目",
  "PLEASE_TYPE_DELETE_TO_CONFIRM": "请输入DELETE来确认",
  "DOES_NOT_MATCH_DELETE": "与DELETE不匹配",
  "EMAIL_MODEL_REVIEWS": "邮件发送模型反馈",
  "ADD_MESSAGE": "附言",
  "SEND": "发送",
  "SIZE": "大小",
  "PIXELS": "像素",
  "CHOOSE_A_FILE_FROM_YOUR_ASSETS": "从您的所有文件中选一个",
  "ADD_A_FOLDER": "新建文件夹",
  "PLEASE_ADD_A_FOLDER_BEFORE_UPLOADING_A_FILE": "请在上传文件前创建文件夹",
  "CHOOSE": "选择",
  "SAVE_CHANGES": "保存改变",
  "DO_YOU_WANT_TO_SAVE_THE_CURRENT_CHANGES": "您想要保存现在的改变吗",
  "MODEL_FILE_SIZE_EXCEEDS_THE_LIMIT": "模型大小超过限制",
  "YOUR_FREE_ACCOUNT_CAN_VIEW": "您的试用账户只能查看最大50MB的模型。由于这个文件大于50MB，请升级账户后再查看。",
  "OK_GOT_IT": "明白了",
  "ARE_YOU_SURE_TO_LEAVE": "您确定要离开这个项目吗？",
  "LEAVE": "离开",
  "SET_STARTING_VIEW": "设置初始视图",
  "SAVE_AS_STARTING_VIEW": "保存成初始视图",
  "SORRY_ATTACHMENT_UNAVAILABLE": "十分抱歉，此附件不可见，它可能已从文件管理页面中被删掉",
  "NO_PREVIEW_AVAILABLE": "不支持预览",
  "MODEL_CONVERSION_ERROR": "您似乎建了一个十分特殊的模型...我们已经通知柯布西耶先生，一旦修好他就会联系您",
  "OTHER_ERROR": "您似乎建了一个十分特殊的模型...我们已经通知柯布西耶先生，一旦修好他就会联系您",
  "FAILED_TO_FIND_SUCH_FILE_ON_THE_DISK": "您似乎建了一个十分特殊的模型...我们已经通知柯布西耶先生，一旦修好他就会联系您",
  "READING_OR_PARSING_THE_FILE_ERROR": "您似乎建了一个十分特殊的模型...我们已经通知柯布西耶先生，一旦修好他就会联系您",
  "NOT_SUPPORTED_FILE_FORMAT": "您似乎建了一个十分特殊的模型...我们已经通知柯布西耶先生，一旦修好他就会联系您",
  "INPUT_FORMAT_IS_NEWER_THAN_COVNERTER": "您似乎建了一个十分特殊的模型...我们已经通知柯布西耶先生，一旦修好他就会联系您",
  "DEFAULT_ERROR": "您似乎建了一个十分特殊的模型...我们已经通知柯布西耶先生，一旦修好他就会联系您",

  "CLOSE": "关闭",
  "OVER_PLAN_SPACE": "超过账户存储空间",
  "UPGRADE_PLAN": "现在已经超过账户存储空间，您需要升级账户以便使用更多空间",
  "OVER_PLAN_SPACE-HEADER": "超过账户存储空间",
  "OVER_PLAN_SPACE-MESSAGE": "现在已经超过账户存储空间，您需要升级账户以便使用更多空间",
  "HERE": "这里",
  "RENDERING_SERVICE": "渲染服务",
  "RENDERING_SERVICES_MESSAGE": "感谢您询问我们的渲染服务。您的申请已成功发送给您的客户经理，我们将在1个工作日内联系您。",
  "VIEW_SAMPLE_LINK-EXAMPLE": "示例链接",
  "HIGH_QUALITY_RENDERING": "需要更高质量的渲染服务吗？让我们来帮助您",
  "COLLABORATE_WITH_PROMINENT_RENDERING_COMPANIES": "为了给您直接提供三维建筑渲染效果，模袋正与知名的渲染公司合作。",
  "BECOME_A_PARTNER": "成为合作者",
  "INQUIRE_ABOUT_RENDERINGS": "咨询渲染相关",
  "DO_NOT_SHOW_ME_THIS_MESSAGE_AGAIN": "不再显示此消息",
  "FOLLOW_UP_MESSAGE": "太好了！我们已经收到您的请求，并将在24小时之内联系您并为您提供更能信息。",
  "PROBLEMS_GETTING_CONTACT_WITH_SALES": "连接时发生了一些错误。欢迎直接发邮件到sales@modelo.io来获取我们渲染服务的更多信息。",
  "SHARE_MODEL": "分享模型",
  "SHARE_3D_MODEL_PAGE": "分享三维模型页面",
  "SHARE_MODEL_FILE": "分享模型文件",
  "HOLD_DOWN_TO_COPY_LINK": "按住复制链接",
  "START_SCREEN": "初始画面",
  "CHOOSE_INITIAL_SCREEN": "选择模型上传之后的初始画面",
  "SHOW_COMMENT_CARD": "显示模型批注",
  "PEOPLE_CAN_VIEW_COMMENT_CARDS_FROM_THIS_MODEL": "可以看该模型中的批注",
  "SHOW_WALKTHROUGH": "显示漫游",
  "PEOPLE_CAN_VIEW_ANY_WALKTHROUGH_FROM_THIS_MODEL": "可以看该模型中的漫游",
  "HIDE_COMMENT_DETAILS": "隐藏批注详情",
  "COMMENTS_AUTHOR_AND_DATE_WILL_NOT_SHOW": "不显示批注者和创建日期",
  "LIMIT_AREA_TO_VIEW": "用它来限制可以查看的区域",
  "RESTRICTED_VIEW_REQUIRES_COMMENTS": "受限视图需要注释。",
  "PREVIEW": "预览",
  "RESTRICTED_VIEW": "受限视图",
  "RESTRICTED_VIEW_INSTRUCTION": "当开启受限视图，用户只能以第一视角来查看模型",
  "PAN": "平移",
  "ZOOM": "缩放",
  "ROTATE": "旋转",
  "COMMENT": "批注",
  "FIRST_PERSON_VIEW_FROM_COMMENT": "第一称视角批注",
  "OFF": "关闭",
  "WELCOME_NEW_LIGHT_ACCOUNT": "欢迎来到您新的个人账户",
  "TRANSFER_ALL_MODELS": "现在，您已将所有项目转移到个人帐户，您可以享受新帐户的许多优惠，例如：",
  "UP_TO_750M_MODEL_UPLOADS": "最大可以上传750MB模型",
  "EMBED_MODE_LINKS": "嵌入模型连接",
  "CLIENT_SHARE_LINKS": "客户分享链接",
  "COMPANY_USER_PERMISSION_CONTROLS": "公司用户权限控制",
  "ENJOY": "走你！",
  "TRANSFER_TO_ANOTHER_COMPANY": "把项目转移到另一个账户",
  "NO_COMPANY_ACCEPTS_THIS_PROJECT": "目前没有合适的公司可以接受这个项目",
  "TRANSFER_TERMS": "转移条款",
  "NO_TRANSFER_FROM_PAID_TO_FREE_COMPANY": "项目无法从付费账户转移到试用账户。另外，为了使公司获得项目转移的资格，您必须是管理员或是所有者。我们保留随时更改这些条款的权利。",
  "TRANSFER": "转移",
  "TRANSFER_ERROR_MESSAGE": "不好意思，项目转移出错，请再试一次。",
  "BUSINESS": "企业账户",
  "LIGHT-USER": "个人账户",
  "REQUEST_A_DEMO": "申请企业演示",
  "VIEW_SAMPLE_LINK-RENDERING": "访问客户分享链接",
  "UPLOAD_PANORAMA_IMAGES": "上传全景图",
  "RENDER_RENDERING": "效果图",
  "RENDER_PANORAMA": "全景图",
  "UPLOAD_TO": "上传到",
  "CHOOSE_STEREOSCRIPT_FORMAT": "选择立体格式，例如6 x 1或12 x 1",
  "UPLOAD_CUBE_MAP": "上传立方体图",
  "CHOOSE_SPHERICAL_FORMAT": "选择球形全景格式，通常由360摄像机拍摄",
  "MATERIAL_INDOOR": "室内",
  "MATERIAL_OUTDOOR": "室外",
  "MATERIAL_INDOOR_ALL": "室内所有",
  "MATERIAL_COLLECT": "收藏",
  "MATERIAL_COLLECT_ALL": "所有收藏",
  "MATERIAL_OUTDOOR_ALL": "室外所有",
  "UPLOAD_SPHERICAL_MAP": "上传球形图",
  "FILE_TYPE_NOT_SUPPORTED": "不支持该文件类型",
  "DROP_YOUR_FILE_HERE": "把您的文件放到这里",
  "GET_TOKEN_FOR_REVIT_3DS_MAX_OR_VECTORWORKERS": "获取Revit，3ds Max或Vectorworks的上传代码",
  "FOLDERS": "文件夹",
  "IMPORT_COMMENTS_AND_ANIMATION_FROM": "导入批注和动画来自",
  "DONE": "完成",
  "ACCOUNT_EXPIRED": "感谢您使用模袋。该帐户已过期。",
  "CONTACT_US": "与我们联系",
  "CONTACT_US-LONG": "如果您想续订账户，请联系您的模袋客户经理，发送电子邮件至hi@modelo.io或致电+1（617）945-8692。",
  "CONTINUE": "继续",
  "TERMS_AND_CONDITIONS_OF_USE": "使用条款及条件",
  "TERM_1": "1.条款",
  "TERM_1_CONTENT": "通过访问模袋 Inc网站（“服务”），您同意遵守以下使用条款和条件以及所有适用的法律和法规，并同意您有责任遵守所有适用的当地法律。如果您不同意这些条款，请勿使用或访问本网站。本网站中的资料受适用的版权和商标法保护。",
  "TERM_2": "2.可接受的使用",
  "TERM_2_CONTENT_1": "您对您的行为和与服务相关的数据全权负责。您同意对因您的数据，使用本服务或违反这些条款而引起或与之有关的任何及所有损失，成本，责任和开支，向模袋 Inc及其供应商进行赔偿，辩护并使其免受损害。本“软件”和“服务”仅提供给您个人或商业用途，您的公司和/或您的客户，其使用必须符合所有适用的法律，法规和规定，且不得侵犯或侵犯第三方的权利。任何未经授权使用任何模袋服务均违反本协议以及某些联邦和州法律 此类违规行为可能会导致未经授权的用户及其代理人受到民事和刑事处罚。",
  "TERM_2_CONTENT_2": "模袋公司保留在任何时候发现违反其使用条款和条件而不退还任何账户的权利。您有权随时取消您的账户而不受处罚。在帐户取消的情况下，您将失去与您的帐户相关的所有数据。",
  "TERM_3": "3.免责声明",
  "TERM_3_CONTENT": "模袋公司网站上的资料是“按原样”提供的。模袋公司不作任何明示或暗示的担保，并在此否认和否定所有其他担保，包括但不限于暗示的担保或条件的适销性，适用于特定目的，或不侵犯知识产权或其他侵权行为。此外，模袋公司对其网站上的材料的使用准确性，可能的结果或可靠性以及与此类材料或与本网站相关的任何网站有关的其他信息不作任何保证或陈述。",
  "TERM_4": "4.限制",
  "TERM_4_CONTENT": "在任何情况下，模袋公司或其供应商均不承担因使用或无法使用模袋公司互联网上的材料而引起的任何损害（包括但不限于因数据或利润损失或因业务中断而造成的损失）即使模袋公司或模袋公司的授权代表已经口头或书面通知了这种损害的可能性。由于某些司法管辖区不允许对隐含担保进行限制，或对后果性或附带性损害承担责任限制，因此这些限制可能不适用于您。",
  "TERM_5": "5.修订和勘误",
  "TERM_5_CONTENT": "出现在模袋公司网站上的材料可能包括技术，印刷或摄影错误。 模袋公司不保证其网站上的任何材料准确，完整或最新。 模袋公司可随时更改其网站上的资料，恕不另行通知。但是，模袋公司并不承诺更新材料。",
  "TERM_6": "6.链接",
  "TERM_6_CONTENT": "模袋公司尚未审查与其互联网网站链接的所有网站，也不对任何此类链接网站的内容负责。 包含任何链接并不意味着模袋公司对该网站的认可。使用任何此类链接的网站由用户自担风险。",
  "TERM_7": "7.网站使用条款修改",
  "TERM_7_CONTENT": "模袋公司可随时修改其网站的使用条款，恕不另行通知。使用本网站即表示您同意遵守当下版本的使用条款和条件。",
  "TERM_8": "8.管辖法律",
  "TERM_8_CONTENT_1": "任何与模袋 Inc网站有关的索赔均应受到州法律的管辖，而不考虑其与法律条款的冲突。",
  "TERM_8_CONTENT_2": "适用于使用网站的一般条款和条件。",
  "TERM_9": "9.知识产权",
  "TERM_9_CONTENT": "模袋 Inc对您提供给本服务的材料不提供任何知识产权。您承认模袋 Inc拥有本服务的所有权利，所有权和利益，包括但不限于所有知识产权，并且这些权利受美国和国际知识产权法保护。您同意不会拷贝，复制，修改，变更或创建衍生作品。",
  "PRIVACY_POLICY": "隐私政策",
  "PRIVACY_POLICY_CONTENT": "本隐私政策的编制是为了更好地服务那些关心他们的“个人身份信息”（PII）如何在线使用的人。美国隐私法和信息安全中使用的个人身份信息是可以单独使用或与其他信息一起使用的信息，以识别，联系或查找单个人，或在上下文中识别个人。 请仔细阅读我们的隐私政策，以便清楚了解我们如何根据我们的网站收集，使用，保护或以其他方式处理您的个人身份信息。",
  "PRIVACY_POLICY_1": "1.我们从访问我们的博客，网站或应用程序的人员中收集哪些个人信息？",
  "PRIVACY_POLICY_1_CONTENT": "在我们的网站上订购或注册时，可能会要求您输入您的姓名，电子邮件地址或其他详细信息以帮助您获得体验。",
  "PRIVACY_POLICY_2": "2.我们什么时候收集信息？",
  "PRIVACY_POLICY_2_CONTENT_1": "当您在我们的网站上注册时，下订单，订阅电子报或在我们的网站上输入信息时，我们会收集您的信息。",
  "PRIVACY_POLICY_3": "3.我们如何使用您的信息？",
  "PRIVACY_POLICY_3_CONTENT_1": "当您注册，订购，订阅电子报，回复调查或营销传播，浏览网站或使用其他网站功能时，我们可能会使用我们从您那里收集的信息：",
  "PRIVACY_POLICY_3_CONTENT_2": "个性化用户体验，并允许我们提供您最感兴趣的内容和产品类型。",
  "PRIVACY_POLICY_3_CONTENT_3": "改进我们的网站，以便更好地为您服务。",
  "PRIVACY_POLICY_3_CONTENT_4": "让我们更好地为您服务，回应您的客户服务请求。",
  "PRIVACY_POLICY_3_CONTENT_5": "可以快速处理您的交易",
  "PRIVACY_POLICY_3_CONTENT_6": "定期发送和订购账户有关以及其他产品和服务的电子邮件",
  "PRIVACY_POLICY_4": "4.我们使用Cookies吗？",
  "PRIVACY_POLICY_4_CONTENT_1": "是的。 Cookies是网站或其服务提供商通过您的网页浏览器（如果允许）将您的计算机的分段驱动器传输到网站或服务提供商的系统，以识别您的浏览器并捕获和记忆某些信息的小文件。例如，我们使用Cookies来帮助我们记住和处理购物车中的商品。他们也被用来帮助我们基于以前或当前的网站活动来了解您的偏好，这使我们能够为您提供改进的服务。我们还使用Cookies来编译有关网站流量和网站互动的汇总数据，以便我们可以在未来提供更好的网站体验和工具。",
  "PRIVACY_POLICY_4_CONTENT_2": "每次发送Cookie时，您都可以选择让您的计算机发出警告，或者您可以选择关闭所有的Cookie。您可以通过浏览器（如Internet Explorer）进行设置。每个浏览器都有些不同，所以请查看浏览器的“帮助”菜单，了解修改Cookie的正确方法",
  "PRIVACY_POLICY_4_CONTENT_3": "如果您禁用了Cookie，则某些功能将被禁用。这不会影响使您更加高效的网站体验，也不会遇到无法正常运行的用户体验。",
  "PRIVACY_POLICY_5": "5.第三方披露",
  "PRIVACY_POLICY_5_CONTENT_1": "除非我们提前通知您，否则我们不会将您的个人识别信息出售，交易或以其他方式转让给外界。这不包括协助我们运营的网站，开展业务或为您服务的网站托管合作伙伴和其他各方，只要这些合作伙伴同意将这些信息保密。当我们认为发布符合遵守法律，执行我们的网站政策或保护我们或他人的权利，财产或安全时，我们也可能会公布您的信息。",
  "PRIVACY_POLICY_6": "6.第三方链接",
  "PRIVACY_POLICY_6_CONTENT": "偶尔，我们可以自行决定在我们的网站上包含或提供第三方产品或服务。这些第三方网站有分离和独立的隐私政策。 因此，我们对这些网站链接的内容和活动不负任何责任。 尽管如此，我们力求保护我们网站的完整性，并欢迎对这些网站的反馈。",
  "PRIVACY_POLICY_7": "7.我们的网站是否允许第三方行为追踪？",
  "PRIVACY_POLICY_7_CONTENT": "注意，我们允许第三方行为追踪",
  "PRIVACY_POLICY_8": "8. COPPA（儿童在线隐私保护法）",
  "PRIVACY_POLICY_8_CONTENT_1": "当收集到13岁以下儿童的个人信息时，“儿童在线隐私保护法案”（Child's Online Privacy Protection Act，COPPA）将家长置于可以控制中。美国消费者保护机构联邦贸易委员会执行COPPA规则，该规定阐明了网站和在线服务运营商必须做什么来保护在线儿童的隐私和安全。",
  "PRIVACY_POLICY_8_CONTENT_2": "我们不专门向13岁以下的儿童推销。",
  "PRIVACY_POLICY_9": "9.公平信息做法",
  "PRIVACY_POLICY_9_CONTENT_1": "公平信息实践原则构成了美国隐私法的中坚力量，其中包含的概念在全球数据保护法的发展中发挥了重要作用。了解公平信息实践原则以及如何实施这些原则对于遵守保护个人信息的各种隐私法是至关重要的。",
  "PRIVACY_POLICY_9_CONTENT_2": "为了与公平信息实践保持一致，如果发生数据泄露，我们将采取以下响应措施：",
  "PRIVACY_POLICY_9_CONTENT_3": "我们将通过电子邮件通知用户",
  "PRIVACY_POLICY_9_CONTENT_4": "7个工作日内",
  "PRIVACY_POLICY_9_CONTENT_5": "我们将通过网站通知用户",
  "PRIVACY_POLICY_9_CONTENT_6": "7个工作日内",
  "PRIVACY_POLICY_9_CONTENT_7": "我们也同意个人的补救原则，这个原则要求个人有权追究不遵守法律的数据收集者和处理者在法律上可执行的权利。这一原则不仅要求个人对数据使用者具有强制执行的权利，而且要求个人诉诸法院或政府机构调查和/或起诉数据处理者的违规行为。",
  "PRIVACY_POLICY_10": "10.垃圾邮件法案",
  "PRIVACY_POLICY_10_CONTENT_1": "CAN-SPAM法是一项规定商业电子邮件规则的法律，规定了商业信息的要求，给予收件人停止发送电子邮件的权利，并规定了对违规行为的严厉处罚。",
  "PRIVACY_POLICY_10_CONTENT_2": "我们收集您的电子邮件地址，以便：",
  "PRIVACY_POLICY_10_CONTENT_3": "在我们的邮件列表中销售或者在原始交易发生之后继续发送电子邮件给我们的客户",
  "PRIVACY_POLICY_11": "11.按照CANSPAM，我们同意以下条款：",
  "PRIVACY_POLICY_11_CONTENT_1": "不要使用虚假或误导的主题或电子邮件地址",
  "PRIVACY_POLICY_11_CONTENT_2": "以合理的方式将消息识别为广告",
  "PRIVACY_POLICY_11_CONTENT_3": "包括我们的业务或现场总部的实际地址",
  "PRIVACY_POLICY_11_CONTENT_4": "监控第三方电子邮件营销服务是否符合规定（如果使用的话）。",
  "PRIVACY_POLICY_11_CONTENT_5": "快速选择退出/取消订阅请求",
  "PRIVACY_POLICY_11_CONTENT_6": "允许用户通过使用每封电子邮件底部的链接取消订阅",
  "CONTACTING_US": "联系我们",
  "CONTACTING_US_CONTENT": "如果您对本隐私政策有任何疑问，请使用以下信息与我们联系。",
  "MODELO_WEBSITE": "www.modelo.io",
  "ADDRESS_LINE_1": "模袋, 1 Davis Square",
  "ADDRESS_LINE_2": "Somerville",
  "ADDRESS_LINE_3": "Massachusetts",
  "ADDRESS_LINE_4": "02144",
  "ADDRESS_LINE_5": "United States",
  "EMAIL_ADDRESS": "hi@modelo.io",
  "AGREE": "同意",
  "FORGOT_PASSWORD": "忘记密码？",
  "FORGOT_YOUR_PASSWORD": "忘记密码?",
  "ENTER_EMAIL_ADDRESS": "请输入您的电子邮箱地址，我们将给您发送一封电子邮件来重置您的密码。",
  "EMAIL_NOT_CORRECT": "您的电子邮箱地址不正确",
  "NO_SUCH_EMAIL": "我们的数据库中没有该电子邮箱地址",
  "SUBMIT": "提交",
  "RESET_PASSWORD_EMAIL_SEND": "我们给您发送了一封电子邮件，其中包含一个可让您在接下来的24小时内重置密码的链接。如果电子邮件没有在几分钟内出现，请检查您的垃圾邮件文件夹。",
  "MODELO": "模袋云",
  "COMMUNICATE_YOUR_VISION": "设计愿景始于沟通",
  "PASSWORD_NOT_MATCH": "此密码与您的帐户不匹配。",
  "EMAIL_NOT_VALID": "这不是个有效的邮箱地址。",
  "EMAIL_CONFIRM": "确定这是您的电子邮箱地址吗？",
  "CREATE_AN_ACCOUNT": "创建一个模袋帐户，使设计反馈更具创造力，演示更具互动性。",
  "MODELO_IS_A_JETPACK": "模袋可以极致优化您的设计流程",
  "ARCHITECT": "建筑师",
  "FIRST_NAME": "名字",
  "PROVIDE_FIRST_NAME": "请提供您的名字",
  "LAST_NAME": "姓",
  "PROVIDE_LAST_NAME": "请提供您的姓",
  "EMAIL": "邮箱",
  "VERIFICATION_CODE": "验证码",
  "GET_VERIFICATION_CODE": "获取邮箱验证码",
  "INVALID_VERIFICATION_CODE": "邮箱验证码错误",
  "PROVIDE_A_VALID_VERIFICATION_CODE": "请填写邮箱验证码",
  "PROVIDE_A_VALID_EMAIL": "请提供有效的电子邮箱地址，例如",
  "PLEASE_PROVIDE_YOUR_EMAIL": "请提供您的电子邮箱地址",
  "EMAIL_EXIST_ALREADY": "看起来这个电子邮箱已经被注册了。您希望",
  "LOG_IN_QUESTION": "登陆？",
  "PHONE_NUMBER": "电话号码",
  "PHONE_NUMBER_NOT_VALID": "这可能不是一个有效的电话号码。请加上区号。",
  "MUST_PROVIDE_A_PHONE_NUMBER": "您必须提供一个电话号码。",
  "COMPANY_INSTITUTION": "公司/机构",
  "PLEASE_PROVIDE_COMPANY": "请提供您的公司/机构名称",
  "PASSWORD": "密码",
  "MUST_PROVIDE_A_PASSWORD": "您必须输入一个密码",
  "MUST_HAVE_8_CHARACTERS_AT_LEAST": "您的密码必须至少8位",
  "CONFIRM_PASSWORD": "确认密码",
  "PASSWORD_MUST_MATCH": "必须匹配您输入的密码",
  "PLEASE_CONFIRM_PASSWORD": "请确认您的密码",
  "AGREE_TO": "我同意",
  "TERMS_AND_CONDITIONS": "条款和条件",
  "CREATE_MY_ACCOUNT": "创建我的账户",
  "ALREADY_HAVE_AN_ACCOUNT": "已经有账户？",
  "LOG_IN": "登陆",
  "MODELO_PASSWORD_RESET": "模袋密码重置",
  "ENTER_A_NEW_PASSWORD": "请为您的账户输入一个新密码。",
  "MUST_HAVE_8_CHARACTERS_LONG": "您的密码必须至少8位",
  "URL_NOT_VALID": "这个网址已失效。请再次申请一个新网址。",
  "LOG_OUT": "退出",
  "ASSIGNED_TO": "指定给：",
  "ASSET_FAILED_TO_UPLOAD": "文件上传失败。",
  "FOLDER_FAILED_TO_BE_CREATED": "文件夹创建失败",
  "UNEXPECTED_ERROR_APOLOGY": "很抱歉，我们尝试转换您的模型时发生错误。 请不要删除模型，并将模型ID  发至邮箱hi@modelo.io。我们的工程师将帮您解决问题，并将在上传转换成功之后通知您。",
  "REVIEW_ADDED": "您的反馈添加成功",
  "BEEN_ADDED_TO_THIS_PROJECT": "您已经被加入到此项目。",
  "BUSINESS_ACCOUNT": "企业账户",
  "YOUR_ROLE": "您的角色",
  "LIGHT_ACCOUNT": "个人帐户",
  "PERSONAL_ACCOUNT": "试用账户",
  "SWITCH_COMPANY": "切换账户",
  "ENTERPRISE_ACCOUNTS": "企业账户",
  "LIGHT_ACCOUNTS": "个人帐户",
  "PERSONAL_ACCOUNTS": "试用账户",
  "ASSIGN_TASK": "分配任务",
  "UPGRADE_ACCOUNT": "升级账户",
  "PROFILE": "账户",
  "SETTINGS": "设置",
  "PLAN": "套餐",
  "RELEASE_NOTE": "版本更新",
  "REVIT_EXPORTER": "Revit导出插件",
  "3DS_MAX_EXPORTER": "3ds Max导出插件",
  "VECTORWORKS_EXPORTER": "Vectorworks导出插件",
  "SIGN_OUT": "退出",
  "SKETCH_DOES_NOT_SUPPORT_LANDSCAPE_THIS_TIME": "手机横屏不支持草图功能",
  "BORDER": "边框",
  "WIDTH": "宽度",
  "TEXT": "文字",
  "FILL": "填充",
  "ADD_WALKTHROUGH_TO_COMMENT": "在批注中加入漫游",
  "ERROR_ADDING_NAVIGATION_COMMENT": "当在批注中加入漫游时出现了错误",
  "NAME-USER": "名称",
  "SAVED_BY": "保存成",
  "SETTING": "设置",
  "REQUEST_360_RENDERING": "询问360渲染服务",
  "REPLY": "回复",
  "FAILED": "失败",
  "RETRY": "重试",
  "CREATOR": "创建者",
  "DATES": "日期",
  "TYPE": "类型",
  "CLIENT_READY": "客户可见",
  "ON": "开启",
  "RECORD_COMMENT_CARDS": "重新排序模型批注",
  "PREVIOUS": "上一个",
  "NEXT": "下一个",
  "UP_DOWN_ARROW_TO_THE_NEXT_COMMENT": "上/下方向键切换批注",
  "LEFT_RIGHT_ARROW_TO_VIEW_ATTACHMENTS": "左/右方向键查看附件",
  "UPLOAD_BACKGROUND_IMAGE": "上传背景图片",
  "PRESET_IMAGES": "预设图片",
  "SELECT_A_PHOTO_FROM_COMPUTER": "从您的电脑里选择一张图片",
  "SUPPORTED_JPEG_PNG": "支持文件格式：JPEG，PNG",
  "REMOVE_IMAGE": "删除图片",
  "MODEL_UPDATING": "模型上传中",
  "PLEASE_WAIT_MOMENTATILY_WHILE_RECONVERTING": "请稍等片刻，我们正在重新转换您的模型。",
  "ERROR_OCCURRED_WHILE_CONVERTING": "转换模型时发生错误",
  "CAN_NOT_VIEW_MODEL": "由于转换此模型时发生错误，您将无法打开它。",
  "LEAVE_PAGE": "离开页面",
  "VISIT_THE_LINK_TO_VIEW_OFFLINE": "访问该离线模型链接并将其添加成书签",
  "OFFLINE_LINK": "离线链接",
  "PLEASE_REFRESH_BROWSER": "请刷新浏览器并尝试再次保存",
  "CLEAR_STORAGE": "清除存储",
  "UPGRADE_TO_SHARE_MODEL": "升级账户以便分享模型",
  "UPGRADE_TO_VIEW_MODEL_OFFLINE": "升级账户以便查看模型离线链接",
  "WE_SEND_EMAIL_TO_SHARE_MODEL": "通过我们提供的链接，您就可以随时随地分享模型。请升级到个人或者企业账户启用分享。",
  "VIEW_SAMPLE_LINK-MODEL": "查看样例模型链接",
  "STILL_ABLE_TO_VIEW_MODEL_OFFLINE": "当网络速度慢或无法联机时，您仍然可以在离线状态下访问和查看模型。请向您的客户经理咨询并升级到企业账户来使用此功能。",
  "EMBED_MODEL": "嵌入模型",
  "DEFAULT": "默认设置",
  "CURRENT_VIEW": "当前视图",
  "AUTOSTART": "自动启动",
  "MAY_EFFECT_LOADING_TIME_WITH_MULTIPLE_MODELS": "页面一旦准备就绪即加载模型。可能会影响多个模型的加载时间。",
  "SHOW_VIEW_SWITCH_BUTTON": "显示视图切换按钮",
  "DISPLAY_BUTTON_TO_SWITCH_VIEWS": "显示按钮切换不同的视图，以便更好地游览模型。",
  "SHOW_VIEW_HIDE_TOOLS": '隐藏工具',
  "DISPLAY_BUTTON_TO_HIDE_TOOLS": '不在菜单中显示工具选项。',
  "NO_COMMENTS": "没有批注",
  "NO_PROMPT": "不再提示",
  "KEYBORD_SHORTCUT": '键盘快捷键',
  "NEXT_COMMENT": "下一个批注",
  "PREV_COMMENT": "上一个批注",
  "ATTACHMENT_FULL_SCREEN": "全屏查看附件",
  "NEXT_ATTACHMENT": "下一个附件",
  "PREV_ATTACHMENT": "上一个附件",
  "QUIT_PRESENTATION_MODE": "退出演示模式",
  "SECTION": "剖面",
  "MEASURE": "测量",
  "ZOOM_AND_PAN": "缩放和平移",
  "EMBED": "嵌入",
  "UPGRADE": "升级",
  "OFFLINE_MODEL_LINK": "离线模型链接",
  "ENABLE_BIN": "启用BIM",
  "BIM_PROPERTIES": "BIM属性",
  "TREE": "树",
  "PROPERTIES": "属性",
  "COMBIMDED_PROPERTIES": "组合属性",
  "COMMON_PROPERTIES": "通用属性",
  "CONFIRM_VIEW_DIRECTION": "确认视图方向",
  "SCENESETTING": "素材设计",
  "WALKTHROUGHS": "漫游",
  "CREATE_A_WALKTHROUGH": "新建一个漫游",
  "AUTO_GENERATE_FLOOR_PLAN": "漫游动画非常简单易用。模袋自动生成平面图，您只要设置几个关键帧即可开始演示！",
  "CLICK_ON_ANY_PLANE_TO_BEGIN_WALKTHROUGH": "点击平面的任意位置，设置第一个关键帧即开始漫游。",
  "RENDER_SETTINGS": "渲染设置",
  "SETTING_NAME": "设置名称",
  "DUPLICATE_NAME": "重复名称",
  "BACKGROUND": "背景",
  "SUN_LIGHTING": "阳光",
  "OPTION": "放置样式",
  "IMAGE": "背景图片",
  "CHANGE": "改变",
  "CHANGE-BG_IMG": "更换图片",
  "CHOOSE_IMAGE": "选择图片",
  "FILTERS": "筛选",
  "ENHANCED_RENDERING": "增强渲染",
  "BASE_RENDERING_MODE" : "基础渲染模式",
  "ACCELERATED_RENDERING_MODE" : "性能模式",
  "ACCELERATED_RENDERING_MODE_INFO" : "性能模式下一些特效和模型构建会在镜头转动的时候关掉以优先保证显示的流畅度。",
  "ARCHITECT_EFFECT": "建筑师特效",
  "PEN_DETAIL": "画笔细节",
  "INK_CONTRAST": "对比度",
  "BLACK_WHITE": "黑白效果",
  "SUNLIGHT_LOCATION": "日照位置",
  "BRIGHTNESS": "亮度",
  "DIRECTION": "方向",
  "ENVIRONMETAL_REFLECTION": "环境反射",
  "SHADOW": "阴影",
  "SPECULAR": "镜面",
  "PROFILE_LINES": "轮廓线",
  "FIELD_OF_VIEW": "视图范围",
  "RESET": "重置",
  "SAVE_AS": "保存成",
  "UPDATE": "更新",
  "LAYERS": "层",
  "EFFECTS": "效果",
  "MATERIALS": "材料",
  "TOP": "上",
  "BOTTOM": "下",
  "FRONT": "前",
  "BACK": "后",
  "RIGHT": "右",
  "LEFT": "左",
  "ISOMETRIC": "等轴视图",
  "GO_BACK": "返回",
  "CLICK_SECTION_TO_MOVE_LEFT_RIGHT": "点击一个剖面，并从左移到右",
  "PICK_FACE_TO_ADJUST": "请选择您想要调整的边界框的面",
  "CHANGE_PASSWORD": "更改密码",
  "CURRENT_PASSWORD": "当前密码",
  "NEW_PASSWORD": "新密码",
  "PASSWORD_NOT_MATCH_CONFIRMATION": "您的新密码与确认密码不符。",
  "CURRENT_PASSWORD_DOES_NOT_MATCH_RECORD": "您的当前密码与记录不符。",
  "MUST_PROVIDE_YOUR_CURRENT_PASSWORD_TO_CHANGE_IT": "您必须提供当前密码才能改变。",
  "CHANGE_PASSWORD_SUCCESSFULLY": "您的密码已成功修改！",
  "PER_MONTH": "每月",
  "CURRENT_PLAN": "当前套餐",
  "500MB_STORAGE": "500MB的存储空间",
  "UP_TO_200MB_PER_MODEL": "单个上传模型最大200MB",
  "UNLIMITED_PROJECTS": "无限量的项目",
  "VR_VIEWING": "VR模式",
  "3D_COMMENTING": "三维批注",
  "WALKTHROUGH_ANIMATION": "漫游动画",
  "PANORAMA_IMAGE_VIEWING": "全景图查看",
  "YOUR_CURRENT_PLAN": "您的当前套餐",
  "3GB_OF_STORAGE_PER_USER": "每个用户有3GB存储空间",
  "UP_TO_750MB_PER_MODEL": "单个上传模型最大750MB",
  "EMBED_MODELS_WITHOUT_MODELO_LOGO": "嵌入模型没有模袋商标",
  "CLIENT_SHARE_LINK": "客户分享链接",
  "USER_PERMISSION_CONTROLS": "用户权限控制",
  "COLLABORATE_WITH_TEAM_MEMBERS": "与团队成员协作",
  "MANAGE_LICENSES": "管理席位",
  "AFTER_THE_TRIAL_ENDS_NEW_PRICE_WILL_BE": "试用期结束后，新的价格将是",
  "PLEASE_REMOVE_USERS_BEFORE_REDUCE_LICENSES": "在尝试减少用户席位数量之前，请先删除多出的用户。",
  "ERROR_UPDATING_YOUR_ACCOUNT": "更新您的帐户时出错，请刷新并重试。如果问题仍然存在，请联系hi@modelo.io",
  "UPDATE_LICENSE": "更新席位",
  "CANCEL_CURRENT_PLAN": "取消当前套餐",
  "REQUEST_A_DEMO-L": "申请企业演示",
  "STORAGE_BASED_PRICING": "基于存储空间的定价",
  "UNLIMITED_FILE_UPLOAD_SIZE": "无限制的文件上传",
  "UNLIMITED_VR_VIEWING": "无限量的VR模式",
  "UNLIMITED_3D_COMMENTING": "无限量的三维批注",
  "UNLIMITED_WALKTHROUGH_ANIMATION": "无限量的漫游动画",
  "UNLIMITED_PANORAMA_IMAGE_VIEWING_AND_SHARE": "无限量的全景图查看和分享链接",
  "UNLIMITED_EMBED_MODELS_WITHOUT_MODELO_LOGO": "无限量的无商标嵌入模型",
  "VIEW_OFFLINE": "查看离线链接",
  "DEDICATED_CUSTOMER_SUCCESS_MANAGER": "专属客户经理",
  "SUPPORT_RESPONSE_WITHIN": "支持",
  "CHINA_LOCAL_SERVER": "中国本地服务器",
  "ACCESS": "进入",
  "COMPANY_NAME": "公司名称",
  "CARD_NUMBER": "银行卡号",
  "EXPIRATION_DATE": "过期日期",
  "SECURITY_CODE": "安全码",
  "TRANSFER_ALL_PROJECTS_FROM_PERSONAL_TO_LIGHT_ACCOUNT": "将试用帐户里的所有项目转移到您的新个人帐户里",
  "BEEN_CHARGED_FIRST_BILL": "您将从今天开始被计费",
  "CARD_NOT_CORRECT": "您提供的银行卡信息不正确。",
  "BEFORE_CANCELLING": "在您取消当前套餐之前，请阅读以下内容：",
  "CANCELLING_PLAN_LINE2": "您的帐户将被降级为试用帐户，如果您试用的项目总存储空间超过5GB，您将被要求需要离开或者删除其中一些。",
  "CANCELLING_PLAN_LINE3": "我们会通过电子邮件来确认您的取消。",
  "BACK-RETURN": "返回",
  "BACK-RETURN-SIMPLE": "返回",
  "CONFIRM_CANCELLATION": "确认取消",
  "PAYMENT_METHOD": "支付方式",
  "CREDIT_CARD_CAN_NOT_BE_PROCESSED": "您的信用卡无法处理。",
  "INVALID_EXPIRATION_DATE": "过期日期无效",
  "WE_USE_STRIPE": "我们使用Stripe处理交易，以确保您的所有付款都安全并加密。",
  "SUBSCRIBED_TO_AT_LEAST_ONE_PAID_ACCOUNT": "您目前至少订阅了一个付费帐户",
  "PAYMENT": "支付",
  "AMOUNT": "账户",
  "RESTART_PLAN": "重新开始付费账户",
  "NO_AMOUNT_DUE_AFTER_CURRENT_PERIOD": "在当前计费周期结束后不会再有任何扣款",
  "COMPANY_LOGO": "公司商标",
  "SHOW_LOG_TO_SHARE_LINKS_AND_EMBED_MODELS": "在客户分享链接和嵌入模型中显示您的公司商标",
  "ACCOUNT_BILLING": "账户和账单",
  "STORAGE": "储存空间",
  "MEMBERS": "成员",
  "COMPANY_PROJECTS": "公司项目",
  "CREATED_BY": "创建自",
  "JOIN": "加入",
  "EMAIL_NOTIFICATION": "邮件通知",
  "YOUR_CHANGES_HAVE_BEEN_SAVED": "您的修改已被保存",
  "SELECT_ALL": "全选",
  "DESELECT_ALL": "取消全选",
  "SOMEONE_LEAVES_A_COMMENT_SCREEN_CAPTURE_SKETCH": "当有人添加了一个三维批注",
  "SOMEONE_ASSIGNS_ME_A_TASK": "当有人分配给了您一个任务",
  "SOMEONE_UPLOADS_A_MODEL": "当有人上传了一个模型",
  "PERSONAL_INFO": "个人信息",
  "EDIT_NAME": "编辑名字",
  "DONT_HAVE_PROJECTS_CREATE_PROJECT_TO_ALTER_EMAIL_SETTINGS": "您还没有创建任何项目，请创建项目之后再来更改邮件通知提醒吧",
  "PERSONAL-ACCOUNT": "试用账户",
  "LIGHT-ACCOUNT": "个人账户",
  "BUSINESS-ACCOUNT": "企业账户",
  "DAYS_UNTIL_DEADLINE": "天到截止日期",
  "DAYS_LATE": "天以后",
  "USERS_ALREADY_IN_COMPANY": "用户 {{ email }} 已经在您的公司里了",
  "FAILED_TO_INVITE_USERS_TO_COMPANY": "在邀请该用户 {{emailString}} 到公司时发生错误。",
  "INVITE_TEAM_MEMBERS_TO_PROJECT": "邀请成员到项目",
  "ADD_COMPANY_MEMBERS_TO_THIS_PROJECT": "添加公司成员到该项目",
  "INVITEES_FULL_ACCESS_WARNING_HEADER": "有些被邀请用户不具备访问该项目的全部访问权限",
  "INVITEES_FULL_ACCESS_WARNING_MESSAGE": "不是该公司的成员，这（些）用户将以客户身份被添加到该项目中，在此项目中只拥有有限的访问权限，如果您想授予这（些）用户访问此项目的全部权限，请联系贵公司的管理员以将此用户添加到您的公司。",
  "ERROR_INVITING_FOLLOWING_USERS": "邀请该用户时发生错误: {{ users }}",
  "CHANGE_IMAGE_TYPE": "更换{type, select, MODEL{模型} other{项目}}图片",
  "ARE_YOU_SURE_YOU_WOULD_LIKE_TO_DELETE": "您确定要删除 {{firstName}} {{ lastName }}吗",
  "ERROR": "错误",
  "LEARN_MORE": "了解更多",
  "YOU_CAN_SET": "您可以设定<b>可以编辑</b> 来为项目成员提供某些功能。",
  "YOU_CAN_SHARE": "您可以设定 <b>可以共享</b> 来为项目成员提供某些功能。",
  "IMAGES_OF_MODELS": "模型的图片",
  "SAVE_AS_TYPE_IMAGE": "设置成{type,select, MODEL{模型} other{项目}}封面",
  "DELETE-OBJECTS": "删除 {{ object }}",
  "ARE_YOU_SURE_YOU_WOULD_LIKE_TO_DELETE-ITEMS": "您确定要删除{itemName, select, render{效果图} Review{反馈} Model{模型} folder{文件夹} other{东西} }吗?",
  "CATION_THIS_CANNOT_BE_UNDONE_CHECK_BOX_TO_CONFIRM": "注意：这将不能被撤销. 请检查 {isFolder, select,  true{boxes} other{box} } 来确认。",
  "ALL_DESIGN_REVIEWS_MODEL_WILL_BE_DELETED": "当有人添加了一个三维批注",
  "ALL_DESIGN_REVIEWS_WILL_BE_DELETED": "确认删除{isPlural, select, true{文件夹} other{模型}}所有批注",
  "ARE_YOU_CERTAIN_YOU_WANT_TO_DELETE_PROJECT_X": "您确定要删除这个项目 <span>{{ projectName }}</span>吗？",
  "THIS_WILL_PERMANENTLY_DELETE_THE_PROJECT_X": "所有{ isPlural, select, true{ 文件夹 } other { 项目 }} 下的设计批注都将被删除",
  "SEND_SELECTED_REVIEW_TO": "发送 {numberOfReviews, plural,  =1{}  other{ # }} 选择的 {numberOfReviews, plural,  =1{review}  other{reviews}} 到：",
  "ADD_A_NEW_FILE": "新建文件",
  "X_STORAGE_PER_USER": "<b>每个用户</b>的存储 {{ storage }}",
  "CONGRATULATIONS_ON_UPGRADING_TO_LIGHT": "恭喜您升级到个人账户。您的试用账户 {transferAll, select, true{<span>以及账户内所有内容</span>} other {} } 仍然可以通过点击标签来访问",
  "PERSONAL_AND_THEN_SELECTING_FROM_THE_DROP_DOWN": "<b>个人帐户</b> 然后从下啦菜单中选择 <b>{{ fullName}} 账户。</b>",
  "X_ACCOUNTS_NAME": "<b>{{ fullName }}的账户</b>。",
  "SELECT_COMPANY_TO_TRANSFER_YOUR_PROJECT_TO": "选择一个公司来转移您的 <span >\"{{ projectName }}\"</span> 。转移完成后，选定的公司将是这个项目的唯一所有者。",
  "INVITE_TEAM_MEMBERS_TO_PROJECTS": "邀请 <b>成员</b> 到项目",
  "INVITE_UNLIMITED_VIEW_ONLY_MEMBERS_TO_PROJECTS": "邀请无限量的 <b >客户</b> 到项目中",
  "ADD_ANOTHER_COMPANY": "添加另一个公司",
  "CHOOSE_STEREOSCOPIC_FORMAT": "选择立体格式，例如6 x 1或12 x 1",
  "CHOOSE_SPHERICAL_PANO_FORMAT": "选择球形全景格式，通常由360摄像机拍摄",
  "THE_X_PAGE_REQUIRE_BEING_LOGGED_OUT": "该 {{page}} 页面需要退出。点击下面的继续登出后进入该页面。",
  "IF_AT_ANY_TIME_YOU_WOULD_LIKE_TO_UNSUB": "如果您在任何时候想取消订阅未来的电子邮件，可以发送电子邮件至<a href='mailto:hi@modelo.io'>hi@modelo.io</a> 或按照每封电子邮件底部的说明进行操作，我们将立即将您从所有列表中删除。",
  "WE_CANT_FIND_YOUR_EMAIL": "我们无法找到使用此电子邮件地址的帐户。您是否想 <a  class='login-form__top-error-link' href='/register'>创建一个新账户？</span>",
  "NO_ACCOUNT": "还没有账户吗？",
  "SIGN_UP": "注册",
  "CREATE_AN_ACCOUNT_TO_JOIN_X": "创建账户来加入 {type, select, company{company} other{project}}",
  "CREATE_A_FREE_ACCOUNT": "开始使用试用账户",
  "CREATE_AN_ACCOUNT-SHORT": "新建一个账户",
  "ONLY_10_LICENSES_ARE_ALLOWED_UNDER_THE_LIGHT_PLAN": "个人帐户最多只允许邀请10个席位。请发邮件至<span class='change-plan-dialog__company-enterprise--email'>sales@modelo.io</span>来升级到我们的企业账户",
  "CANCEL_WILL_BE_EFFECTIVE_AT_THE_END_OF_THIS_BILLING_PERIOD": "取消将在当前结算周期结束后生效<b>{date, date, short}</b>",
  "EDIT_COMPANY_NAME": "编辑公司名称",
  "CHANGE_PLAN": "更改套餐",
  "NEXT_PAYMENT_DUE": "下次付款日期:  {d0, date, short}",
  "LIGHT_PLAN_ENDS_ON": "您的个人账户将结束于 {d0, date, short}",
  "PLAN_EXPIRED_ON_X": "套餐于 { {d0, date, short}过期",
  "UPDATE_PAYMENT_METHOD": "更新支付方式",
  "FREE": "免费",
  "PROJECT_WALL": "项目讨论区",
  "REVIEW_DISCUSSION": "反馈讨论",
  "MESSAGE": "消息",

  "GENERATE_PANO_APP" : "生成全景",
  "MODELS":"模型",
  "MODELS_PLURAL":"模型",
  "REVIEWS":"反馈",
  "GET_TOKEN_FOR_PLUGIN": "获取上传代码",
  "DO_YOU_WANT_TO_GENERATE_AN_PANO_APP_FOR_OFFLINE_USAGE_CURRENTLY_USERS_ARE_ONLY_ABLE_GEN_EVERY_6_HOURS": "模袋 允许你将所有的全景展示文件打包到一个可执行文件(.exe)。每六小时你可以生成一个应用。",
  "USERS_CAN_ONLY_GENERATE_ONE_PANO_EVERY_X_HOURS" : ` 用户每 {{ genTime }} 小时可以生成一个应用, 你需要等到 {{ nextDownloadTime }} 你才可以生成一个新的应用. 如果你有更多需求，请联系我们 sales@modelo.io`,
  "MINS":"分钟",
  "INVALID_DATE":"待定",
  "SMOE_ONE_ACCOUNT":"的账户",
  "MODEL_NUMBER":"个模型",
  "REVIEWS":"条反馈",
  "FOLDER":"文件夹",
  "MODEL":"模型",
  "FAQ":"新手教程",
  "DETAIL":"编辑",
  "VIEW":"视图",
  "YOUR_MODEL":"你的模型",
  "MODEL_PROCESSED":"已经上传成功，可以查看。",
  "MODEL_UPDATE_SUCCEED_TO_VIEW":"已经上传成功，可以查看。",
  "HIDE_BRANDING":"隐藏商标",
  "ADD_BIM_AND_PROPERTIES_MODEL":"添加BIM构建信息到你的模型",
  "IMPORT_BIM_AND_PROPERTIES_FROM_REVIT_MODELS":"模袋现在可以将BIM构件信息以及其他更多内容从Revit模型直接导入到你的设计。请联系您的商务经理以升级账户获得更多功能。",
  "RENDER":"效果图",
  "REVIEW":"反馈",

  "MODEL_MISSING_MTL":"您的模型似乎缺少<mark>mtl</mark>文件…请将obj文件和mtl文件打包为zip文件再尝试上传。",
  "MODEL_NOT_BUILD_BY_TRIANGULAR_MASH":"你的模型可能非完全<mark>三角面建模</mark>或者无<mark>几何数据</mark>…",

  "360_TOUR": "全景漫游",
  "FLOOR_PLAN": "建筑平面图",
  "SELECT_UPLOAD_FILE_TYPE": "选择上传文件类型",
  "PANORAMA_IMAGE": "360全景图",
  "FLOORPLAN_IMAGE": "建筑平面图",

  "DOWNLOADING_AND_PROCESSING_MODEL": "模型加载处理中...",
  "DOWNLOADING_TEXTURE_X": "下载纹理...{{ texture }}",
  "MODEL_LOAD_ERROR-HEADER": "模型加载错误",
  "MODEL_LOAD_ERROR-MESSAGE": "抱歉，加载模型时出错了。别担心，我们会通知内部错误报告系统。如果您仍然遇到问题，请联系我们的支持团队，我们会帮您解决。",
  "PANORAMA_LOAD_ERROR-HEADER": "您的全景无法加载",
  "PANORAMA_LOAD_ERROR-MESSAGE": "由于一些技术上的障碍，无法加载您的全景。",
  "SAVE_360_TOUR_CHANGES-HEADER": "保存更改",
  "SAVE_360_TOUR_CHANGES-MESSAGE": "您希望在全景漫游中保留改动吗？",
  "PANORAMA_LINKED-HEADER": "全景图已有链接",
  "PANORAMA_LINKED-MESSAGE": "已有平面图链接到此全景图。",
  "PDF_DOWNLOAD_ERROR-HEADER": "下载错误",
  "PDF_DOWNLOAD_ERROR-MESSAGE": "哎呀，出错了，请稍后再试。",
  "UPDATE_ENTERPRISE_PAYMENT_METHOD-HEADER": "请联系我们更新付款方式",
  "UPDATE_ENTERPRISE_PAYMENT_METHOD-MESSAGE": "请通过邮箱sales@modelo.io来联系我们的销售代表，以便更新您的付款方式。",
  "PROVIDE_PDF_PASSWORD-HEADER": "PDF是加密的",
  "PROVIDE_PDF_PASSWORD-MESSAGE": "请提供密码",
  "EXIT_FULL_SCREEN": "退出全屏",
  "FULL_SCREEN": "全屏",
  "FIRST_PERSON_VIEW_(SHIFT_+_V)": "第一视角（Shift + V）",
  "ORBIT_VIEW_(SHIFT_+_V)": "轨道视角（Shift + V）",
  "WALKTHROUGH": "漫游",
  "SCREEN_CAPTURE": "屏幕截图",
  "COMMENTS": "批注",
  "SKETCH": "草图",
  "TOOLS": "工具",
  "BIM": "BIM",
  "HD": "高清",
  "ADD_NOTE": "添加注释",
  "EDIT_NOTE": "编辑注释",
  "HIGH_RES": "高分辨率",
  "EMAIL_ALL_SCREENSHOTS": "邮件发送所有屏幕截图",
  "DOWNLOAD_ALL_SCREENSHOTS": "下载所有屏幕截图",
  "MANAGE_WALKTHROUGHS": "管理漫游...",
  "CREATE_WALKTHROUGH": "新建漫游",
  "START_ANIMATION": "开始漫游",
  "ADD_WAYPOINT": "添加航点",
  "REMOVE_WAYPOINT": "删除航点",
  "CHANGE_ELEVATION": "变换高度",
  "GO_TO_LAST_LEVEL": "到达上一层",
  "GO_TO_NEXT_LEVEL": "到达下一层",
  "ELEVATION": "高度",
  "SPEED": "播放速度",
  "PAUSE": "暂停",
  "UPLOAD_ASSETS": "上传文件",
  "CREATE_NEW_FOLDER": "新建文件夹",
  "FOLDER_WITH_SAME_NAME_ALREADY_EXISTS": "该文件夹名已存在，请重新命名.",
  "CANNOT_NAME_FOLDER_ROOT": "抱歉，您不可以把文件夹命名为 \"root\".",
  "USING_REVIT": "使用Revit",
  "GET_THE_EXPORTER_PLUGIN": "下载Revit插件",
  "GRAPHIC DISPLAY OPTION": "图形显示选项",
  "SHADING": "阴影",
  "REALISTIC": "真实",
  "REDUCE_TEXTURE_FILES_FOR_FASTER_RENDERING": "为加快渲染减少纹理文件大小",
  "IMPORT_COMMENTS_AND_WALKTHROUGHS_FROM": "导入的批注和漫游来自",
  "EMAIL_DOWNLOAD_LINK_TO_PEOPLE_ONCE_MODEL_HAS_BEEN_CONVERTED": "一旦模型转换完成后发送下载链接给别人",
  "GET_UPLOAD_TOKEN": "使用插件上传",
  "SELECT_MODEL_FROM_YOUR_COMPUTER": "请从您的电脑里选择模型",
  "WERE_SORRY_THIS_FILE_IS_NOT_SUPPORTED": "抱歉，我们不支持这个文件类型",
  "LOOKS_LIKE_THIS_IS_A_REVIT_FILE_PLEASE_USE_OUR_REVIT_EXPORTER_PLUGIN": "我们检测到您上传了一个Revit文件，请使用我们的Revit导出插件来上传您的文件。",
  "DROP_YOUR_FILES_HERE": "把您的文件放在这里",
  "X_MODELS": "{ models }模型",
  "SHARE_ASSET_FOLDER": "分享文件夹",
  "SHARE_ASSET": "分享文件",
  "EASILY_SEND_LINKS_TO_COLLEAGUES_AND_CLIENTS": "简单轻松地将链接发送给您的同事和客户。",
  "THIS_FOLDER_WILL_NOT_SHOW_ANY_INDICATORS": "这个文件夹不会显示任何指标。",
  "SEND_FILE_DOWNLOAD_LINK_TO": "发送文件下载链接到",
  "SHARE_PDF_LINK_TO": "分享PDF链接到",
  "ADD_MESSAGE_OPTIONAL": "在这里添加描述（可选）",
  "LINK_TO_FILE": "连接到文件",
  "COPY": "复制",
  "COPIED": "已复制",
  "X_ITEMS": "{ items }项",
  "DATE_UPLOADED": "上传日期",
  "NEW_ASSET_NAME": "新文件名",
  "RENAME_ASSET": "重新命名文件",
  "X_FILES_UPLOADING": "{ files }文件上传中",
  "SELECT_USERS_FROM_YOUR_COMPANY": "从您的公司里选择用户",
  "ENTER_EMAIL_ADDRESSES": "输入邮箱地址",
  "UNSELECT_ALL": "取消全部选择",
  "VIEW_UPDATES": "查看更新",
  "VIEW_MODEL_PREPARATION_TIPS": "查看模型演示技巧",
  "UPLOADED_BY": "来源于",
  "ADD_A_DESCRIPTION": "添加描述",
  "DELETE_MODEL": "删除模型",
  "EDIT_NAME_NOTE": "编辑名字/标记",
  "RE_UPLOAD_MODEL": "重新上传模型",
  "MODEL_UPLOADED_FROM_PLUGIN": "模型通过插件上传, 无法下载",
  "DOWNLOAD_MODEL": "下载模型",
  "NO_BIM_ELEMENTS_OR_PROPS_IN_MODEL-HEADER": "在您的模型中找不到BIM元素或属性",
  "NO_BIM_ELEMENTS_OR_PROPS_IN_MODEL-MESSAGE": "当您上传包含BIM元素和属性的的Revit模型时，系统会自动导入。请确保您已经安装了模袋最新的Revit插件，并尝试重新上传模型。如果您仍然遇到问题，请通过hi@modelo.io与我们联系。",
  "CHANGE_NUMBER": "更改电话号码",
  "ADD_NUMBER": "添加电话号码",
  "UNHIDE": "显示",
  "HIDE": "隐藏",
  "BRANDING_IS_CURRENT_HIDDEN_ON_SHARE_LINS_AND_EMBED_MODELS": "在客户分享连接和嵌入模型中，暂时隐藏商标",
  "OPPS_SOMETHING_WENT_WRONG_WHEN_UPLOADING_BRANDING": "抱歉，上传商标时出错了。请再试一次。",
  "UPLOAD_COMPANY_LOGO": "上传公司商标",
  "OPPS_SOMETHING_WENT_WRONG_WHEN_UPDATING_BRANDING": "抱歉，上传商标时出错了。请再试一次。",
  "SET_AS_COMPANY_LOGO": "设置为公司商标",
  "CHANGE_IMAGE": "更换图片",
  "NO_PAYMENT_METHOD_ON_FILE": "没有记录可付款的方式",
  "X_FILE_SPACED_USED": "{{ totalSpace }} 中的{{spaceUsed}} {{spaceUsedByPct}}% 已使用",
  "X_FILE_SPACED_USED_OF_UNLIMITED": "<b>无限空间</b> 中的{{ totalSpaceUsed }} 已使用",
  "X_SPACE_MODEL_FILES": "模型 ({{ spaceUsed }})",
  "X_SPACE_ASSET_FILES": "文件 ({{ spaceUsed }})",
  "ATTACHMENTS": "附件",
  "HDRI_1": "HDRI 1",
  "HDRI_2": "HDRI 2",
  "HDRI_3": "HDRI 3",
  "HDRI_4": "HDRI 4",
  "CLEAR_SKY_1": "清澈天空 1",
  "CLEAR_SKY_2": "清澈天空 2",
  "CLOUDY_SKY_1": "多云天空 1",
  "CLOUDY_SKY_2": "多云天空 2",
  "DUSK_SKY_1": "黄昏天空 1",
  "DUSK_SKY_2": "黄昏天空 2",
  "GREY_BACKGROUND": "灰色背景",
  "NIGHT_SAILING": "黑夜星空",
  "RAINY_SHORE": "细雨海岸",
  "MORNING_FOG": "清晨薄雾",
  "GLACIER_SEA": "冰川海面",
  "MIDNIGHT_LA": "情迷加州",
  "SUMMER_SAPPHIRE": "盛夏宝蓝",
  "SPEED_SLOWEST": "非常慢",
  "SPEED_SLOWER": "慢",
  "SPEED_NORMAL": "正常",
  "SPEED_FASTER": "快",
  "SPEED_FASTEST": "非常快",
  "BACKGROUND_IMAGE_TYPE_WALL_PAPER": "平铺",
  "BACKGROUND_IMAGE_TYPE_WALL_PAPER_TILE": "平铺",
  "BACKGROUND_IMAGE_TYPE_SKY_DOME": "穹顶",
  "CSS_FILTER_NORMAL": "标准",
  "CSS_FILTER_BLUE_PRINT": "蓝调",
  "CSS_FILTER_DARK_SKY": "黑夜",
  "CSS_FILTER_VINTAGE_PAPER": "复古",
  "CSS_FILTER_GRAYSCALE": "灰度",
  "TIME": "时间",
  "UNSELECTED": "请选中一个部位",
  "DATE": "日期",
  "RENDER_WAITING": "排队中...",
  "NAVIGATION_PREFIX": "漫游_",
  "CUTTING_SPEED": "切割速度",
  "HIDE_SECTION_BOX": "隐藏剖面框",
  "ROTATE_SECTION_BOX": "旋转剖面框",
  "RESET_SECTION": "重置剖面",
  "FEET_SHORTHAND": "英尺",
  "INCH_SHORTHAND": "英寸",
  "CM_SHORTHAND": "厘米",
  "MM_SHORTHAND": "毫米",
  "METER_SHORTHAND": "米",
  "SLOW": "慢",
  "FAST": "快",
  "COMMENT_RENDER_RADIUS": "跳转范围：",
  "END_PRESENTATION": "结束演示",
  "ADD_A_COMMENT": "添加批注",
  "ADD_VIEW": "添加视图",
  "PRESENT": "演示",
  "FROM-DATE": "从",
  "TO-DATE": "到",
  "ALL": "所有",
  "PLAY": "播放",
  "ADD_WALKTHROUGH": "添加漫游",
  "SCREENSHOT_PREFIX": "屏幕截图_",
  "UNDO": "撤销",
  "REDO": "恢复撤销",
  "NEW_SKETCH": "新草图",
  "REMOVE": "清除",
  "DOWNLOAD": "下载",
  "ADD_MESSAGE_TO_THE_EMAIL": "在邮件中附言",
  "ADD_TEXT": "添加文字",
  "ADD_FILE": "添加文件",
  "REORDER": "重新排序",
  "3D_PREFIX": "3D_",
  "ASSIGNEE": "被分配者",
  "CREATE_NEW_WALKTHROUGH": "创建新的漫游...",
  "WALKTHROUGH...": "漫游...",
  "MANAGE_SETTINGS": "管理设置",
  "BLANK_NAME": "空白名",
  "RESTORE": "恢复",
  "OEMBED": "OEMBED",
  "HTML": "HTML",
  "USE_MODELO_TO_SHARE_YOUR_3D_MODELS_THROUGH_YOUR_BLOG": "在您的作品展示或博客中使用模袋来分享3D模型吧。",
  "CLIENT_READY_CARDS": "客户可见批注",
  "SAVE_MODEL_AND_VIEW_OFFLINE_IN_CHROME": "在Chrome浏览器中保存模型查看离线模式",
  "ONCE_THE_MODEL_IS_DOWNLOADED_WE_WILL_CREATE_A_LINK": "当模型下载完成后，我们将为您创建一个不需要互联网的模型链接。",
  "UNKNOWN_ERROR": "未知错误",
  "OFFLINE_STORAGE_IN_YOUR_COMPUTER": "离线储存在您的电脑上",
  "X_SPACE_USED": "{{ totalSpace }} 中的 {{ usedSpace }} 已使用",
  "SET_EXPIRATION": "设定截止日期",
  "NO_EXPIRATION": "没有截止日期",
  "1_DAY": "1天",
  "7_DAYS": "7天",
  "30_DAYS": "30天",
  "FIRST_COMMENT": "首个批注",
  "NONE": "无",
  "SEND_A_MESSAGE": "发送信息",
  "DELETE_REVIEW": "删除反馈",
  "SKETCH_ON_REVIEW": "在反馈上画草图",
  "GENERATE_PDF": "导出为PDF",
  "DOWNLOADING": "下载中 ...",
  "COPY_THIS_TOKEN_TO_YOUR_PLUGIN_AND_UPLOAD_YOUR_MODEL_FROM_THERE": "将此代码复制到您的插件并从那里上传您的模型",
  "ADD_A_MESSAGE": "添加信息",
  "OPTIONS": "选项",
  "FOLDER_NAME": "文件夹名",
  "RE_UPLOAD_PANORAMA": "重新上传全景图",
  "EMBED_360_TOUR": "嵌入全景漫游",
  "SELECT": "选择",
  "ADD_HOTSPOT": "添加航点",
  "CLICK_TO_ADD_LINK": "点击增加链接",
  "SELECT_THE_NEXT_360_IMAGE_FROM_BOTTOM_BAR": "请从底部栏里选择下一个全景图",
  "CLICK_ANYWHERE_TO_UPDATE_THE_POSITION": "点击任意处更新位置",
  "SHARE_360_TOUR": "分享全景漫游",
  "LINK_TO_360_TOUR": "连接到全景漫游",
  "CHOOSE_THE_ENTERING_VIEW": "请选择进入画面",
  "PICK_WHICH_VIEW_THE_DESTINATION_360_IMAGE_WILL_BE_SHOWING": "请选择目标全景图的显示视角",
  "GO_TO_PANORAMA": "查看全景图",
  "EDIT_POSITION": "编辑位置",
  "LOADING_X_SCENES": "加载 {scenes} {scenes, plural,  =1{ scene }  other{ scenes }}",
  "ONBOARDING-ROTATE_MODEL-TITLE": "旋转",
  "ONBOARDING-ROTATE_MODEL-MESSAGE": "点击并按住鼠标 <span>左</span> 键",
  "ONBOARDING-PAN_MODEL-TITLE": "平移",
  "ONBOARDING-PAN_MODEL-MESSAGE": "点击并按住鼠标 <span>右</span> 键",
  "ONBOARDING-ZOOM_MODEL-TITLE": "缩放",
  "ONBOARDING-ZOOM_MODEL-MESSAGE": "<span>上下滚动</span> 鼠标来进行放大和缩小",
  "ONBOARDING-PIVOT_POINT_MODEL-TITLE": "定点",
  "ONBOARDING-PIVOT_POINT_MODEL-MESSAGE": "<span>双击鼠标左键</span> 来放大并设置旋转的枢轴点",
  "ONBOARDING-PRECISE_COMMUNICATION-TITLE": "精准的沟通",
  "ONBOARDING-PRECISE_COMMUNICATION-MESSAGE": "在模型中添加批注有效传达您的想法",
  "ONBOARDING-CUSTOMIZING_VISUAL_EFFECT-TITLE": "自定义视角效果",
  "ONBOARDING-CUSTOMIZING_VISUAL_EFFECT-MESSAGE": "将3D批注与材质设置和剖面结合起来，以呈现关键视图和生动的细节。",
  "ONBOARDING-2D_ATTACHMENTS-TITLE": "二维附件",
  "ONBOARDING-2D_ATTACHMENTS-MESSAGE": "将方案，照片和其他图像附加到批注，并快速切换3D和2D视图",
  "ONBOARDING-SHARE_WITH_CONFIDENCE-TITLE": "自由地分享",
  "ONBOARDING-SHARE_WITH_CONFIDENCE-MESSAGE": "把批注设为 '客户可见' 后，当您在展示时，您的客户只能见到这些批注",
  "ONBOARDING-SWIPE_FROM_COMMENT_TO_COMMENT-TITLE": "从一个批注滑动到另一个批注",
  "ONBOARDING-SWIPE_FROM_COMMENT_TO_COMMENT-MESSAGE": "",
  "ONBOARDING-SWIPE_COMMENT_TO_VIEW_AND_REPLY-TITLE": "点击批注即可查看视图和回复",
  "ONBOARDING-SWIPE_COMMENT_TO_VIEW_AND_REPLY-MESSAGE": "",
  "ONBOARDING-CREATE_YOUR_FIRST_ANIMATION-TITLE": "创建您的第一个漫游",
  "ONBOARDING-CREATE_YOUR_FIRST_ANIMATION-MESSAGE": "点击左边的<b>加号</b> 来创建一个漫游。",
  "ONBOARDING-CLICK_ON_A_PLANE_TO_GENERATE_FLOOR_PLAN-TITLE": "点击任意处生成平面图",
  "ONBOARDING-CLICK_ON_A_PLANE_TO_GENERATE_FLOOR_PLAN-MESSAGE": "选择模型里的 <b>平面</b> 来生成指定高度的平面图",
  "ONBOARDING-SELECT_THE_VIEW_DIRECTION-TITLE": "选择视图方向",
  "ONBOARDING-SELECT_THE_VIEW_DIRECTION-MESSAGE": "有两种方式来设置您的相机视图方向：<ol class=\"onboarding-card__list\"><li><b>点击并按住您的模型</b>并旋转您的相机</li><li><b>将光标移到平面图上</b> 来选择方向。</li></ol>",
  "ONBOARDING-ADD_WAYPOINTS_ON_FLOORPLAN-TITLE": "在平面图上增加航点",
  "ONBOARDING-ADD_WAYPOINTS_ON_FLOORPLAN-MESSAGE": "<b>点击平面图</b> 添加更多的航点，为您的漫游设定一个路径。<div class=\"in-app-nav__onboarding-card__message\"><img class=\"in-app-nav__onboarding-card__message__gif\" src=\"/assets/images/navigation_intro_waypoint.gif\"></div><div class=\"in-app-nav__onboarding-card__gif__caption\">在平面图上添加航点后单击确认视图方向。</div>",
  "ONBOARDING-WHEN_FINISHED_PLAY_YOUR_ANIMATION-TITLE": "结束后播放您的漫游",
  "ONBOARDING-WHEN_FINISHED_PLAY_YOUR_ANIMATION-MESSAGE": "一旦设置好您的漫游路径, 点击 <b>播放键</b> 来观看您创建的漫游",
  "MOVE_MODELS_BETWEEN_FOLDERS_BY_CLICK_AND_DRAG": "可以通过点击拖拽，在文件夹中移动模型。",
  "BIM_INFO": "BIM信息",
  "CURRENTLY_YOU_HAVE_NO_SELECTION_SETS": "目前您没有选择集。",
  "HOLD_THE_CTRL_KEY_AND_CLICK_MULTIPLE": "按住Ctrl键并点击多个元素以创建一个选择集。",
  "HOLD_THE_CMD_KEY_AND_CLICK_MULTIPLE": "按住Command键并点击多个元素以创建一个选择集。",
  "SORT_INSTANCES_BY": "实例排序按照",
  "LEVEL_VIEW": "级别视图",
  "CATEGORY_VIEW": "类别视图",
  "NO_ELEMENTS_IN_THIS_LEVEL": "没有这个级别的元素",
  "SAVE_X_SELECTED_ELEMENTS": "保存{{ elements }}已选择的元素",
  "X_SELECTED_ELEMENTS": "{{ elements }}已选择的元素",
  "COMBINED_PROPERTIES": "组合属性",
  "SHOW": "显示",
  "X_MATCHES": "{{ matches }}匹配",
  "PROJECT_BROWSER": "项目浏览器",
  "SELECTION_SETS": "选择集",
  "VIEWS-MODEL": "视图",
  "DOWNLOAD_IMAGE": "下载图片",
  "ONLY_HDRI": "仅显示HDRI",
  "NOTIFICATION-RENDERING_REQUEST_FAILURE": "渲染请求失败",
  "NOTIFICATION-FOLDER_CREATE_FAILURE": "无法创建文件夹",
  "NOTIFICATION-MODEL_READY": "您的模型准备好了",
  "NOTIFICATION-CONVERSION_ERROR": "转换模型时发生错误",
  "NOTIFICATION-COMMENT_SETTING_UPDATED": "批注设置已更新",
  "NOTIFICATION-REVIEW_ADDED": "有一个新反馈",
  "NOTIFICATION-REVIEW_ADDED-EVENT_TX": "查看",
  "NOTIFICATION-ADDED_TO_PROJECT": "转换模型时发生错误",
  "NOTIFICATION-EFFECTS_SAVED": "设置已保存",
  "NOTIFICATION-EFFECTS_DELETED": "设置已删除",
  "NOTIFICATION-FLIPYZ_ASK": "模型显示错误的方向？",
  "NOTIFICATION-FLIPYZ_ASK-EVENT_TXT": "请翻转",
  "NOTIFICATION-RENDERING_CONTINUE": "继续渲染",
  "NOTIFICATION-RENDERING_VIEW": "前往查看",
  "NOTIFICATION-RENDERING_QUEUE": "已添加到渲染队列！",
  "RENDERING_VIEW": "一键渲染全景图(beta)",
  "RENDERING_VIEW_EMPTY": "您还没有创建任何3D卡片。",
  "RENDERING_VIEW_EMPTY_NEW": "立刻创建",
  "RENDERING_VIEW_COMPLETED": "已完成",
  "RENDERING_VIEW_TIME": ", 预计剩余时间",

  "ADD_TEXT": "添加文字",
  "START_RENDERING": "开始渲染",
  "SHARPNESS_HD": "1080P",
  "SHARPNESS_SD": "720P",
  "AUTORENDERING-HEADER": "全景漫游生成成功！",
  "AUTORENDERING-MESSAGE": "是否现在查看？",
  "STOP_RENDERING": "取消渲染",
  // "STOP_RENDERING": "渲染中·····",
  "NOTIFICATION-RENDERING_SUCCESS": "渲染成功！",
  "NOTIFICATION-SETTINGS_NAME_TAKEN": "名字已占",
  "NOTIFICATION-EMAIL_SENT": "邮件已发送。",
  "NOTIFICATION-EMAILS_SENT": "邮件已发送。",
  "NOTIFICATION-SETTINGS_FAILED": "设置无法保存。",
  "NOTIFICATION-ASSET_UPLOAD_FAILED": "文件无法上传。",
  "NOTIFICATION-IS_OFFLINE": "您已离线",
  "NOTIFICATION-NO_SKETCH_IN_BIM": "BIM模式中不支持建筑师特效",
  "CREATE_FOLDER_FAILED": "创建文件夹失败",
  "DELETE_FOLDER_FAILED": "删除文件夹失败",
  "RENAME_FOLDER_FAILED": "重命名文件夹失败",
  "UPDATE_PROJECT_DETAILS_FAILED": "更新模型细节失败",
  "DELETE_MODEL_FAILED": "删除模型失败",
  "UPDATE_MODEL_DETAILS_FAILED": "更新模型细节失败",
  "UPDATE_MODEL_THUMBNAIL_FAILED": "更新模型缩略图失败",
  "USER_EXCEEDED_STORAGE_LIMIT": "抱歉，您已经超过了存储限制。在升级账户或删除项目之前，您将不能再保存或上传任何文件。",
  "SAVE_SELECTION_SET_FAILED": "保存选择集失败",
  "UPDATE_SELECTION_SET_FAILED": "更新选择集失败",
  "RENAME_SELECTION_SET_FAILED": "重命名选择集失败",
  "REORDER_FAILED": "重新排序失败",
  "DELETE_SELECTION_SET_FAILED": "删除选择集失败",
  "INVITE_PEOPLE_TO_YOUR_PROJECT_START_COLLABORATING": "邀请",
  "UPGRADE_DIALOG-EXCEEDED_STORAGE_LIMIT-HEADER": "您已经超过了存储限制",
  "UPGRADE_DIALOG-EXCEEDED_STORAGE_LIMIT-MESSAGE": "您的账户包括 {{maxStorageSize}} 储存限制，您已经达到。请升级账户以便上传更多的文件。",
  "UPGRADE_DIALOG-UPGRADE_TO_SHARE_ASSETS-HEADER": "升级账户分享文件",
  "UPGRADE_DIALOG-UPGRADE_TO_SHARE_ASSETS-MESSAGE": "在Model企业账户分享文件和全景图就像发送链接通知您的同事一样简单。快来了解该计划是如何满足您所有的设计资产管理和共享需求的。",
  "UPGRADE_DIALOG-PLEASE_UPGRADE_TO_ADD_LOGO-HEADER": "请上传添加一个商标",
  "UPGRADE_DIALOG-PLEASE_UPGRADE_TO_ADD_LOGO-MESSAGE": "请升级到个人账户或企业账户来体验在演示中使用您自己的商标",
  "UPGRADE_DIALOG-UPGRADE_FOR_360_TOUR-HEADER": "升级账户使用全景漫游",
  "UPGRADE_DIALOG-UPGRADE_FOR_360_TOUR-MESSAGE": "想要通过创建身临其境，激动人心的全景漫游来演示您的设计吗？快来咨询申请我们的企业账户。",
  "UPGRADE_DIALOG-UPGRADE_TO_ADD_COLLABORATOR_SEATS-HEADER": "升级账户添加协作席位",
  "UPGRADE_DIALOG-UPGRADE_TO_ADD_COLLABORATOR_SEATS-MESSAGE": "模袋的个人账户旨在支持您的演示需求。为了更好的协作，建议您使用模袋的企业账户，因为该计划提供了一个集中管理所有沟通，设计标注和文件的平台。请联系您的客户经理来升级到企业帐户，并开始使用模袋的设计资产管理（DAM）解决方案。",
  "UPGRADE_DIALOG-UPGRADE_TO_SAVE_YOUR_SKETCH-HEADER": "升级账户保存草图",
  "UPGRADE_DIALOG-UPGRADE_TO_SAVE_YOUR_SKETCH-MESSAGE": "标注成功",
  "UPGRADE_DIALOG-SWITCH_TO_ON_OF_YOUR_PAID_COMPANIES-HEADER": "使用个人账户或企业账户来更改或去除水印",
  "UPGRADE_DIALOG-SWITCH_TO_ON_OF_YOUR_PAID_COMPANIES-MESSAGE": "切换到您的任一付费公司或添加一个新的公司来允许您插入自己品牌的水印，或是项目名称，亦或是完全删除水印。",
  "UPGRADE_DIALOG-ABLE_TO_INSERT_A_WATERMARK_OF_YOUR_BRAND-HEADER": "使用个人账户或企业账户来更改或去除水印",
  "UPGRADE_DIALOG-ABLE_TO_INSERT_A_WATERMARK_OF_YOUR_BRAND-MESSAGE": "当您升级到模袋个人帐户或者企业账户时，您将能够插入自己品牌的水印，或是项目名称，亦或是完全删除水印。",
  "UPGRADE_DIALOG-CONTINUE_CREATING_WALKTHROUGHS-HEADER": "继续新建漫游",
  "UPGRADE_DIALOG-CONTINUE_CREATING_WALKTHROUGHS-MESSAGE": "很高兴看到您充分享受模袋。试用帐户仅限于创建一个漫游。想要在您的设计中继续添加新的漫游，请升级到模袋个人帐户或者企业账户。",
  "UPGRADE_DIALOG-SHARE_ASSET_FOLDER-HEADER": "升级您的账户",
  "UPGRADE_DIALOG-SHARE_ASSET_FOLDER-MESSAGE": "共享文件夹的功能属于个人帐户和企业账户。这是与您的客户或同事分享一系列全景图像的最简单方法。",
  "UPGRADE_DIALOG-UPGRADE_TO_GET_MORE_SPACE-HEADER": "升级账户得到更多空间",
  "UPGRADE_DIALOG-UPGRADE_TO_GET_MORE_SPACE-MESSAGE": "您想上传的文件会使您超过存储限制。请立即升级以便与您的团队分享更多文件。",
  "UPGRADE_DIALOG-UPGRADE_TO_VIEW_MORE_SCENE_WITH_COMPANIES-HEADER": "升级账户查看更多场景/视图",
  "UPGRADE_DIALOG-UPGRADE_TO_VIEW_MORE_SCENE_WITH_COMPANIES-MESSAGE": "模袋是一个来助您探索设计的强大工具。试用用户仅限于查看3个导入的场景。切换到您的任一付费帐户或添加一个新的公司来导入，查看，标注，并批注无限数量的场景。",
  "UPGRADE_DIALOG-UPGRADE_TO_VIEW_MORE_SCENE-HEADER": "升级账户查看更多场景/视图",
  "UPGRADE_DIALOG-UPGRADE_TO_VIEW_MORE_SCENE-MESSAGE": "模袋是一个来助您探索设计的强大工具。试用用户仅限于查看3个导入的场景。当您升级到模袋个人帐户或企业账户时，您可以导入，查看，标注，并批注无限数量的场景。",
  "UPGRADE_DIALOG-UPGRADE_TO_START_PRESENTING_PDFS-HEADER": "升级账户演示PDF",
  "UPGRADE_DIALOG-UPGRADE_TO_START_PRESENTING_PDFS-MESSAGE": "演示是我们的专长。升级到企业账户来享用我们的PDF演示功能吧。",
  "UPGRADE_DIALOG-UPGRADE_TO_INVITE_OTHER_TO_YOUR_PROJECTS_WITH_COMPANIES-HEADER": "U升级账户邀请更多人到您的项目",
  "UPGRADE_DIALOG-UPGRADE_TO_INVITE_OTHER_TO_YOUR_PROJECTS_WITH_COMPANIES-MESSAGE": "很高兴看到您将其他人添加到项目中。请切换到您的任一付费公司或添加另一家公司来准备和使用演示。想要与您的团队协作，标注设计，访问所有模袋的设计资产管理（DAM）和演示功能吗？了解更多模袋企业账户如何满足您的需求。",
  "UPGRADE_DIALOG-UPGRADE_TO_INVITE_OTHER_TO_YOUR_PROJECTS-HEADER": "升级账户邀请更多人到您的项目",
  "UPGRADE_DIALOG-UPGRADE_TO_INVITE_OTHER_TO_YOUR_PROJECTS-MESSAGE": "很高兴看到您将其他人添加到项目中。请升级到模袋个人账户来准备和使用演示。想要与您的团队协作，标注设计，访问所有模袋的设计资产管理（DAM）和演示功能吗？了解更多模袋企业账户如何满足您的需求。",
  "UPGRADE_DIALOG-UPGRADE_TO_CHANGE_YOUR_BACKGROUND_IMAGE-HEADER": "升级账户更换背景图片",
  "UPGRADE_DIALOG-UPGRADE_TO_CHANGE_YOUR_BACKGROUND_IMAGE-MESSAGE": "我们的试用账户使用的是默认背景。请升级到模袋个人帐户或企业账户来自定义背景，并加入您的商标或其他任何图片，",
  "UPGRADE_DIALOG-UPGRADE_FOR_HD_SCREENSHOTS-HEADER": "升级您的账户",
  "UPGRADE_DIALOG-UPGRADE_FOR_HD_SCREENSHOTS-MESSAGE": "高分辨率屏幕截图属于个人帐户和企业账户。这是一个与他人合作的强大方式。立即升级您的帐户，为您的项目获取更优质的服务。",
  "UPGRADE_DIALOG-UPGRADE_TO_ADD_EXTRA_COMMENTS-HEADER": "升级账户添加更多的批注",
  "UPGRADE_DIALOG-UPGRADE_TO_ADD_EXTRA_COMMENTS-MESSAGE": "模袋是一个来助您探索设计的强大工具。试用用户仅限于查看3个导入的场景。当您升级到模袋个人帐户或企业账户时，您可以导入，查看，标注，并批注无限数量的场景。",

  "OVER_RENDERINGS-HEADER": "升级账户以渲染更多全景图",
  "OVER_RENDERINGS-MESSAGE": "免费用户只能渲染3张全景图，升级账户获得更多功能",

  "UPGRADE_DIALOG-TABLEAU_UPGRADE-HEADER": "一键升级：让你的模型数据可视化",
  "UPGRADE_DIALOG-TABLEAU_UPGRADE-MESSAGE": "把三维模型的BIM信息下载成 .csv表格，再导入Tableau实现模型与图表的信息联动",

  "UPGRADE_DIALOG-UPGRADE_TO_SET_EXPIRATION-HEADER": "一键升级：延长截止日期",
  "UPGRADE_DIALOG-UPGRADE_TO_SET_EXPIRATION-MESSAGE": "",

  "UPGRADE_DIALOG-UPGRADE_TO_GENERATE_APP-HEADER": "升级账户以便查看离线链接",
  "UPGRADE_DIALOG-UPGRADE_TO_GENERATE_APP-MESSAGE": "模袋将授权你新的功能，你可以把整个多媒体演示打包成可执行文件（.exe）。升级账户以便使用此功能。",

  "CHOOSE_A_FILE_FROM_YOUR_ASSETS": "从您所有的文件中选择一个",
  "CHOOSE_FILE": "选中的文件",

  "FULL_SCREEN-DOWNGRADING": "降级中",
  "FULL_SCREEN-OPPS_THE_URL_IS_INVALID": "糟糕，这是一个无效的链接",
  "FULL_SCREEN-YOU_ARE_NOT_CURRENTLY_A_MEMBER_OF_THIS_PROJECT": "您目前不是该项目的成员。请联系项目所有者授予您访问权限。",
  "FULL_SCREEN-THIS_PROJECT_FOLDER_OR_MODEL_DOES_NOT_EXIST_IN_OUR_DB": "在我们数据库中无法找到这个项目，文件夹或模型。它可能已被删除。",
  "FULL_SCREEN-WE_COULDNT_FIND_YOUR_PAGE": "抱歉，我们无法找到您正在寻找的页面。请尝试刷新页面。如果您仍然遇到问题，请发送邮件至hi@modelo.io，我们将会帮助您！",
  "FULL_SCREEN-MODEL_FAILED_TO_LOAD": "无法加载模型！主要原因是资源枯竭，请关闭其他未使用的标签页并刷新模型。",
  "FULL_SCREEN-WE_JUST_CLEANED_UP_A_COUPLE_THINGS_PLEASE_REFRESH": "我们打磨了一下您的模型。请点击确定来刷新页面并重新加载更新后的模型。",
  "FULL_SCREEN-THE_OWNER_OF_THIS_MODEL_HAS_EXPIRED": "这个模型的所有者帐户已过期，请联系他/她来查看模型。",
  "FULL_SCREEN-RESOURCE_DEPLETED": "资源枯竭！请关闭一些未使用的标签页，然后点击chrome webgl reload按钮来重新加载此页面。",
  "FULL_SCREEN-REFRESH_THIS_PAGE": "想要刷新此页面？ 请点击刷新按钮！",
  "FULL_SCREEN-ACCOUNT_EXPIRED": "您的账户已经过期，请续费以激活此页面。如有任何问题，欢迎随时通过hi@modelo.io联系我们。",
  "ALL-SEARCH": "全部",
  "MODELS-SEARCH": "模型",
  "ASSETS-SEARCH": "文件",
  "360_TOUR-SEARCH": "全景漫游",
  "WALKTHROUGH_SPEED_PLACEHOLDER": "例如3",
  "SAVING...": "正在保存...",
  "PRESENT_COMMENTS": "展示批注",
  "RESOLVE": "解决",
  "RESOLVED": "已解决",
  "UNRESOLVED": "未解决",
  "CREATED_A_3D_COMMENT": "已创建一条三维批注",
  "CREATED_A_SKETCH": "已创建一个示意草图",
  "CREATED_A_SCREENSHOT": "已创建一个截图",
  "CREATED_A_REVIEW": "已创建一条回复",
  "TRANSITION_SPEED_HEADER": "批注转换速度",
  "ILLUSTRATED_BT_FEIFEI_FEND": "来自冯飞飞",
  "SIGN_UP_FOR_FREE": "免费注册",
  "MODELO_IS_THE_EASIEST_WAY_TO_BRING_YOUR_3D_MODEL_INTO_THE_WEB_AND_SHARE_WITH_OTHERS": "想通过网络将模型分享给伙伴？模袋是您最便捷的方式",
  "YOUR_FILE_WILL_BEGIN_DOWNLOADING_SHORTLY": "即将开始下载您的文件",
  "OPPS_LOOKS_LIKE_SOMETHING_WENT_WRONG": "很抱歉，这里出了点问题",
  "OPPS_LOOKS_LIKE_THIS_FILE_HAS_BEEN_DELETED": "噢，这个文件似乎已被删除",
  "VIEW_BROWSER_BY": "视图选项",
  "VIEW_BY": "视图",
  "EXIT": "退出",
  "REUPLOAD_A_NEW_MODEL_TO_REPLACE_THE_OLD_MODEL": "当您上传新模型来替代原模型后，该模型链接地址, 相关设置及设计回复均被保留",
  "OPPS_SOMETHING_WENT_WRONG_WE_LOGGED_THIS_ERROR_AND_OUR_DEVELOPERS_WILL_TAKE_A_LOOK": "很抱歉，这里出了点问题。我们的工程师会尽快查看问题所在。",
  "UPLOADING...": "正在上传",
  "YOUR_ENTERPRISE_PLAN_EXPIRED_EMAIL_SALES_TO_CONTINUE_USING_YOUR_ACCOUNT": "您的企业服务方案已经过期。烦请发送邮件至 <a href='mailto:sales@modelo.io'>sales@modelo.io</a>，以便继续使用您的账户",
  "YOUR_CURRENT_PAYMENT_METHOD_FAILED_PLEASE": "您的当前付款方式有误，烦请&nbsp;",
  "UPDATE_PAYMENT_DETAILS": "更新付款方式",
  "OR": "或者",
  "DOWNGRADE_YOUR_PLAN": "降低服务方案等级",
  "TO_ACCESS_YOUR_PROJECT": "进入您的项目",
  "YOUR_PLAN_WILL_EXPIRE_IN_X_DAYS": "您的服务方案将在{willExpireIn}天后过期",
  "EMBED_ASSET": "嵌入文件",
  "THIS_ACTION_CANNOT_BE_UNDONE": "这将<span>不能</span>被撤销",
  "REUPLOAD_MODEL_FROM_PLUGIN": "通过插件重新上传模型",
  "UT_LENGTH_FEET": "英尺",
  "UT_AREA_FEET_2": "平方英尺",
  "UT_MASS_KG": "千克",
  "UT_VOLUME_FEET_3": "立方英尺",

  "UT_LENGTH_METER": "米",
  "UT_AREA_METER_2": "平方米",
  "UT_VOLUME_METER_3": "立方米",

  "CHINA_LOCAL_SERVER_ACCESS": "中国本地服务器",
  "VIEW_SETTINGS_PREFIX": "查看设置",
  "CHANGE_LANGUAGE": "更改语言",
  "CHOOSE_LANGUAGE": "选择语言",
  "ENGLISH": "英语",
  "CHINESE": "中文",
  "EN": "en",
  "ZH": "中文(ch)",
  "SELECTED_ELEMENTS": "已选中的构件",
  "MODEL_CONVERSION_ERROR_FILE_TOO_LONG": "似乎你尝试上传的文件中有部分文件或者贴图的名称过长。请尝试缩短文件名或者减少文件夹层数。",
  "CONVERSION_TAKES_TOO_LONG": '您上传的文件过<mark>大</mark>...,请减小文件大小或联系sales@modelo.io获得帮助。',
  "CURVES": "曲线",
  "ADD_ANNOTATION": "添加注释",
  "MODEL_CONVERTING_TEXT_EMAIL": "您可以离开当前页面，当您的模型准备好的时候我们会发送email通知您。",
  "GO_TO_PROJECTS_PAGE": "前往项目页面",
  "CAN_ONLY_VIEW_FILES_IN_PROJECT": "您只能查看当前项目的文件。",
  "BIM_DATA_INSIGHT_TOOL": "BIM信息发掘工具",
  "FLIP_PANORAMA_DIALOG-MESSAGE": "您是否需要反转该全景图像？",
  "DOWNLOAD_CHROME": "下载Chrome",
  "AS_CLIENT": "仅浏览",
  "AS_TEAMMEMBER": "作为团队成员",
  "MODEL_CONVERTING_TEXT_NO_EMAIL": "您可以离开当前页面，并返回这里浏览您的模型。",
  "FLIP_PANORAMA_DIALOG-HEADER": "反转全景图像",
  "COPY_SHARE_LINK": "复制分享链接",
  "TEST_WEBGL_SUPPORT": "测试WebGL是否被支持",
  "CLIENT_SIDEBAR_BODY_TEXT": "您的仅浏览权限允许您查看设计以及回复批注。如果您希望在项目中更广泛的参与合作，请与项目所有者联系，以团队成员身份加入到项目中。",
  "SUPPORTED_BROWSERS_TEXT": "我们当前支持的浏览器分别是移动版Safari，Mozilla Firefox, Microsoft Edge 以及 Google Chrome。",
  "UNSUPPORTED_WEBGL_TEXT": "您的浏览器不支WebGL。我们的3D引擎需要它及其扩展库。",
  "FLIP": "反转",
  "NAVISWORKS_EXPORTER": "Naviswork导出插件",


  "HOW_TO_EARN_MORE": "如何获取更多设计点数",
  "WHAT_IS_DESIGN_TOKEN": "什么是设计点数",
  "MODELO_DESIGN_TOKEN_IS_THE_FIRST_DIGITAL_REWARDING_FUND": "模袋设计点数是模袋与兴谷合作的第一支数字奖励基金。模袋设计点数可以用来购买模袋产品或者兑换为兴谷点数。",
  "VISIT_CINGULARITY_NETWORK": "访问兴谷网站",
  "YOUR_DESIGN_TOKEN_IS_CALCULATED_USING_THE_FOLLOWING_FORMULA": "你的设计点数是由如下方式计算得来：",
  "DESIGN_TOKEN_UPLOAD_MODEL_PLUS_ETC_X_0_DOT_25": " 设计点数由上传模型文件大小及评论数决定",
  "DESIGN_TOKEN": "设计点数",
  "GENERATE_APP": "离线模型交付",

  "GENERATE_MODEL_VIEWER_APP": "离线模型交付",
  "DO_YOU_WANT_TO_GENERATE_AN_APP_FOR_OFFLINE_USAGE_CURRENTLY_USERS_ARE_ONLY_ABLE_GEN_EVERY_6_HOURS": "模袋的离线模型交付功能可以将您的PPT, 图纸，BIM模型以及动画打包成⼀个EXE⽂件⽤于交付和展示，⽤户每六个⼩时可以下载⼀次。",
  "GENERATE": "生成",
  "THE_MODEL_VIEWER_APP_WILL_AUTO_START_DOWNLOADING_ONCE_IT_HAS_BEEN_GENERATED": " 您的离线模型已经⽣成成功，如果没有⾃动下载，请点击下⽅按钮进⾏下载。",
  "USERS_CAN_ONLY_GENERATE_ONE_MODEL_EVERY_X_HOURS": "您每六⼩时可以⽣成离线模型⼀次，下⼀次⽣成的时间为{{ nextDownloadTime }}. 如果您需要更多离线模型交付，请联系我们的客服。",
  "THE_MODEL_VIEWER_APP_WAS_GENERATED_SUCCESSFULLY": "您的离线模型APP正在被⽣成，请不要刷新此⻚，⽣成后⽂件会⾃动下载到您的电脑⾥",
  "THERE_WAS_AN_ERROR_GENERATING_YOUR_MODEL_VIEWER_APP_PLEASE_TRY_AGAIN_LATER": "您的模型貌似很特殊，在生成的过程中遇到了问题。请刷新页面后再次尝试生成，或者与我们的客服联系。",

  "GO_TO_MODEL_PAGE": "前往模型页面",

  "CLICK_TO_ADD_ANNOTATION": "点击添加注释",
  "SHARE_LINK": "分享链接",
  "TITLE": "标题",
  "HEIGHT": "高度",
  "MEDIA": "附件",
  "FLIP_PANORAMA": "翻转全景图",
  "REQUIRED": "必填",
  "ADD_NOTES": " 输入内容",
  "EDIT_ANNOTATION": "编辑注释",

  "MATERIAL_SETTING_ZOOM_HORIZONTAL": "横向缩放",
  "MATERIAL_SETTING_ZOOM_VERTICAL": "纵向缩放",
  "MATERIAL_SETTING_ANGLE": "角度",
  "MATERIAL_SETTING_SMOOTHNESS": "光滑度",
  "MATERIAL_SETTING_REFLECT": "反射度",
  "MATERIAL_SETTING_HORIZONTAL_OFFSET": "横向偏移",
  "MATERIAL_SETTING_VERTICAL_OFFSET": "纵向偏移",

  "TABLEAU_EXTENSION": "Tableau扩展",
  "TABLEAU_EXTENSION_DATA": "Tableau扩展数据",
  "GET_TABLEAU_PLUGIN": "获取Tableau插件",
  "MODEL_TOKEN": "模型代码",
  "YOU_CAN_IMPORT_THIS_DATA_INTO_TABLEAU_AS_A_DATASOURCE": "你可以下载这个数据并作为tableau的数据源。如果想链接数据联动，请选择ElenmentId数据项。",
  "DOWNLOAD_BIM_DATA": "下载BIM数据",

"CONTACT_US-HEADER": "联系我们",
"CONTACT_EMAIL-MESSAGE": "请联系我们的官方邮箱 sales@modelo.io",
"MATERIAL_SETTING_ZOOM_HORIZONTAL": "横向缩放",
"MATERIAL_SETTING_ZOOM_VERTICAL": "纵向缩放",
"MATERIAL_SETTING_ANGLE": "角度",
"MATERIAL_SETTING_SMOOTHNESS": "光滑度",
"MATERIAL_SETTING_REFLECT": "反射度",
"MATERIAL_SETTING_HORIZONTAL_OFFSET": "横向偏移",
"MATERIAL_SETTING_VERTICAL_OFFSET": "纵向偏移",
  "COUPON_CODE": "优惠券",
  "THE_COUPON_CODE_YOU_ENTERED_IS_INVALID": "您输入的优惠券代码错误，请再次输入。",

  "UPGRADE_TO_CUSTOMIZE_YOUR_BRANDING": "升级以自定义商标",
  "NOTICE": "注意",
  "ALL_MODELS_UPLOADED_FROM_FREE_USERS_WILL_BE_PUBLICLY_SHOW_IN_MODELO_EXPLORE": "所有免费用户的模型都会24小时后上传到<a target=\"_blank\" href=\"https://modelo.io/explore\">模袋发现公共展示平台</a>。如果您想要对自己的模型保持私密，",
  "PLEASE_UPGRADE_YOUR_ACCOUNT_HERE": "请移步到这里<a>升级</a>您的账户。",
  "PLEASE_ACCEPT_OUR_UPDATED_TERMS_AND_CONDITIONS": "请同意并接收我们最新的条款与协议以继续使用模袋产品",

  "UT_POWER_WATT": "w",
  "UT_VOLTAGE_VOLT": "V",

  "SCENE_SETTING_PARAM": "参数调整",
  "SCENE_SETTING_DIRECTION": "方向",
  "SCENE_SETTING_DENSITY": "密度",
  "SCENE_SETTING_POSITION": "位置",
  "SCENE_SETTING_ANGLE": "角度",
  "SCENE_SETTING_SCALE": "缩放",
  "SCENE_SETTING_PROPORTION": "比例",

"UT_POWER_WATT": "w",
"UT_VOLTAGE_VOLT" : "V",

"CLOUDY_LAWNS": "秋日旷野",
"GREEN_SUBURBAN": "城郊原野",
"RURAL_LANDSCAPE": "田园风情",
"ON_THE_ROAD": "在路上",
"GREEN_CAMPUS": "青春校园",
"OASIS": "沙漠绿洲",
"BLUE_SKY": "碧草蓝天",
"VENICE_SUNSET": "水城日落",
"MOUNTAIN_TOP": "山顶远眺",
"CLIFF_TOP": "天涯海角",

"LOADING_KOORENDER": "KooRender正在开启中... ",
"HDRI": "设置",
"HDRI-INTENSITY": "亮度",
"HDRI-DIRECTION": "方向",
  "PAGE_IS_EMPTY": "没有数据",

  "COMMENTAUTORENDER_DEFAULT": "默认",
  "COMMENTAUTORENDER_QUALITY": "清晰度",
  "COMMENTAUTORENDER_STYLE": "风格",
  "COMMENTAUTORENDER_SAVETO": "保存到",
  "COMMENTAUTORENDER_START": "开始渲染全景图",
  "COMMENTAUTORENDER_RENDERING": "渲染中···",
  "COMMENTAUTORENDER_COMPLETED": "全景图设置",

  "RENDERSTATUS_WAITING": "等待中...",
  "RENDERSTATUS_RENDERING": "渲染中...",
  "RENDERSTATUS_COMPLETED": "已完成!",

  "PANORAMA_LOADING": "正在加载全景图",
  "PANORAMA_LOADING_THUMB": "正在加载缩略图...",

    "PANORAMA_LOADING": "正在加载全景图",
    "PANORAMA_LOADING_THUMB": "正在加载缩略图...",
    
    'KOORENDER_ERROR_MODAL_CONTENT': "这个模型上传的比较早，koorender需要重新对模型进行一些处理，请重新上传模型以获得更好的渲染体验。",
  

    "RELEASE_FEATURE": "新功能",
    "RELEASE_DETAIL": "了解详情",
    "RELEASE_UPDATE": "优化内容",
    "RELEASE_DESC": "我们不断更新我们的产品，为您创造更棒的用户体验，以下是本次更新小结",
    "RELEASE_MAJOR": "新功能发布",
    "RELEASE_MINOR": "细节功能更新",
    "RELEASE_FIX": "Bug修复",
    "RELEASE_MISC": "细节优化",
    "RELEASE_VERSION": "已更新至 v{version}",

    "RELEASE_SMALL_UPDATE": "更新了一些细节功能",
    "RELEASE_SMALL_BUG": "修复了一些Bug",
    "RELEASE_SMALL_MAJORIZATION": "优化了一些使用体验",

    "INVITE_TEAM_MEMBERS_EXISTED": "用户{{existedEmails}}已经存在于该项目中",

    'ERROR_MODEL_TOOOLD': '这个模型上传的比较早，koorender需要重新对模型进行一些处理，请重新上传模型以获得更好的渲染体验。',

    "DEFAULT_TITLE": "",
    "DEFAULT_DESCRIPTION": "模袋云 一键智能生成VR漫游",
    "REGISTER_DESCRIPTION": "",
    "CHANGEBACKGROUND": "背景切换中",
    "AUTOEXPOSURE": "自动曝光",

    "UPLOAD_BACKGROUND_IMAGE" : "从本地上传",
    "CHANGE_BACKGROUND_IMAGE" : "更改背景图片",

    "CUSTOM" : "自定义",
    "PRESET": "预设",

    "INVALID_IMAGE": "无效图片",
    "CURRENT_IMAGE": "当前图片",

    "SAFE_VERIFICATION": "安全验证",
    "CONFIRM": "确认",

    "VERITIFY_ERROR": "验证码错误",
    "VERTIFITY_EXPIRED": "验证码过期，请刷新后再试",

    "PROJECT_NAME_CONNOT_BE_EMPTY":"项目名称不能为空",
    "FAQ_URL": "https://www.kujiale.com/package/3FO4K4VV2VKN?kpm=9V8.c01721ce0f7b2146.e4c6906.1598255128971",

    "CUSTOMIZED_PRICING_BASED_ON_STORAGE" : "基于存储空间的定制化定价",
    "UNLIMITED_MODEL_UPLOAD_SIZE" : "无上传模型体积限制",
    "UNLIMITED_OBJECT_QUANTITY" : "无项目数量限制",
    "UNLIMITED_SCENES_PER_MODEL_IN_VR" : "无限量VR模式场景",
    "3D_WALKTHROUGH_UNLIMITED" : "无限量漫游动画",
    "UNLIMITED_360_PANORAMIC_TOUR" : "无限量360 全景漫游",
    "UNLIMITED_CREATE_SHARE_LINKS" : "无限量生成分享链接",
    "CUSTOM_BRANDS_ON_MODEL" : "模型可以添加定制商标",
    "PERSONALIZED_SETTINGS_CUSTOMIZED_USER_PERMISSION" : "企业套餐权限管理",
    "OFFLINE_MODEL_VIEWING" : "模袋云离线模型查看",
    "BIM_VIEWER_ACCESS_BIM_PROPERTIES_AND_ELEMENTS" : "BIM模型构件属性信息管理",
    "ASSET_MARKUPS_MARKUP_AND_SHARE_PDFS_PLANS_AND_IMAGES" : "文件标注-在线生成的PDF",
    "SUPPORT_DEDICATED_CUSTOMER_SUCCESS_MANAGER" : "专属客户成功经理",
    "FREE_MODELO_ON_BOARDING_TRAINING" : "免费模袋云使用培训",

    "LEARN_MORE_URL" : "https://www.kujiale.com/hc/article/3FO4K4VPO156?utm_source=hc_nav",
    "UPLOAD_MODEL_IMPORT_COMPAT_TEXT_HELP_URL" : "https://www.kujiale.com/hc/article/3FO4K4VPO156?utm_source=hc_nav",
    "UPLOAD_MODEL_HELP" : "https://www.kujiale.com/hc/article/3FO4K4VPO156?utm_source=hc_nav",
    "MODEL_PROCESSING" : "模型处理中...",

    "UPGRADE_TO_CUSTOMIZE_URL" : "https://modeloapp.com/",
    "SHARE_360" : "全景图分享",
    "GO_TO_360_TOUR_PANEL": "到全景图页",
    "LEAVEL_THIS_PAGE_AND_GO_TO_360_TOUR_PANEL" : "分享全景图需要离开当前页去全景图页，离开前往？",
    "HAVENT_GENERATED_360" : "你还没有创建全景图。",
    "GO_TO_GENERATE" : "去创建",

    "CAN_ONLY_AHARE_NON-IMPORTED_FILES" : "只能分享非导入文件",


};

if (typeof window !== 'undefined') {
  window.ZH_TRANSLATIONS = ZH_TRANSLATIONS;
}
